sprite $Airwave_Appliance [87x150/16z] {
jTfPWceX38HXJG9n_nk-WzoXi2F5mUeiu6luG_jqRjV6_AQVUxJMJArwUqxSvUWOby7Mfd5PL1n9uhktOi84KM4aYItQ-mbTr7bC45MJsDhMn5qGjOIFeseI
0og0ILIMcACoc4VbuqAK9_RsyOGLBrKnVfVU7-75lxzWTL8qOh2cHGTx3oawM6tK6EDoTB0zkmu5zl587Ohi8xjAHLO0HnJiW3KeiWFMeCYEwI8LsL52WNPW
Z-0enu5by3xg607XJwAwHojOSc2Euieul7z_nxOSvcWLWIVcztUR8d2Oeui8h0IFMaHWC4V3CGA7UTGY0eF9KT4BWmXi-XkqjHWUHW2MJKOvlS4XmV-SVOr0
NaBc7WjHjo9ap_q8yz8MRFvoUsv7SFHNR7_2sn709n6US5BMBaKOvX-OHq0VsVgm8_6A9H7AkdzX6W5_6POHfiDs6W7zmRB3iWYlI-lBTuk7VNzQz68lmkFV
6rj5mAWy0XusUGJm-vA5mwOa0ZxU1riPUZp2d7Z1pXv4e329W4lZ4J0nZu0-i2InE0B_lIsM9c2hdri1-nfL5Q6zBAt98vW-GeGqGl7pfOpWuAiYsBmqIOGl
Imi1Yr6L4UQe-WZ-pH5S527q4T2B44Q0fUaZWA-FuDe88OymUo6CC2zDmtfnNba4HryL0H-PAe9zSmJxZWYkZ01HmTT5G5_1VbrQbqJ0yyeYO5HbX69fwWX_
K5a4cz08-vI5gA3U515yHgE5IIB4XBOcYu1gk9aemeoQUNx8pcZpfsetx-TiQp6ZuJR6mwEViXurQlRyYoqPIzM18jiYekK1MqG5Ti0zprYyFx9ZrecJeoKx
u3nW0ItOTU8aKKkMmydlNxFhn4bGmW9CsGLgzwY-t6X9s17rBGgVKYqJ9xy_gZKxIYIobr1WrubpEohxe2RmtoFteXhz-cjEd9ltn_7tiF-1yoeAWHUxInxr
sjTbyTnTqgZ5iCJUUd5_YlB4-_Vd9H0cw2cy6VLgOeAUmkp-XoK8UWgJ-v-M4A3LAoRtFosXGGTSiyeFyOKe9fRS7qiCM8XYOjdzvyHmLE7uLVGd
}

