sprite $AM_11n [150x146/16z] {
xTY9YknA38FXBakgUlytFY5CC3aOUZ9oBq1-zilsSIrIq-TXD2B6u-j2V25hB6d6zwcsRjLlkbMtwbRTgZ6-K1LRu-jKGZ2-JhMsSAjkrQtwJBVgLld5rkzL
U9EA1QjKnNoZQisvy0lLO031yR49rQerfRdYsrHxtwUwLRVgLjsg-3PLh2r-cmhGP8nAfVYOQX70HAMQmiTKUr6h97obIegFgSx_DPIgBOulK0rgfceF7xjW
cdHI-IvV1QbKYV6n2uP-IbN6yH7LeBH7h3rIf_1kLQH9Z4CLqBburRzNirGXf2CKgXVE2rfhObIgyx23QqkHgepTgeb04CzKGWIsIbJ_lDQQSwtdAX4xZ59T
T8_zYUgNCLwg6hgawZzZ_UIbod2rgYWPAYbUe0h9L8cZMJKeNoMXKPKcSUtfpw5D1Hq1n-EoEpznnWCWrG_nHrprapT_NkUG4LfLYW3d528eg-XK2R47oeoZ
GPLnop2PPnnCbL6l2vAfwfzNIAQgVrw3CbNzPnomdxn-5oHJrN_6q16nzWHzs3Ke7KNygC9Y-MU4CXugHkWjnPFZ_QWmyxVd6sB9Abuy8Dw58cAhVFPc-Tlp
7I5YRnIgPBsuVERJLBlUzta2a0e0SQvGlTP58fut2jNBN4IIVkrQBsKHSQcHAjlbcx92rUfAqlN_NTDWTPlI9QqNk11MZpKrkrqCjxMwNKIOZR4ZfBvvqJPj
7OYkUS56fQhhZFHDgUfoqJSTgimz8tfCgJBcrOzAbNz6sgOCAxE-4lHDsUEXjJhEs69ArMEeuOneGQLgAvRhOeyfLNlklD1eIfKvBtQYKcNEYvscL9dpGeUf
LjNp-XKBhQRWuzpusxpGYS8yL5dCFvoHVQQGudH1uok1BXCdSbVdU7bUC4rvlDrK5zU-4aJJe1I5wUfNejKKcZ7EA6DUw1vKtQL7Y6rVW_ZVPCoBQ315CIXh
NYJXcbGSpviNjm33D7ZPzFmHuXvQ1sNFQ_8d_FLvITFbeZxZ53FqV0tSUQt9Kp2VbwOpylzm_NcnYxdEYONB79H_niaYN1wK7qyiLY5DnjV0cDTa6QpdnVzA
g5PPVw_uyvgroXYKamwMIfKvA7zUfShu6fZ54vLnF2jUKV72ysAViLPPpujVp59b3iflL2fxK7ueLFRVAtu3XSfzNlhFYFFpylXOKQcSGVNF2mtFI_-yqF0r
w9yNof_3dvuN6fwN_dcfOL3zyqAQlibbe_u1
}

