sprite $AM_ABG [150x146/16z] {
xTSDpgCu48HXN5Ljxd_ZPNvRZhnPGZK4hNWlC8-cI_ZBOjI0jjmkueQijaPqt4-rTM_LetfKZ-fHFQf7zQWUrQDwL8_gKM5hlueNgRINXNwXQkrzrx_L119g
5wcsTgdM7j5Nt4tri_-Vwb4zgaVrg1vLu8wg7hobAeAtL4NW9Yf4ghRKRg1gYZwe8lWrLPfYKFakNyM8gIg4hwaGlnjLnhnyLLFyIlobacA8bwlI5C8V5HXZ
EEiNiTuVRuiJrOdpOcnROPkRCW5QjmAfobIjwWGXpeutH81RYHfZzQnwdmnByPhu4wQ8UQXLJUQEE91mggefZiLobMzALxrAuOKJL0WxjM9LKrJ4GbMQ_5Yc
OXIcLg4IeZWrNzMZFjvAbU6Mgb2xZSe_OvEjgdSnmbJLpmiHfgf-NarXgkhFs1XXgkfTZ31LzMT4nCjlps1yrJN-RG3yLi5Y-MTaPFgZ4X2NX7V7InLx_lQy
84rPBxic019NeKHiJP-zllEtPtt4hzf4bQmBahO6qynrtUU9P2f8OcoYEjSb4VzT6rGdkyGaxNQjfx94V5HBbUtoJTcegdSbwVF_hcwmgatfYbXFS15MouRe
rIx1RLshNIBCMlk9YAYRbspJrcz4sRneer9LTKRvfbHLkUIR_gWozuoiCQNAc5SzAbN-6MMRCgwPzPMGRygM9OzcdR74bAgbHS4PMO9ArHPMrwKgKwgst7cn
q9GgSrwgHANAd9SgJQaovyLAqwYQpsiNYwKcQ1bhn-R5IXIxbjVG3vnHTIP4OBYWyPLWbKcTkQinVJmlcgOytc0QmsTV2R5eK869wS1Neiw4w6WZofWNJnvK
jlyHKjdN0AycOrvYWGcJGLdpaaHxK9FZUVFI5ccOcdQRzZz2-XbB1sNFg-jtFFwyjELWc9-nXpBMV0tSUQrTGpIVbw8pwZKUU5xSqDUnqCHb3ie_OzSa7XYK
cmQM_fNLZA-1Ew-kQRIU5_yh4NELzVUAFwy-Lnc3Segt_raq1-NFQweolWPcUACoZcUdJrJQ_xpuPvohhEV53tsgCWVbrsOgUr1-VA-YCIYdnedAVLxgpyZn
ULc-5cOgPr3rysB1yr8_BnPy3UhdnUdFuM_FYmNFI_syec1GzVDYckxaib7_
}

