sprite $AP_11n_Instant [163x146/16z] {
xCw5aKG124J13xo1_2C-T_URggKZwECR4lAm5W1XNSn6Orzit-8MjxZ5BMunCyoB1OHtKQ3qBWuzliKjRd6BMznYk1UhgFX8iIwBzHz5WFf0CMYwYNye3Xe-
K4m1oBeuGZtknPxJB6vnYrlSObmMoxfObqMiYu14lbHKUXG7e5yijYeiYa8phnIb2lkYICTYwRvucxGgfjJdpTo9afjE4mFmfIKrVlyN_Wu6B6Ce3tJjEAkw
_aVY-cKaXjmxOg7jeSI9EX8b_1qYf5EY67-32ArfHEt2wTyJWnjc9PBQ1V-OE3qz93SYjS_mjkF_H9qI0QbF73z9Yah66J7bB39coiIlJJ99KkWHnMVaZ9wa
DJcpHpHIpfScEUUHE9bu8vo-HmoLY1A-H9me4ml8yKHAgXF564qCgKPqE8qa1bKdEXX6d1hGH9KJOuW6aYkHgeRJxnD3pz14QW2oI4pjYBaGQM8b64SKkU1e
OZ4nX6YZXUFQhXEblg_UziHRz_j44mVbZJFXrl5Eb4h4-Zin9F7wmnHIYLYVP50Y44eVRmzeujXWAqq08q2bnEXr_4sY5Ci82N0XajcP9AKl4yaLk17viUtG
5h8HnV50BK004G3m2JbH9qIE1X84mFX_i1uaJo-W2N8ud6XWEpqsOnE2qF5dVN5yYL0faeD7YC2QLGWm2E3Gzl5jl6Rm2156jYq-_mlVa8_7ENBi2CamQGcV
_qQIkxOV_ykiyJ6m8M2anPkGr89SYKjImyC6j0A03yx05azo9Rhj8V5qsl18InXFSLZeT-BKY4EHzBYvFhrmo1tOYGYiatmuypWVi_qROX_mDV4MK9BOT6CE
aawskIz6RdbR7-XWuKiYqN0Za7nDhfzD8h3hDR2QTk30UeGaviSRSW2m4JVa5b_N-wTxOJw193978Ca3qPzjuNer4iGhaZIGn6CsyhVQvZ6v-spN30Q105TW
0DW9snPd6pl8Aj14Jt9h5UiZX0rfe8cF-JVRPeTeP9lT8WnNRI1DF4TcLTWnUfBW9hIHF7n6-9kMdRPBG4VpuRDN8Tw_rxrBukNO-fEi2oNfY6HByvq21P_Y
RqoI7ubvrhQ9fq02n4xKkO3gGagPajlst9_44o01Rz6aSjly53MZUDPs-A9ncay0i2VLs-R7A1TaIim3yWmehTUcyFF3Nq7oSnPVBb0T9ta4BZW2R3_t62Rr
9badPZl3XKdk3_Bq14MYbRt-IdvzaXRs7vTSeTA-xSD50snB968XNc-xJfHIFadk9lb-qOWo4ZzRr4TcMKZDAp0tw6lRXukcuKWGQQ8dMNWdif-S6z1GQZuG
0UC4uFqdoc3ZpNSYhsHPOSfGRKYwOsZ3WM3kWVL9cjXlE_M4wlzPYl95G_XPLj8oPyf7vG8YhoFzN3yl89BQuKX0CckVoC85nCl9kPLiA7CcIHX7W1xXML1e
czVJW8PAr09ylGrd_7mE7rrareY823QReG90haY2IFvq4rScMG0YbkZj0iBhROZKTAwgJv9NWtWcPyatv2BSBfeF8wnUG7U03j8Na41jZqlYvqOcNMYx0cpX
d5hRRZqJXn7M9lb-ZfT7U8ncFou4g9nkuFhlH5TTES8MhCyrHBItNINJfqasebG1jc1EIOMEhxqJJLGDs1Ovfy1af-Fo1UJBySu87IGZbAfst7ydpf9JECBK
ylUEJEW2gfDCxN8Ng4HCb_gjJrBlkTCn4n4NWVL9IX-G_H5U1zOdcJh9jOuLdOxBcTZ_OQk1uplkjvqw3Jf05e3bjkyJaQe0wnVGV9Ue30k78lMnQdH6-9qW
FnmZ2XVDYE0kqIFyMYRU8SeTVnMPLuaqyDj1zeWUeOLVJlI9KWSuEXEEn4B7Wv4y40iNpU04pud8IiVZ9scYiWWSFqaKHlZbjb4TuVY4YTKHZWyQKOMElte1
_LsW9ma3_sY0tnN-5m
}

