sprite $AP_ABG_mount_wall [108x150/16z] {
xTY7ZkCu3CPnLadE-p_mAGbmcdocoqr4N_CVMBJTdHz8fXX3lubPrLwf2bDYCkgYzmp4j5Zq1IfmYU3JCw6BUdDyAQTNQQpN3ZTButVf6elsnjiOIDHqvhlA
t7IJKz2clAjCOezr-ej4p3gNk4ZaDfR9EXyZrixnncXybSQ0pTEKGqn-yyvIOTxJmbU9_YMCwHrtS_TDBE4YzVThxE3s5t4ucdrrCtvo5CNcIfYxV_icLjuO
ZTUOqbTnfCMOZ2r-evt3t8teUosucwmmFdCnVdPmDpw1kSinr1FPVRxLO3HrNUsLpiOxdWHNCtWnC5Y7NkTEx37-sOSMnX8FnsjCOR2Vzs8r-0zneaf1g__B
SB4Vj7hlt9oY4awsqZ_NF5wZxvJfdCR1pGIM-6cDpyjN5dmCd1zDZT6A7y7VL6-yiqJslXc3gvaU_OiF2PV-5FaaXeEizomVaaLpYvp3-7E9J9WD2Qn3RNKp
urrAMrLHiCvgoc3HRgKrHolMWhk9meliqAfgOCM970mcT6Wr0-iy1hDEi01Bjs9CAC_2LnvdMWoJP5hqNxNeNsVT5dEsXR-qoxV4Nqc-nVxEDDF21ox9jORK
qqoBXvHksP2cMKnXMeOqn_9duTrhAo8wp_8_MsdI_vdgjBdyPyPhowTP3YcZLMoEvK4ALfrYgNcO95YY7cUSEHUcaotlV-gc9bEjsdgrR6eyqUhjQyfJB1tM
tY9zXiLzWNLenUFA3AjZfJPOP885DmCjnwhjivfgOINPWaNcMgYbMgYbMbX9ivQrMKkEjIpkaPPXFRhb9T2Ih52h9S4Qju5SDCaApcOvLhZ8ccF5cgCbyomy
MmLBQQA5PmEBfrcuIBIKQOQ5McGfqKmBiPfeuT5gpRDmiEgjbQiiysgNMRtRYhgjsxgjsxgjsxgjsreUvKAhNMQrnwDSPYsFfLnbTUpHoWNMqAwodaTRQgRb
xKTBrqgUfKE2iqsoS8ce9LWm69mjmHeOd2t16XYUBSCYjbXBi7fIMdYs3AjhTJtQqbAiNh38BAldkHQUBTF2DDN2RDyIcXcNFOjfRb8sBQNfoPR5b93Lo19A
IShAKg0Ij0gtoadhqohwafYIywwPmlgoOXNkqRVz0G
}

