sprite $AP_ABG_mount_ceilling [150x136/16z] {
xTe7RkH838LXla2fxt_YdMuOJfG42LMjgjsTVyOHwJD9PyTjWRB5c2auFvh8nVpAdCJa_94nnV9AZi4fD-CCowkPCvXgnYG7DVwyc2VY3CkhcKEND_wyd9VI
50TLuu236hv6LDDubx8qS8sGRJ1B8rtEql0rqjalTpHDna8rZJykPKwdOhuXiv7r5fGjD8_AdKtFs832-aXHtKss6bHwF5QHlL7jgaUkwxfqDhNFQdtyQUrf
QbTzjdH0zLSzsjPezrQrk-otgPwk1bD_LTDvUIisgvhMwEtGfcfpUIT5iwgw6aqsUwZgkDfGYZwgwovtHbNLTPUxewhgydaTcH0TLEjoCAxh9aPqKRcmYgkQ
TcoCwAKghBB6QdgcdikhAkTwu5f-e_8ZgYolfwguwXghAIsLvNLM7QznaVo1-0vK-MZGNMKVZ2j9Kb-cUb1lKXslKQHsJOnub-hOjNog2ggOkglit659QbXU
gmhSFllq-ZnwgPXkKKLikXR_UMIg7DHTgWYlswgLvQ9kL4Kicwg7nwg2ovOg1wiYjCweYl2Kgi0oeog2ouog2A_pgJxFIxEfWavJ4wXg-7Ue_gfYHXLdL2ac
L2dcKuandueHSwZmfH9Y5bKiJrKnZLPnVImg1pLQ5J21YF6gslz7zLVrLyKfLPfIHSoe0cTGiQmGurNrZg31gcq3EQCgoDjLF75646vLrJkIeWRnLXLvRYua
RbJL8L1xVbnH8Iw5ih2wmwkkgb9Sohy8tZWYnQwBEAKIua9bFpIFM3KKML5THaL1sB75GiIX30ImenBZMaX67LQDulMl-YuCYhzKPJas8gvjiRPygeJhTuGi
2uCTqJekFLNdb_TxOvdbRU4E2rTSosELhJWLVoESYhEiWCwxB01nBlzMCHs7h3elHE-SBA_H9WlxbzaTLWt8BG1iHXp1UifK5wPDLiX2x0U-QA_G2cGcwlmS
6z5ct5IcuYGBiX6tv8rXmQdO6PTkSI7JiS4oXhgKoIXziZPTlEEo4fiindRG3GDZPcw_MeYTwBV3M4wh7bUDiaNSpWfb7Wu4Bva-FsoYBr8xB9Rhge6a9B6G
kh0Grrqtd3nsmHp9Okox44E2Cxr7TjdmRJapUUGIHcrHiHCAREIuwiI80UCwlY3gARE8MsqghXAepp_eboJY9jUf-y6jyuBBlAO8UheOqwKiYvmYlXOv8Kmv
9mpAP-PqCdx8H60scVELBV6P94w112dvsNj5_m
}

