sprite $AP_ABG_rogueAP [168x139/16z] {
pPk9Vkie3yND9h7h_TzsMkGIh8GwvSR-pVcMMRhaRvs342HtkqVAeW-vqAwIFRhjVoRh8xrKJM0kBv3MUdj36EbNrNXjNOtMHfrMKa3UZwg2z-644ye8awC7
Pup-aZ4EGwxqK75NSSOl_SffKwV8thtAY8PGBYPbpkqNTSUZ4uyZMFlZu2MWlzTJxw-UGPq_CXPgIkfkt-rEQT_jN9czL_ToCcQ5xNt1CkXwFWqNK_-jprK6
lJ6VPIbicd_iFj_Zukkf1eftSK8pVLkGRjQRU_AfrsF6mIwtv9DTjzkQaBu4D_ZEvGpRgZ8HrUivkPnrpVNkF5wVJxtoEl8vy_Nv157EjOBQottFQ-cKl-5g
JYsgiRZaozNvTFjoNNLUxO-gBywd9w8lUYXw3RD4dWxWOjzJM-sgKbQBsRHjnVkt49HQu-HQk0qMvvxGbX2o9--SoyrsAXrY34_kLY8ohI9nSGdbpRstaBHt
xesoM-ESiV8PUGsanOJPHcZVspfrZ36yuH4wX-6pdAPncezongOdtpidBd2wspXBQ_DXkcBFptBv5ixSrZl-mtgFjt2outPj6E4Ep-vVpCaLKNLfb-STazsu
cDDoBT9IG85_cFUZQpdDeoHvQKGEx3vUpCaHOror4a_7xfkhEIE7QoMWcX_Ei_kVvTIlMZMfXeiBNJvpLVsdET6ysf5mdtowbBRWKHzV1prOhOxBAF63cezp
eYIDpJR_mwaSXbI8DIR1LcegAQ1hj3pFbKPx0IU2afs9OETKWRgElLzL6XKKSoRav_aKfx8xPvDJOakgUmFDT1GEe-PHcNslD2dd6gT173YFvji7b2UXECH3
o6-ETjaFSMh0pjcbdn3SLaae3mEBKEMcotdv1AS2n2EdC5_lU4RH7-f9MX59rzSvbKKKd5skDvWczSm9GnEIKdnTNlKdE0rW4nZctFzPnBJbiZoRMqMV5P58
7Cv5JXbCnjGxP_jN8KMFEFIenFx1j9mll-RbzA8m9PoMx9jJRIza7mvh7UANWjOEVVCh-nvJvaJH9EK4bPzQgnCbTxLznKmudVVEp2XPeBNr8Q3L6h1GKmt8
ilinYSVcGKQCWADY7qH4YvqkB6-DiJYrl1lVP1p6NXAFBB3yWe95_auKpo2cBAJV-scC8SJmr8kam7x98RPorkPGmLsX6vYeIvP5Vh6V0bcQopoVdkAtWhHy
hjRITNlD-CIf2h7wEpKkRC5khxyudllzOqihxt4Q_4s-USolMPuuDvs9nhO85BT8xhWZ5Bt9UYhUcJWv9vmYc4A2oGq5zUDirDf1saaiDKuomxlqnQlnu36K
K-sywfHJEJnH_36cFDQyFru9QwE6QIvjSR1I6Irlf_eYYc9jpJajdYh_D4QWHnkjauim8ERaiadrwmaTY95tpl0xfuPtCFjgJTH9ywJjbSwP9-VYj5FsPTvV
OCQf7PwBsHpRbkc7TF8UfwNEIURrEqUWud6sSlmFKqw7Vy1aAL-9rOZh4wZdtJC-glMqIoPYLVvw1uK99xwZq34bAIivQMpd59dJM6XGxIsWWzhf0UrSzVb9
LJYGriE7b_BEAIC7YMQK7JIlS-vRXf0-ab9zV4STECk3iamfnxp8WVsFd16CSJwc5E11IWSLix4A0uQnFdfQInToJcYCRUMkyYJv1zz9yA2QaBfXyC3D3YlO
rjUK2iliQCNRpryu4mbLLA_TjtsN2RkFm6MfugTVhaVPnznmG5i2xHMHf5Nj0vBV0rVusyhBPnIKeiSPnBzoee-b4jMIKogTL1yFo6LebntbwP1KdpEJm8LS
QoaHvC0-vvpBUsmAdJJeyP0UerW6nqQLotYxO6AdD8T7atCHS9ztkA1EIapg6Dk8V1q791mIR7kGeldz96aCSsgBAmfvV255JQvC1YJTYjzjjxdl3dfwUS1o
-eTJ0ox93wGyarBqHEJLCsQxVInK-6tYF2ueAJ4NEQqXVDikEDT8szegLFOTgDr6m9SGVOYvKiFdgQKKIIaLF0uoMXjhZHQ-hv9Ier2UNAOYMasXw0WDNvPE
ARl4SEJC_hdnVv9_l7QeP3pfI1iIH7987iWZMVqDYK0f4BtnOUOOux6a2CBoHT9AJP080fd6QJrfHwxXMKtU4WRo-DQ7cMCKf1EjabfF8L2jtvncu7IQIYNC
vDm99Iko0bwWnkae1wf4AJtgwP5Y9ghaAnbn_pNdP7s-fAbn6ggH-lYMysDjHqEHgchrHFKEv-VD1mXrkAPNaNIWNAcs_vPCtb3GRR07iTHdd1UGWkip3xRX
pSP3FhqZfoYuTg7ZnLnmmlcvc3hRA5c1fqnUHw5nwfspyYri78vJPig98Hxa_vqoZEVZqWupd4mxSAPCH57jGsWHOzAplCCOFsS-k5ZxI-e-ATbX7UL4bR_1
FZvROE89QOm8_X_Dzp7bdAFdZMXukVAOB3Mcmo4ZmJ2bviC1eA1I5cAAQ8xx4S0_cT_P7Y2fduZ6cpjbNDlim6hnngqu5jNwTE1WBi2mR7uYgMX6Y7p-XoLw
tR2G41xNktT-CQQUkaHxKU7y7SluE02mN7vzqknS264ffdnh50B7ByEBmorECSEB2mRRVbC9-pd67pZNOvhwBOmsHdK2hFIGdvYUwENigRHMyiFV1ovOw57X
bRNGzt0_RpR0Z-9J9vKzSp0Z7eGBCQrFzogk42ivOtPhi_WSY_bfGzvQ-24j84FHsuKJ2nt-7DD0Hr2R7vJVyhIhf83mBUGmSmtjjo0__p7EAAvNGN3zkKT5
1XMPos1sGQ6PCjXTcCKRTtd0P6cChCKUPP5F6ECABcWUwZk-KF5s4EOHr0dC9YCg-AUj58o1lgYDfDo5KQAM25R8vKSRctn2Y6EwrAEiuSKI-msSDw_aCAIS
Ioavf-Z1FellGtdf-Ca6eJ36jHxLohNlZvunJsGdOZ-OBqxRhlPBFGgCOUFhptw-GCdg-TQR-73xDARlRwMj-JH0fPfhRf6IETlloEhaevbkrgFcCONEoGis
h58wV3ICWYSVTJN-hpsAs-HmS5Z3T01kcFJ4G7XEUjwZxBZf5Bj8YOvzxw2JUAxtACuZjxxg5YrtbcVy0JHlfu8_z2XdMA5I2NQfc0ZMckEuLNaW5LgFgQZV
OZ2jVGTglKU1NQNi0hPyNUeyfakKql9bolbMwb2GsqzOllsxpAzRQUZ6tnzCAJitdnkfko2OArBpSJ_qFZ_HjS6KKfCUrPies9k3-VvM6exxF2nOhhOBvAJv
uF4Wjx19NY459_CTsBU3wSPDychpFKv8B-X5YprgFjel1FDoy_tho_dpkUXgoQqKNscX5rrjVlWBfvFRp_LolnLqeHTT6DDvGHU2UQ6Kdt4kzAABO_ekfmZc
xO89vuBbLyTqmYaiDyBo-wNnIKl1l5u6XTQ2URsK4vnBmRoVT2sOzvk_OFcDifrpRPEyttmEveBbDtVJjLvqVqmNBBzV3d6j5zqVqyk2-Hy
}

