sprite $AP_ABG_hybrid_AM [106x150/16z] {
xPdfOgiy34GPQKRk-x_mjwJKmRV8SOZktldLrGSqzE32jX2txSV4AFmWajgVIVeYVP6-I5yaEtSswqcYdtzPNaoAE5snCVYJI5-aBrBWHv6QYEzFiXj9ykzC
0hMJ9FkE9BXq9uduNYIJ93P6K3kh18G83XnA4WTIJLrEwS3jfq6AdLHI5wKs57H7KSSGTIJJF2mYWNeOBo31jHBQgoJNQeXNIAPduY-Gz6IyabG_Ge-4LCmo
AI7LZX3K2wHrGS6bdKHT3DO6Tmjlf1prig2WWxD5NOvZcyVVuexYTOwP6HwGtbheMaX_3sqFvgHBBBhRMQQa6-j9ZAL1JjfHKS2PiYnQPrLmyX5wYtZhh1AE
6T9hhtMMvbdZ82CTMIqAG2bfcULBd3bfQOJqHGwGN1ABB9Ah86pdKMVDHaYIliO1Sf-_PQnr4ewPRI8UZP1p4f2GrkgAb3G7cMspO5uN9oYCSGsaQLrnmaf9
66DoR0zZULtif3c7g_i_djT5Tj8KH1hMjtudLpnx7XIKSF8Hzhfsqd1I-U0yuUInRqROr57-Ua5vNSCruGK5vOAIr5cU5EGJpleLF-xm2WhAwXgbv4K5ZG7R
9zKIOpmfw5fTaP0ozLolgoMaFhYYi9sJZBIjDk10IjHJpc9IK3sBIK65yKvAr5FDOb9G_GYPgASw44yvCB_5KCZQni0PRKZGj_8ustc2ACGO-x8q01i0C-hZ
5Bq8vkyBwcmzu_vD573ULxAyJeyAbiLA5SQNMJUERmkviVobmVdwNRkrmDMxLTEs7fiT64MCxV9ZseZMmigExUE90BODCASaMJ_0s9wDfIWmUudHMkCLWqqc
RhpJ3XfhpRPBuQnR09yV0IKY9wM8YFoUKh3vTCLdlLgzopib94dHFo-5GUqM4HX66Uzih-KGfyNjtopQs4x_Xk6p7rWFOi7ItcRYCYB_JJ-k4ROeOqj5vDan
I7Q_Qt2zJC_VspXEEM871Pwvnt3oBeg68sRVl7Q9wJddnVozb-YtaDsnGr_BWIF_dZ5xjrGVM3yPjpKCW3f-FeBM8rO0yttT65avn_HXShgPcVUzCcivCMps
b_KAMrhTHfaJsRdcBArqwH8EDq7EFHJ85f4l_0E_7zV33IOYrQjrvKpamViMpbQSDpba8kKSJrfQkcIOVYjn3uoTKnNZEynm59Ewp8jP9w5ltoFc737sVRrf
vkwsOF8-OTA-gz3thUHtb_cPoyDon_Xp1jUmmMpt8c6A6OiIdtluTjmx-jb_qKt8KB9542MXAqcMRYdJWMGJpELeawS5oaYRAMNbFuKj3-RZdxEi6xX4Gpvr
kQnShqC0P-SK1TwDwWO0Pav-9_kPQqYAgPSvtL1IpTLLw9yVIiJat7cnPaXA79iiY3Kvv4v1VxxClbUE_0q2BhpXyBlY7DziNv4hqvwTdFfYdvjnMx3c-WbT
2xZ-oxxeYhcaiSPn5Bp6CinFlKRctlMQ6R5p2bXTFpX2kfmSzIwNk4SVyMh9uapcJ30LE7CdINSpAvdPlm
}

