sprite $AP_ABG_Home_Router [164x111/16z] {
pTk7hkCw40DG3Sd9___nQt50FCH2DEkH4w9ittj0MhfzW42Cdmv4W6DlufdnXv58C7RX04eEFLhPo2q-wZnLfYHYGv6GSvM950cYkK9z3ADO9DdUOQUI4j5P
P52hGMrijixSgVIfKNIVvSx1gROYGP8xbF4S-tgHGThOEBZ79bjAv9ugUHJP8BInMHaf4H0kp-oe7CI7iQyL6I1vNHahOqV7p3Os3kwnsJ6peyR1FNRqp4mR
--uXf4HGx9dPoCx1dsDJFJFRsAdKSMhGC7E34Z4T6rARqCQsnpABfoR8hKOnfbSa6qhiKix6pcWLKbU2oHN9Bg6LROFpk2BLyo0wwgioZbEJM2mHH_OQXRCh
KYj2E9-OQaJouwcny2qRZJePM_pq80At8daoTiR2WrX0wchYP6nEX2RUYuGXaRDJ0z915QdUiOyYCRyHYMbkEJLuNP5wczd1FFUSxFTJ0qw8DnldfoR8tp9w
R6LOk6x4HgDpZFqi4WNYtY8DzDXC1NWMVBz7Nv6YyzqUVJeyjWXQ-FqUKnZlOrFYBBSRCudnDlP_-RxHnFTtQ_xSo5QZYVyt1dSOUP68oUUdECkDFMQAiD4b
5enxQyn74i-OA2qOxteRDvyps-WMdIyQFVCH4nUDt4cqaEz6Qi6u-_r2FuWyCK858qj4ralagP6wWYHxZ1RgtHYg6Sbb8Mipw_X73nAlXASk8EtanzJkcsSY
c3QEch6Uyioa414_QFJCf68SHXDjx4UMxfiZ6M4ZuWUCdbal8o92DD5NpmvaGKZfSVmZHa0qyMdCFSRIp0WSFti0fDzoj747idBVC2AEdol5jw_musDBaONx
XiA849rNYJO-r8zSlMzyAUf4QECEvDA3AFgWs8WOPyRskHTFywjBsKWCnyP-v9AG23nUXpbWuSJOY_muiylJWPHddlSuKJOIBRGHecFXn9WJPJCnnOdHCy-D
CsLhYI8dHiHOCcPUHdwUMO_qcpXBGXjRb0ipHnm_IGPaOS5O6hmk5C9lFiWFOi5ugSgLqwmOX_7pp0viF5CwLuJoszaZ8XU5JjfOKTRl6xylOE9O2y-CMNZD
e_NxXea8o2Kk9jB63rKw4znaPaUAg0cDJ6UchCSpEmzvvafWOq5P4Zgoi1HczY4zCsT1Z7gGpSfqYU-ni9J8LkLSw9cRgdI-ExEZdYhpqJ-p4mtABCpSCdXT
cG-fC7EpKf-LMPkvV_33C67w3ml2TkK1URxUbEFVrNyfF8ZjWyiYlpNdd-kLsOFO7vuRdUaV56Pk7roBkM5c1nr6nDWRNZR6s9vGtLYOkLjPDsBS5kYFZ8Xn
PrWtCiRD2HMD65y8L36EBmNBn1XVIr0BiV1NbSJuUWA5xxhx9fCw2Gty7IXVE08xVNy3
}

