sprite $AP_ABG_with_waves [150x135/16z] {
xTU9pY8h50HWpbAqx__44_ARgQ17f56WarZtpfhj2rK3cdeZgcPUOgQIzaVCKL8y_oCN45tXU4Zw4rt5GvAa2qNzSgHa05pJvKmc5pIz7PqiLMlR9ABc3i1B
p9ROn1kc0WBSLDQNfwz8NaG1QDz15PBfhfNBgqV7ILgDij3a6wy91omskQLDaNZcmkeseQItL4P4j4GMeimR9b5pzoBwomILHwX6UKKq_SEe1IXnM8CaAru-
2zgB3qf9cXl0dr1mYQzJjhgyFuEd8BRm6GIi2wLBJ5nL3qgMTHSR12vHUSrlrMfQyhLxow71NtGVbEYKx_V-i7M3FQDCNf5K9ZNuKabKl4WpdRVsXpzQ7qhd
VfE0n4T5r3eJ8rQfFDNnw9gWQLgqGjZZbQ31GMbQ6xEt_Qd9wY_LuZNIvRczbuUkAZI9Vf5bzQgi5wLQ-x_yyK8gbJOQPgIOwZYofqbvB50jCf6qHcNoq9z4
tQMqI1LFrXu0X2vL9GcFhdrGLAs91QWhgOZQhz9WTHjLySnKTglYexkWIYwfIl9J3UMdQaVQjoZsgDnTMYhPeieu9CMHx9xrSgh3y_5J_LJF-Qb-AiWLLHbs
BPN-gG2zaCfmLm6k5r4fG1NWSW6LEceLOBjLuYZneWAZMrLsB-rFvMGjgr7XsPy6TLV1aTs1vIw78p-KHrO9wjWYLJveChoDwsALeIik2rNgOBQwg1B7cUWA
bHWwapFdDLcbtQRoWpLELVaf4s4sLOKpzMMmHzVjgfo3uvhYqanLnobb_kP_JBvjSb3LDoZ-cFG8YG6nAZRb3FvcrYDa05Ld1ZNnibUWn7FxPY0bDdrrNkAe
LDvr5UIvZv3nv1q5vksHrnLYqd4TcQgI6CMhWBzfnDtTFbBTw1eV5340_1xzH7Mx7HstPkQT473Yc8ohIZAOiuFoHao6LIL7Xoio-RlOgAhbolMTSCuqFgzy
HuNpgflhhkxp6ezyq9N1FBztEJ1DOXqtkbZZvuDYJFMygb226ZC_7eoPY1fJ5TSHkEwjtO731pMikiKrihawfqpZgf8Sk3Zo4PIPVggAvqNJ04frM9MChiOj
mPmtsO0g2KY9vbNdl2bdgiv4CYdvZQjpK4JTm0Q_LECHg_eFoeptrK3yrZMlSoOWMFlml5xNs65YtEuwJ-EHrxS4qutYkFWDSTgyEar4ELZWT-V56ljCZ5Mc
6VDgcomq6L6VHL_Dw_H1mRjDu_FAdQQHGOq_GXauCoWRC0qyGZcSkqqjhrqZ_nbsbLTCa-AL2_-pTb3jMm9WtWqgGCsPru4g2sw3hdbbL5bNNXpSMQZJU5wM
H11rk79GSVHuxd3reE9vDLGSrF8WK6qhZn4FL2nlMoHKEKsRebG5WzeNeoeUrDvvHOFQNsDKtluQQRfCn3ceAqKqdSW_
}

