sprite $Aruba_Controller [150x133/16z] {
pDQ7akCm38FX3NwclFyBN_5aZA56YBtDCQ_txmX8seyV6_5nkj7rUYsTotJXkanTJcLQX_E4rqPdCdbA9mglRlxkUr4O8gvtkpX3U0L0S-bDuPKt8qgIgDlT
KhstKABggQgwlx5UeycgUbkzT6tXTLMz9yOBtJIe5jSjk8ugr4HrV8oo2QgIghjqSA6ogjVhSbnuKULw_Ruhc88grEk0GYNLKVMwf4AX9qV-HiHw7LCei_or
bEl5BnSAQAprAwb-iLxvDW0znwnb0WhgPbVffpzUMH40Q-lLXWPQVfrqIto_K3P1zOceMXQ7-CaOiGcRQXamWXcArLE87xibD0kFCWF0FnvHMdRbwW7zblXc
eSgMQOfcOH2Y_J-0KA_ltL183LS5I3X4gfYiYH-w9LIjK0qboVjH2t5TKzliCxwfIz-v3SgLTKnUWdEJx6yxXMyyGY4yrzUzd_wJqfWrDPbMhoy_B_OCQs1u
PEQ7LNpl4PB30weDL9LZdAGOTpbTLwpNTg76GUD6B0xNHvXGhyr2mOpbYlamEiH9kghP46FC7soE5yqifb3fCRsqSoLNVbxyT-SH5lP1ARvE3p76GY5jgY2W
nfSn_pgL7w5Ug7YUK_lJEBxCoZ7svoMWub0x9xEwIw5GkwPsZBPdNY-kwtXH1weSoiqIbXjsLTRRTbLNJt5xFEw11NbsTkxrp55LY-gHraN5sP3jK4VJKvLT
vB_njLjiea9uLYskuPVOSOl6tuFOMXXfKLOjCraNEJuCOuugL9b6D5aLOkJLoO8fdlKdfCftFy5aLN3byPRCSYvDYqYqNgYewlNQF7ohIsR1a92qjf-CgWgg
dUjgXu_6cgM8M5KYce9gsvMwCtuuCwfjat9uMRNj0Y0bjFuA37QaQgfiogfSBq0IZ6qkiJA7qs0K8eGNLBlNPSvOPFnYCtPF_cFHb5NPrUD3gl7GIsRLv9mI
dvUi2Z5w75-PrJfkLaYHiAYzgl08nSV4A7b5OueaKrRjYz4iD5PjP36acCBBglqkWm9gSfz6Knwu1qwkrqlKtsBDHCUH78QXqn59xV__y5ubX8ZiP4hh1M8S
Ctq_c3QVgjER46yUAA_u-VL3SurRehysiOOOc381FxyU4N2AGov3NKdjHjXHUFMvrrrYJhawLBLelJbcygAIyG2923IkaOGYed3QvHk5vq--g4W4b2V7orHj
ZPaGO56Hmj7nCjL9U2GZJ4N9nslG4ftgb0bHL2ogThm64dfBnJdJHGKWLLGa3bgYKKqtAeMeXLI0IbrKnJLk2LCTXAUeHTMvKbvKTGLoUBnCTH1UKK6CgDEk
zCyH0SrQebFDso2AIjS_psPu_foS7ozJZS8pKr4n5HSLnLUk9ESICXNd3LLK5A4o0_pDCtLHJINagi5KUOXQ4YEWYX4EJqfTLCKrFLvpvSbGY8kAgUSTh2fL
AkdhcACOv-6Xg5Xj1K6qSLobyi-H04wuvifJjO4BzDM3hbBfcUZWUCtReAYWH7ZBoeCEB_Lw6wM1XCPjK5GKX6AYFTZ3CvSqaD14UGmdXWZ1CQuUT7PCEL74
hVOQA0yHrij5zHAZFTYhL3AZHzLFItSF50j0gdz1OVNW6bxwVPRZxx3kCKLHUSkKZ92PcWSTNlPtuiRnkjK6HKMfnHWHaig3GIxXfRA_yuw4xWwR14GKW0J7
21MLNnzSm_F_iabeJ2LPULSHoZ4s3pv-_E8yAKa5y4cESwe-RA8YWnoZhd-AoQyxDmzActS2mSm1bG-KV8mgCcdrO34L5pPLEfNZZM7JknCfL69qWU9d-Ni6
QHEUT7jKlJDiqiyCYmShlCPbAujlvPZl9VJxOHE4Oxoe90Xx9iVOmvEqND5t8_HMUN1YZ2fGQVLWF3hEofMRy9I-ejlsMg1O9yOaHCNOFTWtQZbUbPCz-6vK
xUMrKnvVBna9KUYtiJEjAuggOCmbRUIO6oeVgABobZ6vUf2FUt_NjtemjRcYBSQkbwA2qZ6YUx32kyF5tCXnlQAjx5iR55Nlol9WQC1KAy1Qzk2RKTLSdvK7
EKP5X6PCFbxTWvBMKTKjyGmleqyfZj4Ud3FjvUX0s-znBZaM5AmykK0T8-kTXXgj1z_9CVllSGJe3olFU-82RJ46pJJdakwCgaI4zN8fRpTi9dSNRnwZj8Qt
7LKHpvkdW9u2b9e7hPS3he-ZAYLPZgubHO2R68d3ZNACfafz6bMZFvW7kl88CvskvJRkvHZzmLoEyLcWvqoECUwCgajN8jXY90v9keHM3rgErp_H7ipjmO7o
niTBk-SCUUUYFPZNv29en3IFqGYxHDsLQXwSCysv-gXQomNg6EkTiuQQnzWzM5ocekWO1yexvqgwuStr-lkLy5odmutwhwFgymvgVVIBmJwTS67nuFCEBXuS
XdTUzgiSkmVFcSv7rVOw0y_3EnzL-wCVUD061rpuw47WSACEHzNYiWTzyxwpOl7WTvaSO_UWzV9DBdOFzZRusl4obSFx-WfJVJsytbuHyUXGtuznSw2-l-9_
PFeB
}

