sprite $Branch_Controller [161x176/16z] {
xCxLeKC124J12vo5_Yj-xgu97piLpF5BKH37OWMmETYWMHsKsi6lSD111nrqC39pSp00Sd4m1QhDmK63Wr_We8CEEkXWPAuE9b1V3CPDC4yR151yBLY85gSD
IlHyCIW0Uc-m6pIpEgZU47JGGGSTTB2kWzeR31gDykrWd3-Ot7exg8gp1qUWqJj1AHS4rHy4HIuFIXNRWgLv6fHgLJ2bbq4frmG3lHKK_r-y9CvE51mvKY20
IaI0_Fy_l8UoAfQQnanIAtdmsVSpGIRbrXOGxWLGe_YdWUPU0aNyiq2ZyZo0z6lH_XWmyvm2qdyfVh69qGAH40aeuVTpjdS7MGF3_GBqDp0oyEjN3bSzI-3r
EF1TJlc-F8fAcFINjS0ih7raV6KKjLvxe8erps7mLsWKlm-4W7s91-0a_WD0Omo0D11cPcIyD8hV0MhjxWC9a2UG38tYju1Fk0-0C303gL7y4j3S1q0kNWQI
yIRQLu167m354r145_6Jm2TSfKtI3ryDLCwV1IOUJo3P3LyDpCGF0et9rmELRWtyy2X6b4jt0Pramsk0kdBSlWEaqyDh7yJhWCgPpuy3dQf--7gWYFWuKCGk
NS6qwlGc-R4hvra2-wkb42vWuRkz_RJNNWCWJX-WVxM5qjyC7nn5kEy3jNQNGnHBLVhixYWQVG2aGP6gVOMGkK2IXkaewg5g7qY81-50obpxRFqTmr7Ksjq6
GWzz6i8KA0eVGD5Wm7116tq0X1n8EhoB4igRccUMZ_f9dF2S1v3iXo_x5BCAsGSJa383sBqLdvb22iXc-EJBF03Nb47WF1GmDG_OlnKrVF8nMg3EAt_ah9YJ
tw1SOPTR2PlRprWy5J32IVPFBVgnue6vbYqVZHmlTXUqdf4bL3Ky0TBKvvs2vhy2LEqiwB_--ZjYltOr-b3SEMSsSw1UzmjQmFyGVQDaKE5wyzR7sIIiykrp
5b1DxFTQKJe5mWX12HEne3L40KNiUG3PA7CVSuhvEb_5gg1HvBC0TiJL3nJVkLfZp37_E1fr3zL-FOXbe2gwuOCrGB9O5Qa0vGl-BJ0JaO5j4obU0hPzP55D
lW9gBa940HEnuO4RLNzMdM-zlJMA9k25c7t0r4SPfgKUvr4KC5SKmzVL9d_ohKI4W4NErFMrLUnh_hsMmiIgYFnJ7TIcnLEeSXIlu_lbqbKX7yqMiAgO406q
HzIsURZm1DpC-RVPeTlOVGG_qpK1juaxzqJ5W4dP0O4BhmJse_ZxV548OUdPjjt5ETqze5PBSmV30EKZZkmmFMzrgv0LJy2jdFiIv2BKN2e0MADKkWrmICGg
ZUbYrJ6BgKFJy0HyoR4nYZNmPxnvMa5SkwkqJS8YNG4V475p54jc1L1RSyoWMcpMyGHyCkGOv2mN1Bb4M9mfZG1EPfEkW4QIhrj4dL4KXo3VIc0HCs5eU0Bo
NI76V1HHNIFvOeTTOvQpJLT0TpA2CHv5vVkcgNbYI9ZJllQnvmdeuIJ7ezZTmIWUmdJUvIpJhO6h9_Ch1wYsc7mImigOnMk0le2-sds3Q93jfw_wNOCQhtHR
O8HxEfxpKIotHYLKp1SUhA-dHqJuAZLnD8h5SqabJ6_lfQiPpA-ZC-96pgh-bIP0CNkHRdT8rCCOT54vLm6pUwsEucq2NKsCk3kAzQkT1wBYOOltUBXx8eOE
zDq5ZNSTqFFjvg6gBT8UoxHoNi3RLquk0Na_NOQxW-S4ngfydaSvzy0v3syIGNTNkjVpF1p55ZXFTo60TOfVuMSVbVXy57lWd0S4SAowI3ATv_4eDi1XkkuE
l85QTKbuFSy-prd0-ppY03ufMHB6-SOuPo-0itGZJXuG7ey7T3IEVuduPK5xp1QqWFU6B-BqCTQlgX7XYQY8ZueOZgA0DuVFUVOFmF6AiLQTqesGUZwA0evu
vzbTG0_Y3Ln4zItEn4MCMziF06vTBGleuS027cKHIZSy4qEJDHl5EUymEHdd6tpyh_1IpwuBskyjwD7mHOJEheS3z7LAnCkZg3FoypmFjfzuU-qBbuzOm7X1
4MiKhuzVnx-9FHZ5wV1n0Hd4CR_1451bhfGZ_DV49wFe6EqrPPhxA62g9ug76oK-6CMOxRMLQGG0GJCm4vakmslY_V-Upe4UYwTCZvpFFWRZKPLvTPvNuYB-
_q2wgsNvx7fGVRH7NPRlGZsIwVuWFVmr1DRfNZEbGxiO7k8L1GtWIvTXNCzpJuozuOjbaJDSgmwFjfxCbs5zdgCXnjvUYvmf8evLn-2pmMaKVwIhn3MASw1u
2yXO_HFKYJHyFV4LIbU9wpmxkvoZsslkKC_yo9cXsOiDdd9EvxW-pxuDrF3biykLC_K-3TycqVDrNP_ds0KgtMkc2AYf37y-PcLUdEUaPZsAqGtVlvin3-I8
OX26RWAIxt_YT0sVQFlw5z8pJMCBz0oZvTgWifXyJ9wiw71JFo-a7o_6hkvqn7869dIxprJIu4RzR05zGM2mzIwOZEKv9f9vUhhUeDQWFx5yvBZ01CcitjMC
1jKRmypti1M7zxD-Tn2Z4ptZFwjKFxlvdhSYm8varSyeYNJpCJghWAYeEyseR4FHdbZDYdJcOtHMmT__NZAVWrZrCy_lZxl0RAkMb14bb9fyyoHQFzk-QPJ0
lch9OXNf96I-QHNqnyhm_J7_RfSZmra5bcipAnTmWqlxOsgNWJHMKJyRL4sseWxHzyV8H5krD5R9eCNkT8cbS5pODodNa9rLrCz6z9ChwDl41jorQWaGQBb6
cM_LohPDTE3McR5OHRr1CzzALlJR7O9mQKccM4NzdCgr3IGMt1YIEQlGHii65VHj8eS45XyCH71BUVuc83jmTrPHr9dvjh6Yz_DW4i7-zDZGV3uLmHxGIrQf
SppjLU7R1x6Az67i9y-Vfn981j9YToU9xC0jyo55zBjNj83M34HQxEvNkTW-K5bikRQl5MbHP_9sjo8N0cctkt_58kgE8yz1x5YtwrQ4YFwWzJx9V9y
}

