sprite $Building_office [149x225/16z] {
pDU9TlGg30FWOCacx__2TmbpCc9AN8OkgVzzxNT05B7zn1HOsVxM5Bgxe_mb4hpDts0T1dCPbfj5vYm58hgVPOow1un-Fqj9_ysOvNRBQMkankA8XN8JATX-
h3Upb0Gpkv-bf0exHbZmMp9Vw2VXEJdBRY3Tmb9IA6dCSc7zUBWAl8Mfkb1kO2MasrWvAMS1N0ZNCkbsbf9sXqqDOpzcchLE2Y5DigeRc8HhcTHCGffdLQVP
jxAaKKPDI0cBi3O9QudKPiKa_-ZRM4QN8TP8EOksG5fbmJc2hhBq4PUm5aWI-BNURE73uGo95oGAQYLS5h7A8Z4YWO9QOfb7hB7ek5WcGIMiD50H6Mk51EGe
ujECHx3mJHQS2GavYaHwhJnGMp6_Pk5DKeuYIIGaGHN3B0iahaY4MOhYCSX8YafLZhamcQKeKb03agAydAYSbPD8AmVAEKPHK2d93mgjeHmPAoS11meU7A98
GUMaXeeWq3QI2IlDTqCnU4n2-e0IKeyAPqCb1p79zmC5zuGqHfaF9cHQv2ci78KptmSg9ocg9-KiFr2WH3v3GUCDi95I4o0eQKqPo-s1EdulHq7YRN2V2HC4
rPDo5XfgmmSM1gI6cimt12MaALP35Js8Yb9IGqsIp4wKaAPP3MNeMHXVANBaCfFP4rNeqnCNaUzHGFz1PiBK7mT4kA-m8AW8GNLN2fqp9E05jTSrbgEX_CmM
FbufFaVwYDhNMGVgR5j8hfGiu6FKEkkCl4Sq0c3zbSASzA38TZTKOxdCMkIx3p91qdZhTZTKcrXZUH6KR49EKfHkjw3Qr4KMhKVDvrjHSES0jHujGb0UdBnJ
5ELEAYfOlyvwe8oJ97j1jH7KLbnMozTO1ohTkVpCjS4JjHN4_iN47oZcfF6P2p41WYh6-jN4pvc07kLAUaKPccgTnOKpnz0z7Q5gV8cLaV8prqWNg8BwXSJF
vBj73N8cgEs1sWhhSk9zeiO9gWjJYjgA-MhYtpfpZBowL1H1hIS-3rE7WlkdrINGeNnFM6ka7gMaFcVi-XGw55nPNoVrAB_A6UErJodADejTM0kcR2t6EOFx
XvPG6weqr5OMeYMaP2t6EREBwb9DKSMOi59IlXRZCnUaecfzRfCf2dotR34xSyPGqcVLXKyMpKnG4Shwqfc3UrfTNb5Qg8BdIXbttr2LjNxcakT2N5GNALGr
Gb5RyIHQqpKkUIvarKLZ3KKrSCxAujtd-_hCmV8-5IY2CaiIF_zqofyBkAekkeTG56gj7MljwOIbwYAnhWv5XVckhFaQb-HikhfGM2weijaeMioVJdFFXH6g
AChWJrQ7AWqihEapbpyNHgYziWZAkkUMRTiJPUOTQ_Rfb3yNHgXssle-9Oj5QoW1AsfbBToJYYmNSWqgoegoEbHb5TJYMkGLMJy9TDL5OnrKb6siWbfPYt55
3XzM5qKLK_2kgEqHhRgm5kbrFKIv2UhuoJc2Ei7rtRLmJokoeW9TeUggI-rldXDrWEjRQs6YlQp8MbqeB2ZAJM-USwMAeDvVYxmYdwXYUjhwwW85PwXyBIOh
igAwM5T5zM1FKEbQJ5NalBgm24h1Uxr2EPQV2tbrSOcreXHSlO5x5EFwkQ2abUhInrfHLKFtWdgzvlubrKniM8j189Wyhluh_hSbZ_GX6xk35JcO7Vnf5cks
hgeWgosMxvI0Sh67UaAQXGrruQCAyYqMq0Lpz1LgcCNqFSiHNVv-IpfqYTU6BWXSAnHmYhDGwaAhWieVeWixyyPJR867TS53ksAbKmLXyv2d2g66MHmXCbLG
EbGGWCg0BbO89Sr2H-HP1G6em5EBrUlxMOI2o4GNwrHG0LtMvYbb5dejfGhQVkcj2Yf_xw4UonLAdeLzGcIY2oieq0MRvpDFHLuXCj45G0KLnCqpeukTrOKU
NQ8wTC4SXr2dTK545weW1Xv23RDGZ7g3BW213bti1NGHPY4YSXDgColb3qB1rZBKN9q6H1PvYXMKw09RYr2MrtLX34MWeWgYhLsXpke26Un_eHxmrEET2gAj
NQ4EwiAxCUfGGV6eAeY6wl2wO1aAkfIJfppHcIKLf5yNOZ3gH1Ug86uUg21BX6fcCIAo_W27AWX05LH1HXMaNnSuGEsAXL1m-aINjIhh-xeGChe011eLL0Zr
LtxMmIpaAnP10EY2pJEWYp0BpoyVuA22FZkwRF-OWmgwh0lD5Gj0HHM42Zg44cUXFy3X5mWynS0veCkzKPzvAfuj5B_nJQZ8SwC-emj0O8Lg0XDTnbbSNh5G
GH6AjXQXJgyBChgmWeAdQ6ktK7vV5-PGTFf45zhQ0BfS6tM6MXMqKK5le0ispumkvqPzgQ2W2kBcqT7btgZpYXK6TE7c0ReaGYcpE7-0Km6U8b01NTw9K5_D
mWIZFg0BdNu1NIptKFP5NSW92xTGD2j0bsolM5xj5Mki2pgwxDMfLK6XgQ28iPREHfqFcdFd4wWWR9wHf_IwC5la5OeLrA62wFGdT9bdeHfrFcZkLT0ELFCL
wzwewoh89nL4ZBitwWn5iwAg8Fanadx5OYX8EweWs5g4EhukgEW2-KaLHCkuX-AOZepw78f0HHL4Mxj2BOoxD-f45qCec1M4mkR90LqEZJfLK5h7KsNl-Og5
MTmRTQYWCAeWEFs3AzRFuku4wLKOXW4mn4jo_mk_VK7yTIeYcFe47l0KHtnCXKIT0iqzJr5GzF4emAdVOk5O-w6flmsl0PoOh8KKQ8xoBPRbq02Elm4ucAoK
gql3ACZxPO3Zbm3E7ZLeXYSFh2wF0voM9MXsQ7WU1RcQgA-0vkxsEC3XGJCH1J4OYLYHfw1vGz0C4ry072rHRmHeZZDenhGMcxAruy8De1a4DWjmQdJYLm1E
bA0PO7X3W2CbwWnepb62PcZu7S1n2U2aqL5GT3OAiWmDuFGpQ4vaPKKKz3J0wObH41n1eIbmSDfnmIk0KqL1cEbZ5EHzt0zmB9s9WY3JHz2SXwRiVe2ZWsR-
MX1pLe9cUmMQUpRcBPRV1t3G740K10stULFuCo037Cpq4w8Wfq5pX9Ye2w1P0JW-JP5l0yt2SO43ECc0PaVGB7lzEWfYG3CqZ037rKIT1iq1KH0sV6ZAT813
VDjUW6OCFvctM0h0wJu5pJi3cczDr2t_PFebQ5w8WhH4lGRDy1DFH47yjV09m0cVWsPaPJFGp1yNvaUn27yR1U5O8sYEFjO0JinMP1aqvu3LXRuMrBNT43H7
3PgDYe8iD83ZthPj-mAQgs_REm6Qcvge--y_ptaBcYt1mUa0fruBtVPjEpHrNAZwAGfo0ZGBnmLi2PjgBe7cY3M00yFqjt2Vga2pzqaKDCT8nWASxNzLe3dj
39gXuLi03jovOvMWkQUHeDdJruuBs5BTrBPx2PhRIz2yUbp0OS9w0Pg31yrG2uaw31CqDRelW6OLuE2TmteDcgDpe7dXxO8PjbGtDKOYQ0PMXb6Gvn003WvJ
KH2HGnG4cNu1cWM0WorXxK5yspxojBf47mi0vyKpfMmhAT1CHa51V1S2BHM5MRJqRJjtNF2sCMNZshVjJG4uyvPmj0hGZDVHbW2E4yDKZ1O3cYEl0npBoJ3n
epLYlmQQBQZZWhUL_xc1XOe7pGujrKUdRQamquTzok79GmCSSfZudmS4pUUqbW4uq99ILaP1i5050N1WcBJQlOg2CAsT0npFSfZKqUe9txRJRx68nvmqMb60
PWRWO4jwsQX0Syl10fnwcFJHGj3yDwsj00uxJFAlLl5jUucHwZkdLykBtxOl39CsMlvsd_8aXqaVBHeq1pzCUbiKQ7RYwFJ0QDLHa33VIjaCD0kFENMqoc_R
XSVSdVSmZb4GjO0_tnQ2PhqbVRHgqDosJvMNKT3smJfcst3dFbljAsY6bZvx3piCq-VhiBf8mtJ_Q7LzcEuVhQwtT7yzDapV0G
}

