sprite $Campus_AP [150x147/16z] {
xTSBZgn028LXWNEesV-AxsLUYOCP7S5ga_Ylu4j1i7if9AQwt2u38BTJEK2xdMg0ur4Twb4zgaVrgEI6AZMOt4u507exbGVWTghng8xrg1xLetfKegQ7L39J
PG3iYCeS790vAWBa4HNUqpag9ySXrGZ_iFkfw8_gKUttg1xLev9GuMug2m1qIuNNgHoHRQaITfvgU02sLIJaZYhIRgEoRrMajr0fkL8HydALW6jLPAzLYP59
bLoJLKPkgY9zaKh1bOhh82zGoRS9-5G1N6NJLSQla5INZb7VLRgbMaqAy7SLGdNv6F6URQbypOg8h8hGFa20ZbqLyHKtirxLEs1V5Qr8ARrO9KbrACY5AW7F
gKXSfZBoj8hGIrH69jLSLrO9MLMH9gqg0Ukgo1fLng_meI9uCcYJIlaTlbM9DUjAU7eMr5MHrLNZvma7tG6malQglcCjQAEAJAZ9woKZgtAJryjOLVMlbu95
LVzw2SYYgd-CHXPL_MDKigZg7wE2dw7m8Uwz4eBqoNE0rsSx2rLJzQ-NSeK2yuTu_XX97l_lsHy0Mt8x_pslDaMcMVNsjkNYD5HaabN_NPogY4X4oVMjYdmU
Q3lJh4fZd2dAhb1Twi8VCacgS4qcvIofsfyB9p9DgkIQPCfZn0XC-nXHI6MX-q-NppNbJFnj95TnZ2XcAXuA1glBLJPfgDuHdbolCxshehOn5ascArKyZjV7
M7wejIggZx5gogf05Az4UNXPLL-ldeUAX2j3vKeqcI9PVN8gLw9aIgf5tbtLzIejL5Rzxtkv2bUYzb1P5Mbwd3-EiMhAggYwNdLJLaN2NTVmIr5P5QcVlX9D
fgoAxEmO6qrPjGZFNOdADSY1AzJcbV03LwBpeSmXAzBHAv5TRIObqmHFNuak4zmIwlILQ5eeSwnCksCSlusnQw6uPJfv9ReMoaqbeL97haHXUFiBTNwzsgx1
lkdubHZaDTUWj5w3PFqQv8MghTTWr7yDzbDFhh5MaLtNe3h6TBFQhy5-UCkk_VjkrhnGUOpPvLnNk0PzBcUgUWtgwxNDwhy6-t7_r_AXXKh3wnoZSwlQDQYF
SN0pcx1GAOoTnx8P2vNptn_BQjUWlbw-gPexlBnUOrDL-BmK4um_gU08q-M9xwZoDPYIZeCgpZD5s56bQp0fsrDPMgWPANvLfOMQbIPL_HhqZz7oRuCRkApX
6lIlbwLhS8Vdii8rw4_iIsM5XUfF6A5ZeVglH7bu_LcWbjibkbJx1m
}

