sprite $Controller_a600 [150x122/16z] {
pDRBSSOm30DX4mJwRpct_nJahQo-2Z1U3SVFdv6UwoY9vxdAR9BRTcrUT5EyNBPhd9ThCcxUuTisyHdbT5H6vqCUCbwtw3NeH5w3paF6wtR8U9t8U9q5RA8p
AZ-svARE0k8nLyBv0pjal4xafiuY7rItPpuKlqlE0TQPUDoLc4q1PbGE4nclyv3nEl_1poRwl9H_9V91THuoNcTgqy-FlHoCLHyKQgV4WwbS0vXLui4y9Hvi
soR-UKtkO-MjUNj1RRK7OZ1CJaTwP_yR_YynJX0VnxIfSQ8LF5I3t5lyWQelDv_cihxStNoK2VTTrVXpJAWOgeznWQeUgi-eqRWgLTr-UtbLLrNZDvSNgd2z
iRnGHNYRQQLg_9OrMAlEkyAKgWo7oyjegYxnoJN8c515y5lAAu5IbS7doojmtjKrd3OPpsjV19ykhq9rs6NyDzDKhSF1ybArZhUZT3MXkgWErWWioWlLCPUn
MPHtKQt3jYaNQrCfLElWJMiWhkKbQgfEk8n5gWIkoe1IjR_6DBaxLEwBoOiNP_zAW4mtTzMYlCMBixr6KBcxKTdYQafcBrJRNCPIkL79RR4ex__WXMhJUHda
Tjbt2nPbMBmur4Arvyi54jskAWDkpAAyXMgVoxZe7kKDaBcM5ynKxQznj4AtIsu3oCtYnPcg6_rg_BrlxE1Pda5AbQ0Y-F-_1rIujjNesOhAZ_BGzSKXaNZy
qlsctkuohfbdUQvAbN4YuVbdp9jVTotAkmSRDp9KfSeuaKRvLvnjDQR9jDIpl509bCXxUP5RRN5bUG8Z8zfLgPfC4-L5jjLeKpE0tHu7bIhZC1RyxG-zV_ph
bG3yBC-03QfKYGTThd5GOShyiaRZyY28Dcu4haY-EFPSWqLkUjrLfcge1E2sHtcHPDg22iFU6gjhg4PvdULfVWsJQHRbvKhyKaKRGD5KU_IgG0b5UQk8twbm
uvZtqQw1kanvPETvfSfjnpTsz9noKJdbFyiVNbU1SmtQLO9yceqN1xNZl5ALQ-0vvS9bFyfpbBU_nbJb6eWvvUwcKDspM8DTAv6gHayJZUuoqTtOjPZolJMc
YXgPmldJu5J5bB-QucUg-2x6LUx6nKELQ_1wZU8LrIZFG7UB_Z-sSmqEr1WgPdc-S-ZkHlcy7AWnL6fybrNrG-Kug2tnZrIcoc2NfmfviGRRLcBTe41udhai
NyexSLxP8AZgeIBMO7VgcwhvznWqL8urs9xReaQcIlZnh8oxebueRy_t4kIBCykasnVJWVCArSnK2GvzY53VLx4exyXAN5MTKtwgnhNAiGP7SYlMAiKQd7Df
fVAYl7ChaIhXC9rD4QfLUUThJ9MfTr3IHQZM1tL-9QYEANzxQgeM1_McywA8yZwZHkehJ1_YsdXG_m8
}

