sprite $Controller_a200 [150x101/16z] {
pPOBZXqX30G7qyRS_yBvaKMoqliXowEf4vIebcUURLXzhiFWZl9SHO7_vYwlwfDhCfedx9Pu6PHRucNgRKxwZ0P_5vXwK1mKTJnE5Ly3VKOUJv-n-W9Lx2Iy
4iNNWQa7nK4Hn5FEo_nRc3eU1wPsujG3Wn9xcUy3fex7GL77urHvF8xj_RpeCnOIJ-v5dEJpClZhAHkkWJfZzMD0UWtUfsuOb2OZSP9xLHTXya5nR65GwepL
vQ0m9pr6u-afxFEYfnOMJq-brq2FjURNWTfwNEO5_BRgTtbXMFqcxd6QLjSy5v2ixl12jXg4sYbRJPhSoObLZwPrYfXMUYyCedTYDGYHa_UUhAJFXJTQjf9w
8LkrOMNH6N7IQLg53wdo572lTjO9QD7m1tj-KrfNP0GoZhU7-akDyrvW3AU97vuN1grb9tioXNj5U-afxycgFlzY9p9cfzvRYfSuEo_CxykqcawKylfv0TJA
ddSuSIM0RDN8GntFY6mLJfquU556P9hFQy0vSIN0gSyxdBWI62Gv4k_il31etPUSzi-BdqqddvSrRCkyyjNqzmPrU5uWLYJUbdcjEKshuDTWdSQzseBJj6ex
d0RM_ZCZCX7hWzf_9O3C_Bni0trrNY1iYBVmBo5nMfyN22JUI-SbS_fuNaqGRoaZ5X_go9KGE0qAtl4In4jUphM4Jk_FAnJnCYHZY9tul48KBrFYGwjQooEX
1hFYyLJpYXnFIN5YLUkZPiuhnF7ul28xwS6q0XcKT5v17agVCOYJdftNu2S
}

