sprite $Controller_a2400 [150x101/16z] {
pPThpkGs30GjgPla_KyS63DCieIyseSiihx7_2su6iJusaOVLpawIRHQJcsGhEOrIATNYiTYNeqHj1hn8YWJhqp63ZwJbJ4ubPZNu99H95waLtFoZ5NYHQzQ
JaxFY9VlrO9JPiPrlCGhqVbNz8HuEHd13OnsO52vy-hWFlg1GMNDQt0xezLoSdgDU17qZKxv6JjVPXHpSlgkU8bN8ZYLc5VdKKQDU17q3KxdvpMOn2Wpg7L6
ZrV8ApgLoTXPWb7BoK4ByMfv3HPZUBnYT16M0qDCYta1jvNLye9RcMab9xYLgLHnSgioNWXM5J82mSgHNATebPqHc5XbUs5Y5T1S9xUAg6GwkLMg5sQChZP3
SvnSwheuzv94fviccf4HSyRbF6MKrwKOdThrFyRPURcCMept8vtdCheJnNwm2av7CxgJg8Won9k04ru-AAe98C5f2j-RLnmKLK2rCAWv_RKh4GT5KCJKhy62
yM967vIA4c8YiegtdjUki_aP5DKan5iWDaNsdFBFeAXSEyLvxSteJfzaYq4TczV_sq5CdmQr1hPdNkv4fIdTBSGxdj7ZcL5mempn4hnyK682gYnF-RjN8WvA
29Z91gSRsXJvxK79_H47TJfZ7DJzmSM3Ed0byEKxA56PEHsTbuyS03-3eiVRoIhZV53wULYBGHsQ5_nxdM8ngFVczH3FlaiAWzfEWqsHYHFD-DsLntkDzfWn
3efAYAf_0MwlAQtVX7nGOkgxMiGxS2NWWn81r7VbyLwcSQw53sRYkxgTHhiECVGdLahGbCeGByNBhNnNCLvIHhTIVwD2lyxJv6bNH8oNaJ7kofsomCJA1vL8
uyngNDaqZLOnNkgyj8HJd9VEha7wlBJKW_ACwawbs7aD_W4
}

