sprite $Controller_8port [150x101/16z] {
pPS94kiW34C3DZRtl_1VI1btqr-OnEATu8sbYlIuZ2h7TbHjJSjUJaNRO2ilQMqYsuJNNgWxXHTesIcyGDXEW4fT0uXMPg4mMfZXOOIx1ZX6SdZy6ANz1q9s
8gv4QV-FLaAXsFMIjenGrm1JkU7XUZ6TC48j54QuXS8nCiF3Q666Xn5gU9YQyBoanbX0U5Glu4IjLzLsFuMx1ZX6PdWOfQu1HXOBnOyHE56zf96ex49XBtwX
S8muFBvNEF6f83ms1JmlPAI0yCW8M0CsrQnjXufrtynBzRTLtyjBfrNllezJMEroBjMmsiPBFwmYHhAJjMarCRfJynvM4IFRgOSLsqiVz0wiUdVMeO1Ld8iI
tcbb6bOShv2oteULdzjUlN_3Sm_L-x0wdLJAKVIxbwKvXTL9FRz5hHDYZ4BPQUKw3_L0FDyh2ZMi8hmd6l3Ac4qRzpfRVhnIckUTIoS-js0WnoSr9yPmiXPM
4LwGMg_fv7rOHQ4G1TNhhdVOvw4gKifO2NrxXq5ucJ56UDFgqmcZmEkoy7nOnHfWhby9NAXXDSD34XaheG_csm9-URdrcavg3olWb5clU8TFgoZK0XNLQxbG
myf1eLBhfODv90E5kgPUo-ym2Ez_iVLFrGZlOTM0qm9rzH7I24-Vt-43aR4IyMqmh62Xrj7-l_Lw_wEmkWPNVajC9PjMm2cpNh46Fgn0UFVM2nTgMBa1fvlh
PU2NDwn0eL9ZrCdwEtpzIcXWe53tK1HuJQUmYl0IAEsxbhvW3fmIwWMjeb29g0ChbbFK2rj5UDaK_wELu4DbheGJmyFrSc9uU2KydEGW4_Lo51wrNWwSQ6XO
WKBHwkNWKDmO7JXnkN8DVW8
}

