sprite $Device_microwave [150x148/16z] {
pTVTZgm-30DmQ9scx__2_u-AjKOeovP98FNLkVofzeIpcoi5TTyMomxvBsKjL9MHfLn5X5cbnWAIrd617ARa3yfCMQYy_1ffMinLvO-KnKnqPPUNN-DEqumh
hRpy6elSJaaOL6wD7DHYhYgErFH1sIa9vINKoF92NVackjBBirCMCx76XF8ShYmJNTdbsK49-UiblqQMjvYho2kfpa7bpyimfTR8GItcAf3tKns3IfYNKLv-
ZJGjvz8ckJ5hx5sJMIYMgckJPMgaQYaNLMkuYgLQPLvKCKlKI5Ljh37VHTM-LLreNbHj6tIXUL6rxRBAlB1JzL_AGlEYwhyiCozGDMfSOruuL4p9dnT05RCd
pmimLVkUE2_0LEqZMVF2fIgdHk1ADLBVTW66YYW6RyuBc5JjHLwR5wPKxyuBk58HHLLvuKe0jrMbu64N_bBjbgeyEY_WjgeSUUnA00xLGpK24oeJnKYu2muL
KsFd1VXKP0NE2vXGNQEega7p0YPKPUwfHYBcXLZLIAFh6HDLamKUWMTUGAYAADUyS5ErJweyymAyAhj01lVd1OIho9cObzj4rVnJCRXJ8rvJOTe5FAAgjWgi
iMkKYQfldmeppmNuLFUVwlHSpOdogt1IqUKrKUKea2fhNi2JgZgXCfuBFjNkA92gimi8LXMNQhY0frNrRrKJxPz1eEh-Kr45j2LLWBwfghCgY4QgF4z55Lsl
gEeT5T3ILC1PfG96WrIE0law3Om-hwgJggujLYN5KI1Lh358rHME0gcYAq8relMh0gbYMeYA1xdL-qzb_qycGhNn84lngUYAK6sb7IwLShT0ghI9DANCh_hF
nRzJSFEfg1B-CqOryZ6lsQUoluEXgkrZNdN-gQWIa1Mg-foNGuKMgJBdLRzGGGDLvhmcKDmL8v4gpekkBrNGE9KrhpglKe1faIgcSbwOGGdl5IkCKzdpmgnA
0IPQnKZdlEPKNG9LjMnsIkkSrpNgKAbVHTDEniMyP495bbjLQR83ka2KgIABQmytsVF2hqz5LLVXlGeSrFMySA6YgqbpV77EWvgQ5tvN7JGcehpPULceeL90
39NFD3-ltrN3pdW7TNDUxOmw6WH4HIZp3MhUPSwBAWMQ0g3ALzvyOBYewjf6ZQqhLSxoxizB3XHLgZyrOkWTdnVtlAXIe8r7RCVk7ULvvqKLVuDwrDWT9k-y
XAe-BEtulx9GvHYKOruZFvRZb3Osw1YKRrx2tw3evobrbEUR5rsjay9JwZJvvtMiNNbAXIh7eDppKlu6jIb_WuxFYtTUX0qBJobLZlByy-9la0SrnSIW7-5P
7urstw3yaLEDRVIQC2XZNgSQUqvvzhmQJsb2UTQy673jIUNPrukgjFBiZoCRp3LnNWp0b2qve2fxKFQyiikpvsLUW_HvMOFAdnS7jL84JjE_
}

