sprite $Device_iphone [62x163/16z] {
tT9hphCw40DWvfhB_XTy3g-e5Kg0IVGXeVft7s5dkeo5M5LucGlhNuHcxQGdqIR2atRyywoTSCmIm3WdwS1KgwlSuvxrKclDq4E3RRMhrl71bckDQ1Bh3Wvf
DhFEu1iD2zsMZcXIWsvBHpI9RMbjgI7DXkokTAjXeJ4ueadT6ut14KtYtcfSAQBPVASnEA3PjpHMSprBQJMfGmEdKvlD6wqfxJG6TrDCrQ75qrxZIbthgWfD
bbAhRqed5L5eyjJgczBPH1fDQGlmnPMAY-oqj_fwS4qYUwsfqJTNKk2FJeZRpPKsscZ9q7Pz9T166xIh-iLWvevEEO2pCdTrpkXjfuCP-4IxQkbZPuO6_jAc
VZOue5NpoU2OBjt1KNt0YObcTHQYLik0BafqglLQ5oUQrec1HpG6p-fYj2mTBH7j_zixhISwym8ygekkT58NMg217zCfhYMWmxEVr_m3MW8w_6ZFQtw5bd-b
zLhJ6pI_Gaj81sS_h_a7jCHqxD6Ur_mABNrjmrglDRr1yokqzBKTT6Jsyvf_G4jVsr477krvpM_M5j0T_7BDRzOsh7LSoxZctzKsh7LSoxZcESsFQ-2uxd-w
p6iljNPrP7QkjQ_vNgTIfxMlTbAlfKSrR8Azqz9ebBxMVAuDTb1ZyAHEfSvg39xHA1tNm9fg3MfOQ9JkQBdGA5tAbDQqslKNFU_ALzfNavExUuSNLJhLOdyW
kwtnVD19PJdJckiVjYsfz-cz1fQq_UI3rR-nAIzzRGKF0tt0idIrOcCHsoBfQxCAzNJxE-UFfjpORBf-kQEzFOt8XfMRqhvz-5kpxizAkcdsjlJwNaUzbKRA
HwiKb8RTwmeBBPiM712b3_eOrUrS6AomzzhjBzuEZkliQr9pfH5TIqgvj5UAQwGa31xN6OF7TSQLnZK6ZsjSQKfdWntM1OE7DGQ7TNmmaWuQVyj057gWD48E
FL8QaPtEiC6GGdUk5AglcZ5uE6ogYj8JNbMO1j5_
}

