sprite $Device_game_console [97x150/16z] {
xTM7YcGX48NXKzdtV-493hr58tUnfOhesK3sOtu7Boh6wZ56k18wnZP6p8tHG9362FkRnuXgGcA4sy-IaCewdiSduLnLPpr-4cCOLSPV5oEqEdvPfpN-Cq7d
TMoCzVZrAfIAuwzN8SNnrqvQ6dzTH77yjH8-sH9_unQmFuxzEldsDSJFuuVhBa07TKRepvhY-nXXca1vdNdy9a1s5F-rhlYxWCPPdLnzVDUtLSQtZ9yhZc-w
2_1P_7LDyNCbZtB6NrVtBZoiANwkw57U1CYYA7wkANwkANwkw55-Nj6Z_BoCNredT_v5t5nJ_1prnC_vQAcJ6t7sAEy3mslUXMTWnDaNSHyOuGtn4uX8eYJ-
2YHH57y59h7nA9y3K_32-2km4kkxS0uaKHT_1Tn_2L_Y5mAJ29-6vwzc7J29yREO_xjfFJ2DkJo-6h3NBd04NE025xZ01IvmWGjSu08NkC05N4Mi4N1Y4I9j
0qZcJm5f0ep-xi28Um2LroMJj02YBy2WlO0hML-YEPQ-IvvJD001dy0SIGF0ae1m0s3mVu1H0n0i2Q03SDWBy1OWbBm5a1SGGYs9C84v9fi0SnqWG0AXu1z2
O5M04Du0DmPGznOny0xC2oZx7Z0mr_JH5w0J448hm40d840d88GU88_l11Ze10Je18JG2X3G2J3G2GZG2GYX5I2W4s2W4n123v37Tm8CT082T092w07o-4w0
WKv0yDbY0pYeavEF0CBdats0SJRT0mJ7Oty4rlZdn0eKrCdf_m16nNG1iaxDs1OWZoyYLe1HEta71FNJ18JGCHArdrN5_mO
}

