sprite $Device_gamepad [151x96/16z] {
pPe7TkCm34H3TD__mDkaQB9w92qOTFclf_vWHc0Iy-jL4BFeZWWpqTVROT4UJEsTKZg1tpGr4hq3jO-I0jm-93yX5b6pkbXTYdapsQt-OeZoJVa9aSW-8ZbG
y8g1jNEfe6Ag9Zki2lWTfJB1X7oJvCOAdZumqWvcia6YHv9wWb-N7xnKH9X89_2JfLXzlARsPxA7j2UMYedLtKwTtyDZsJ1xaHV9iGjKrNwAKMCM4Vsv7hIB
hCzlbsBTiDZ5C28yayASwbSzlmFpyDFQEfv9Rg9zw0bI90hs934X8bMrVJ_e05cT7wHEOhPjK2Qzmbef9jOU7hwFw2ABIoKwmCFqEhRaf1ddXwfZMTp7OlrI
008oOkPHrf9UVj97BLplul67jKj1xe3pQ3Aglomg5IYAUK2hMYh9OE49hKAfhi7VY8SbGyoNwheFG9A3UVbJysDmNSmYd6idJTe732jcOMrvVdmPwGzCb4jB
WH_n0KIz94M4rfIAiz01cvsbe9LV2hlLWpv0EcTeMeiWLV01t962LhfKHQ6n5BJofIhv01b8GIjLgfhFk5IWvKjL51hd1pZzXtB11pIIcLJBdZHK56h_cER7
b3vfAZvWcX-bbm8z5jW9rbNvGQhWip4l5QMab2b56yBrKc4f57mI-ILBLV81QvT2IGXiNmz8RIcKVROfB5qANFC1fC_CB-K3MhrKcBUK1WJMB0Ly4U771mIM
bGe8FUO3LYu51PmN0eMbC2W1u9JF-bAHzX62K0PQSjAKNd9VNoeyBmcnQgbgLdnS293XbyelXUi_eW8PN0YGjgPKBTrEg7Gl170zlrmPP7uXWFdoIscjljJ1
lGi1XxQqMgbotBaGC7Wc2qiXhRMhCB6gQ0ygB8KSfXs8M4Gwh_y9LKkLrvBPXO1nnMXTgO1Z4CHovK80vqkL9tG7AkW-JokslbGWCAuTldyXG5fzASo9iF-t
LcCybBC3l7xIpBLyrzesAB42_BjRxLn_BfTghXMEjTM1ZqFRTS1WALHmUFMH0pK5yrALiPXxcG05y_pgIFp5JGSul2WXLQN5niWhOlVYHf4hLJt5yS3iTejj
xzlD4gMgGX5pCRzjU3w_UhjYKdtxYuB4ILEFSTxzKdvrhx6OcRiLyYjuZSNClzzf2QaY6Z4tym2IM0f5E0360gcV54fL2HAukvblKY2JNnsok4PkATGXJsab
f8hm5R51gTuziKAfrdTC-NkSXLBL48yJk57LkBMlTq4mWzHdm6B-rydU8FKR
}

