sprite $Device_PDA [150x93/16z] {
pPZRajj024G53SZ__yEvgZeNONPcH5awBydkqocwpOxPhY2GxN68kJ_EI_qN-YWf-879SmPbxWJogFG87j5pMX6vtKbKrSapwYNw4_CJk7LGj3gXTmwALi-8
KIYbJkxs4YLmSc-CefaKF4xZqi-6Hvm2y7s_BKRHP5Bsk_InnyAMQ7RYnm_ytxv_FaQHt0bE8lEIky9p4acz81yDpnWUoUkbDuH7FbeloSChLcYw9Mue5B6V
vFNwm3P0gaCMwjLGA7ldG_hhHQSwFAlntYr1ftmRm4OfOkmkbCqGhJ6Avk71fa1UBsbrqd4TOfx4YCjEa-7XH4EzPDa9xxbOBp5t0utCXyB3b-HFrOLR1Ycs
0IPOgvVaJdbuM64-He6VO7YuwdDqmYRV4hB7Lqwuu4FcOiJhbNf1iOgcJDNBNZz8njldGn33ozv_McNZiWuTCbclUBqkUUaSFh3iEQk567KAaGED4I_PNxDU
Qpe4CH2Z6BsA61V7asCZtpZ4Aozhr253zTAeOspp8Jgq9NH_aMJPjSYGxISO-iPHrmjjFaHiPDcBxLMCruIs3ANLUhtGuqC4eqTeH1bZWmvH9nVhPNfHXuXv
0RPaUvKnNlDXU1L6g_4jiQn3w3HaHJ0HupQBMkPXxX773xIQgzUaJbuemCpZxtj175AqcgtNYXF3evJHv3U9LR6zkiuhwkHVap0p0uvVSsCjr4lMmwC9xvdX
VqdfLcDzCGgS14qikR5YOEPxiUnrfL16buH4Qg5UChiDpA3_I4KuOQa6m5ACUQ7-Sug8dIV1h5JhzPe9Jt7w5CQ-5wMgaDXNjuJ-NIWO_q_uXhSYlzvwILee
0umufTBy-kib-BjGu6m1C-9B-H6noIq19mRaLp6EZrBJI1rZzJOm3fLEjAAKRAIlNf2aKDLDa-stf5IDzJg5PxJZGu50UwHOhtfBwB-pyM2xZB3-gLH_lSIS
d2jD9mwga5glbnV4KMCAd9mQfF8_Gb5f1Pzp7iwIWqw9L7EzQcBV6UY1SNHR6-99lMgjqxE5UweHV5cludr7LBPcKCPe2fX5v4eSL3_YXPU1DSgL31nKkzVR
6CD-0YHAoQ2QmRij4V7lEzrMdVhhbHiPIgV-UXL6YttghvUTmSBMR8pH4i0ntU3bThyIOOnnSt1vlUBc8UKnndECw4Khw1EC66Dm9pq8jKjAtm4
}

