sprite $Device_DVR [157x115/16z] {
pPXRZkim34CRHx8ixt_15_CaSkkM492nnC_vEiZXq7OVUzBaV5JDgQhIog9zH8voQ4tqDsT5DAILCeeKSzjq5Qc0TeY-o5aH3McLobQfUarv9DzeDRT0escv
PQjKlQRHd9bbuscfHhdRWaQHyoXe56aLqP2MQfHNho0QSbOqYhI4-KXmIuocp0etcb-zuzI_YhGDPKkgNYD6Cwg7ict8cLasdhJvu1cpc574t6THezszznZS
DhGnJIG4rxOPdKC4SCNAfXA3sras4S0LGjFFiW6kbj6XGk1Iq60KSANc0rpUXSCrtJeVNr6V4t1rvkCZOquETvmPPRCv0LTiFlo7xHtSeGdpeUCBRRpzRpqa
qUXGJ4dgVFYJKUzWpRtgNkVZ8oPW6yJexh8flgFt9xRCiZbWVGxDCjh7V5Es3zzT_aVBCtejctSzymu41SbpsQQfjBJvwCIeDc9qnrcbJemMcmzJEKZPykP3
MjPykB6odONdutXSOmdpiImRZ29Zz1Bp0RGBtB2UFny2enSuuEsywhwR3y1znHBdGs5q3JUi9yq7qDPmmBlVQBHiQxZxtHgV3mKQWGFUxVDXAwEA0u70nTt6
Nyhuoy3j8m07l8Jv873tkEq-_VLyT9y3POl2aHEDb-s39N3x871tkhKl6Z8V0RZxt9fFmD6hBeUx4Uz38k06Z9ApAWuNT_j50pWw7noEu0MDNk66e6p4A8VZ
RhbHm5tcmuXH1aTcXSp74vpo-OZ3nTqQg0177Yz1E8x7omOuCXynE5uzNZR4wNp4uU8VRynbdCn748xZSQE8a_a8ml4ODOhuueUsUDG2U7qn7-luwl4Ipz43
TDP9sP3bVCJJB8vdJj18sG8vGtWesyiCKhPGZaZrZ1XTd5KRtJefsyNeFhSSZjm-_cvME1oPZntLytT6xoMALyy3yx6ZUXoEt3wsLS_tbksQret0yVb8gvul
ojOU6oD6uCY1aERMoNpimIDmR3vIPiN9VEoABk58sLBTEYbRgbjdPSkS5KVPAgHVuPoKBRDwEAkgvCJxIzgZNEIBBSqeVtyRqAgbwLQZ_m
}

