sprite $Device_laptop_left [150x148/16z] {
pTcBbjiu30DG4uJi_FyNxyQZE4QZS3Z7bcNie-_s7e6brEdKFyMdsuNBup7Vp8JvyNyMkvj9L3SfJrHtCgbgV7btKrcf7b7Tg3mkzr3vyjXIR9hleCAkl1dJ
fAhn0xNuD8dg3WDLRBg52ikkl0ePhS9dUUDLt9auJO5gs3QuXGgpReD0DMmRZ5TfUGjjkeKAtmPALKElbu4g7IWjRxpAvNfvPhXAhnVOJmQhz7gnTqQgADj0
CagbrmlCD4DKUhsuDHAehja6xLohqe7IyZHNgbos0Ip8PIhT1W1YbwYk6IW02LPtbSj0RObTekfylJYGPOcgUtbfLpULSMSgZaOiI1-L1-MbM1rKDiVbRRbG
PKNAS_U0TPMAYvfY5gvGwK3HQo9NVvKEb6z9irJLQQ2IhduglLvgULbMDnKQ0vLdePFA6-KTEAxbNDLIw47mFLrKGNb9LpVLJFe1LZyL3vmMEggE7nVcn_ag
-g7ZGbaUFLJq0oukhmLZfwcEidn-tGvamPcg0pMMn_ldAQKGvwWEiSghl1MrXdQ6wW2BUnFBAtwUwk_JvVDMdg2anbDKUPQ_ogEWr7LSbOTfUHjAGpj7bMTj
ffc2qlWPghnB1afG6k92bMm3COKr7bUHUHDB5BTJLB6Bs_KYg2WuLSLeeDGKXpXJnQ2y5iez6A_pLFoBYG30OBpEKIcBKju7YbnLVcIyL1MdckHw-ImFSAuD
qdbWl5GLioZbDL7rdE83ewLLXOopcRwL1v00CpLwMbLYLskW-EyvuVKvkZEkCQqgaIakpvqEkF0OruYSAd350rL_VNBzdFF7ydkDbbMLx43nOnjGQYG0Cgwn
U5PL_ZfGh6DKQwmyOWyDnYjMBMKBrPJQ1bgZm-crHWztVQ4bLIKQA4KHSDq6SavSdPvuuyIg6Z6bjm5_JEH7ZN4GgvHLwa0jNqtRDY2UaHhBLcCZyfFHGvLc
ZijptGQELKA7rjYA_eJyYohU1dJP1b8ZfSOMIfDNnGD5R6Fa885LGWYKIHFTSgfVjW5Rsm3GRU1CcX1jXhJ9jp6Yq_-q3PWwA5MfQHPJTXlGPSf54fGNgdIW
sjrHBb-ypuaRsOF3IPGdAYqllbqAspNAGJ5bYbM_c_Y-V5qlNpfp9YqlePBon2JRO9L8ZGBrmoPLnQRoSVdMqw73nNIiF5NLB4LDkWsSKgDkWtnv55EW2apw
5AzZL2_VLT8s2IukBrRDRHC17IEFje4y1W9JGXLzP5EVuheDtYOvgB8b6gWu7fYYf_ZN3LNs2GygLYrpawHlEF_O1coMfr5JFYv_po7vyXGdqRXU0fEMbp-h
yYNvRH2Wn9HN1QxMKvpo9whJojFu8a-PV8qwKEHXauRnSR7MIE4rhfV3vMcin2xT1au7DWBtQHpKT228QopR63NUcfA3vRN7wtkDa1e59L7JuHWpDKBdvyXx
vVXuQOrRUXvKVaku5qa_auPBNACcP-fVewRhG6biphjI1zL_l3INcVGI2dDHUJfUoxo8Qv19uoJBiWmkJsFEDVCoZpHfu2J5DR0yDTKK6VlWGvkzonFKyk-M
63DG4apyzur3ZVNrhF-Z1CrBIBz7t-3d_wLH3MPnNLcUrL_1YrJJkeIkCE6VJusbKSs-ngxbcMecsERo1dvpzJ891oObDYBZDKjvfn-ILTMq-oM0Nzyuy_ac
uN1ILZqlYuwiF6RYR8yS2217b0lyz46gAlyu8uDDeqAhDRm8Zbsjes2i273VXy2UkLZbVF7ypS8qEWN2keaBr6FRN3QKHRw1s4-KEvu3PQDParCCutuNgiMS
c6uI5EoDRZTnaIOFTSVFZXhi0rq4XcSKDSY5wOQ1q-sUiEAm6z8C_ipGeVeF
}

