sprite $Firewall [150x139/16z] {
pDO7abuX30FW1KcG-ryurN-nngc4zz2KPFitM9IFQzFGFeuB9E4mKwU-XVqWKwCYvxWQz9upwjNbmHc5yh2VKIWFRnmZzFEWdJ8yTvqnF4-_ypI8t5xxhZyD
szs5Ybl7_i4rhjeK339_H5vIB_pCLFtpBLQldGirx9-VciZzzGB7f_a3Cjx_AKsHtPTZ_-wOCq0ALurobOIDnsQumXF_LYO0MINrNOMgNIfCP5Bjg1UKCtEz
_3GW86LLmB7rplDw-K99eRBHOfl9NPNffSfVnPxXrVMYql2oAdtrWdjupgc8BTHBbSyAx1gUBrTjybv5i7DuxdAJz-fR4Ahzfd05IgfKOSB_K3NzAap_X4ef
U4S1rBgg_TKZgb0Ho2QPQlSZobHcYj6kgxhgr2PJbSDRLxLMFbK6MPjUAWQ-C2sg6gidGQH0kSg7HsbTXTTcDrTjWgd2n5GeKoqKQleOInDC5UjampFLocam
tCNg4PKc6CWn1x-bF5JxWgbuSPQFA5F5Get1wBkV5MXBfu7NgpP9Nugt3rt7SHYCmhWHLTx_XRSECJgP0q4H1CVes_91f3dqRs_yTxNvYIQY_gdwt_IwO7fl
BrkYKZMPgCg3WkaeOF7sacqJgknogCwB9oPrqKHL7fIehZIKkyG4rMIYAjXGvxk1jnSQ2YhCYbcL3LMkD9GVL-JyvcJ4sAHA6kholb879wClKJ6hR1gS9tQ-
6r3bInHKU7euRoWmA0ogV8aIrOVvzgjfEERBfgb2J5JbtwslxUB5q5N5JLJv4YMgtmdapsxnMX_BSAp219KkKLHXfcubH0KpcovVegZohPog2HMQNBd9mp4t
KVM_iZOMZzsc2UHhqL2xuTZKCb3bdEG3XC-A9C9r48v9OlUcok91vRC2AfJHY-SkN-oeob-bocU5vAAONklTe8riBp51bRyAbHKF2IJwegmQojkhSjaqbJ-O
LfaLgM89PjLcE8Q3CfKzcFgWfsegmSVX64oYIXDK5hzGnPjwftXihxhSeR8yKDdcGDLiIfNl1dvrFWNu_LwfMWvwc5BrQH3LgF9z1QgSgJHHnKCk7vf2L7A_
GnKOz5LH_9EhxAM8QHALjGnL7FGq-I6Nwk6O7nHLNZnHOT1xuVadLsbZEnmJLRY9gke9P6XYbAenDiCnghIXHFMUoInCL8qXuPZi1WKgNJQfQbK6lHKlJLID
JfSlcwcQZ7NZmLG6lJIKgDAr3CUWoWAqZiSQBmzKNZnNiRqqY4eLmp6e_7uF6VIjetYgOXdbeA2QK5H9otW26TEVN1P1feekCL6LlqgLjWnLAObA5LEiLD75
9mLHvKz19Gtb2MIDe8hvSQhWqcMJglm1g7JGKvKeg52yVqYg6klNdhLDRGnLaU9HbIQeM3ogwFBRWoT1bHUFgia45J9jg7Zv3E9915HIFAWmwA52yVPLtZ9K
xGtwF6Me445kgtmtc5HvIGAfGvK9f4QGFz6NAbysgKgJP7rs3mHL_ZO9WrHKlXjGbRzAbGymgb0yNAMxoXlAL9P0kecgDFbLkwdquL9Kca3w4aKL6qhAI1Td
K4Fng8eSkLJvOmPLEv7sQsPX-UoZRWnLghnuL4dnrkqrpw0ngFAXIfK-BLDLjiFisYTLcaGb9m7Lh-8kFzZPCR6zKfKpWoex2QgIB0dasNlSwAcAreUexDQ2
QXggKE4zxi577MDayKGbjnPL4nagB5477w7s4P4cgAoXH9Lag4xUBJEgRJLHKDcW5zNYWvs3uZ5h59KKJrHfWWh5EtYD2nTKEUZz-nOE-WBLOV5eeYjL4Ull
Mt2CLDaqEF_ihB-h987qeGfLEPi6ReeyhbH90kdBZkIYvUex-FzSypCJLVx0HTN1Xm5L4hM63-H_xGoQGFe0emh5sxoQlyD5LDjhU0Bfky6x2gPTrTZx7ozC
vSicLIpUlcf8OElVvr7bGvKg5czVPObQeodd8bInCLHVvOIKAWQs_XfN4yXelVjGHPCVgz1U6ejIbLMiKFbkSAv2U-qca9wBYkbKnVQIRmQXIXDLN3Qlg1X0
yg2emc875OftHKKNJLIbILGNJFi995LPFAXmvzrIyLeznwNfFO7CXZe-g4zJDTyD0Yeqr2CgtmsWWka9bPigLPSQYb7CMkMx0LNbna7n6NwjyhTvLC5qgOfm
GUN5euh5krZ6vYfVDjzLfLm7iRseyYS5gaexADvXUyqpgFPkazx3iVjNfIgNJIP5vxl1UNj1bSaQL31TBzuwi6KiEZmSUy34roUJILH5Ekg9CcP3YKg2gAVA
c0T55Oht_0KJL8-Rs5wcyX7rU7jHLN1GNxeALMYeRru1bUm6tselgBvkOdjLM-o-tbvLJDykOnrLYlTzLppzYty3
}

