sprite $Headquarters [124x225/16z] {
nDH7UiGW44JXwSZS_yHcIg5njZv3wUsq-fMentyJaySzYKU4onsoHMIMJfRRCzsXy-MMtQNga0CosdGJlZpgJ9chQnUoPA8-oj_gowQavEzrNIEtaY_e3Bbq
LxuywjDbhYvMybLTPWntoTTqaoaoKI-v1PgWa-J2eHFaAKEh9PDrTSXv0PWoj92Zv8cwAryUTRuywXU6UxukV7dKoVBtKoTMCbKlcPZT9hlRRNAtRv9XQtGQ
CfjsIx1y6JRcaowRMdJx2PqiY-nsrvcoc_GSDaeQ3LaKTjlmbWIvwCssUEuwuqE7WTvj5QqNlrHs5O6jPOlOqXTVRnisQ3jjrIXzeImQfg0jTXjNBnpwejSD
UhFDJbjHUkvuBlZ553Hiq0xRDjhIPdzshzSDMs5lz6ZRonRnDzRBBDrv48QX7v9jzh_YVm0ft91ov-SE9xKEM3NzjnNJT9cSw8Wmcs8t-BJNBv7di1EYv4IJ
D9jc0rY3_qt5O4eOBJRDneYaVaetcIaqKkYeO12C49jcM_WL-myLgxOhLY9piZdZxs7XOyNUwoT1ezgkM94p2oQhwudCvc2tnZBz1uhLKp5DHDqXIORP51l0
6lot5QjBCQFzN0XrfjJljegMhejUtrMiBiKenJoHoHxq67cJOcEoisNtu3zF1bDe5goOukQslyU1BbRGR4YGR0rRx9-hWLfFBDmLOujzVuza9HsZSg87-tJD
dic3RNM4vdprzVvEnKw6s1GRm67mHyMOPyMIpJ_CRD2nYqsnWM7yU_JOQo3ph5XoeiKMe4RicZd5ncJN5ViHJGIjMEwAHGXzwWuSoIOhGR4bNTIgT7KCEbQK
bs8Qj_VtkJiezYxXGsmETaDuy0V5mb56KioWNaqtitUwWsBto-CLiHlsynP6Rr56FXM35IFrugCx0E7O8t9TIpwKxfCcFwCKMuhvnTKTujGT0EZN9JdOd6oz
n4uFNc1YHHb2HzAAoVojEn2ClJluAiq-JdiMQ3R4zbqps5kK0J7JuwwsArRAKsm1tkvlr8pLqfLUOlT5LDT0LvH1CLD1ezgkMCKaS-vl0UxxcugTP9ZDoMvW
_MVp42MMOlLGB8FJpi7MOTpsTqDsnMxsU41BLvjYOajklrYuHDwVQ-xl7gixq6m0QxSluVlLi-CHvPmvbs9xTrXaTuSvsydclJkKJliIlWDcMx6YxVQNt_Rt
V57fxV_zKyc-wWwAFIoysHniwK7RxLjiiF6fxj3caN9tY5jtQBvh9CKIwncbWXxi_Rac6O___ZfIEfvxTrYxFSIcsIlAjmF5epjGvDVTWVvryUmEtkrcK-nR
bDptD_pQciYfEwmZTUmEHKOdA3R_ScPcEPB3C0oTikHuxd_XNXy8HM5SGV_s4Y-YnKT8fKHYnR-TnBRiSFnsqd3iyCBRLqWKvwGHesBWLMAU7KBiGDajEr1s
19_go-ebdXtOrtjse9Ek78OTghSdQwk1Kyh63Z7mcsViW7qxTXZ5s_44hUpOGJVod1tqf1exuA4eycVjOKl9scrVGsOXwLjs-BrusA7xDrkRgL9QTc1VXXsu
4P_zP_BQnGw_FWOxuEsGccU7mRxUiaDSsO6KDCUL7V3sGnAxi8E8tB93iAyDEuofnOj_nw9ywyWm6DYxwz4D9-8qDpZ2iKFjfDM_vL3vsh13l2mxgBl23hmQ
c_tnTaJ7sfqTZi8EVDonGxsHoWvhSkVTl-ca-FTRTg2KUtRur-S6A-F8ORB_RoTbxTonGoWfM7PWNtbc1-1aDNR0GuktvuOTTA6M7HJCBkmWE37PlxJPtBC3
AuiTlCHe-eKTr4bxzgSpa9Bks86FMtR8gFlo_es5SUuuiyD1IlfUEm9Hcr8wTXZnO6umUM_oxyeEbFtA3Z4visU74S_c1fHTCUp43dXx3CSEyRBimBuK6BTp
0ohBhnix2EaAEt0iomvL-is__Tn0S9A67PIIM9jI6dRWHanW5Crt_wvmujc1hN7kp6obX1tqhcpsPrjsRi3gbXq2Rq-ETMA7e5YIcFnxdFnxCpSW9JLsmBzH
fC50VLOIerPsRZ1lvmQ7H1TnoVxpP-qObXqaCUO6IAm7CzZ1pmqAiDRiZxUJ_HixrEo5V_l023kikxd1DA9RkiJ23cgp5uaTzu4nf-34pmr8IJNxEtRmsT_C
3NhsvtIM7UYaEtResJ_3-tSCb_rvq9uTGi2wPOSK1lhiZmMRxF_pf5Q4cHl8lhViaEgkc-plvmQ24yiEylRE3fIez_MxkS5jzkTqdXtoFugixD0ojhx-bxd1
WeWjE_3QSmsJ_JcMp_xZGVPdRh3wt01sUE7jPMtMtCuDaDZxx4_PLrfseEo57Ph4FdcvrostGHW8m8uaOD__XNlBd5QMXp74Uvg_UqUiFUAJSt63L8gLtXzh
QzGDyhszHmgW_yaDyC7KopRb1cwqzmydlNyA9zmDq2NXUypTm3vr0tH9t0tUPM_XqWr2k85vNBA3OSC7ojwQa-pmtf6Tb3BEDCLx_y0USMG7qlk7SeCONrqG
a7A3Y4Xk4C8DnimD6dE3LCgP6xYVPmQxApU8aXrqx-yUt-a6tTVTm9KR67U3qIPk41jk4CeDy2brPX0tK3vpWDHcYsxWt0qSyPJq_gxS01zKRf2lhljk4CeD
y47f1d7d1YxS0E7apWsCkO4hDp3b1lK8bxe1TkG7RX3hRj1zuWQTkm4MbBj1st23a6wG0skFSZvFtS2tt01hox93SOCv0KLBMsp73LAND763iUW6M95zD-ZE
tG0NebitSE46UMRGxjmWaXkWxAptrswG_Zz2p1oWI-eJDuWLD_3Y1dzUASqhDy1bbcK7k07f_TFLzPaRbC1g2sw0DTTkuCaDHfkuGTzt0zJoe6wGL-IV6uJ7
r0t64pV0jymDuv7ktux_cb5xVsiDPMyqE_1I5ZSeMypgp60GDq1sA4UujsvWAsvWEJlWbBPaX-86AZkuT8EynSZz6mklPWwQ-tPsI3IbUlzGRZ0QFhZg1dcB
-SBCO1l23Tw8nzm0fJoxWLStaFTlWnkCrfkJx81xkwViW0KbRb06kkJz6zcX7E4oDnWdDoW4z3ht_fccX1lOsGrOTiXTqjGDi9vfHSZz-uaRTDIR4H393gpt
bsumsiGDOi0DCW5bDuZi1ihz-Sp1Ewm7TmFSspC1lSwzVzpC31OtADa1PP-vGIzkG7h_CEq6CZk4SeCOnGsI-sFhByqC8fnmDnYDku5Ft43F3695rjm07znt
0-x--sxGHNPuEZE8S4BT05TIFdD0p-StPmQjVGatGDc96x3pUUK6lFT7sVdC0JuuSOCGRX1fYproWpvpWn0pW_L-esOEcdQ3d1qg0JroWq0uuMxmBdioYxB5
7iuCekoTkm6wfE86_drkWBBpcGF4vUe6pjt0Kw7lU_yKJlZCWRMh6_ZC3LouWHCtUAL15vuT_dP9WK9lpmpgcOFshYpF3hYtQpT0BTQVDxYwGQTku3Tku0jk
uDGDq5hd8rpk1gxTuANSm98Ra9a3IqUun0tKp21t0toGk0793ZxcRc2xCuCbpTy_gzZ7fXk0W9RT06lhB3kWIrfo0rJJvSpWZXkWx2jkuDeDOkO6z5d5VJTm
uWRvwagoGnuFysztWxGY-bb5uGQZFN43-zmDS2LbRj2K6_11C-86FeGR-0CtAEyrC7U3CNC3b7rvPZ1ECuFrK3UkRY2ULKnTqcCty2qto8Ck2zd1xUe6hh83
Fy95TjXq0_vU0_Tk4E9PHUK6TOjnDp3j1jRaiufm0_lC3GAlMU-VUPO_gwZTmAiRv8i-alFHlvhpcODGRX323VHx3U1bnt68PnMDFAkuv0QUtQ0EcY4p7RzU
n0rITcZuu4vsq6w0vVxPovdWE0p3C11r5JN___2UsX0bCZsqXlc0425zWfP-yFrrg5MSanleePcO2vSYt_zLgwWXfjp0Umt8QE6InGwvGQsaptA3kru3HQst
Z68s7Aqxeb-h-AZNW8m-RLUwb-rqTiXERX2dGqnmswbMyNexoms2SWCDCP0RXCzjO6vmTtQGbTXhm9YPVIy4v0PMgsZLIRv_iz4iFDSgwfQaimFd1WEC1cY-
SQsYSWECWBwvsMZ6qI4f83UelTtk_fORT9WblES61tVjxOzw3SG6HhykFDSgLcxmuxFlt-yOpVDDjwJYXjp0xlvY7irUr8Vmd1jmhm4PtMCFiUERW-6vmTMC
xcAKy90RGA-1fj6yqALpSwy1PkuBRsyEeDT0ssYURqzp0pPwbksG6u3SKn1xOOFSO2OpBxERdnt8wFd2UsuWvgb6ytpJsQ5lTD_s-kz5p2wySWCoUZxxJNjx
B68MueyzJUubI76lPPRj2NAli3sNCylsbDohCMOmVm8
}

