sprite $Home [225x171/16z] {
tDSDakiW30DWR1d8_K_yogJQ_yrhXBDJgXjy8q58UUROBUL5O-Q0t_AAmc6BWE-n5xH5WBmN4fexOWzr5Dhhs5WUitw9nb4Uy2XStSPj2i85R2nF4AvWOtdB
2yrfEy5ZR5aUo5jRQ81Q7cClMnvZjYXlxH9Dk5WM4gQLnzWIs_I9s2BRr6EBR5EFBVxHquNhbyVOw_8OMtoRkd3zyXXRuAEtaj00iJmzjl8sTU7wszI5-TjS
NsZ2DbDZjiesQmsHkCWswmYUHvXziQ3k2Jo3q3opF0AP48JFVx44ULADTkKs6PyARQBHBhutUK6a01bemlnj7XmTuGYgDLh-DgbZa0baue-41XpWvYkC-biQ
_a1enpeczGWolSf2VPl2d5HWxn6F2otZtgo_9_y8jYs0W70GjMtMuo0Ts1j6BX8wpkX6ik-OrcC7HhxG70Uwv0eFRfXx0hb2moaS4xd0te5BX0v5frU8Wu7c
2ysXuVGAu_Y6OJn3QAAEILnewmSyKMWGSFCLjjuERXW1w6O7swnJaHhiMpynKAr4qtNprmpQrjklDumJg0fPNas9IubEujU1UYa4ga9pGPVziKSbyVCDOuL0
LMXGSFaV-uZsuIZsO7qYa4AFcXtNWeXeBB4rrYS2AKJLarzXnBxJ-q3TpEQ03aJK9wgGn5xllY4qgC2eWRZbcIgC_IW219h3DE1O9ugJ-1GLaXXtqU2v5Om8
l0f-u9E5cAim08e0kqK03b7OnpVCCrK8Yk1s7aYU5oQV25r8855dWLpddSTuBZ4oW3IPO-GK3qRPHINwb12VXDWZ7BuBYP43nBjFE7mgyVeA0OQyKv-6tuCM
MKHC0NLUX1y1jru5ONg5aYzstt-0szQJIiGqKE7z5pWYx3IvGem8wtmGkFKK8bpCH-0PtkF0BUKeXbwXiiuJm2oYgmc1Tnge7yNv2eLr2i1H8kQ8haRWAS2j
cKyHuMA4TMh0sTURQn5uCb3_aT8hbDQf0yrggCIucZSFj5jwarl4fUkS1zg8zoOVnRYSDm_q0ImgyK_MYHcWtu75F0HYPFFYEyzcW4wWcRKg4AzU9wmK7UWZ
wBnib0SghkKDZGxiTVW6SBzif0VgfPy6AtF0hSS0yhAH_XLnvU4hSy3cRMk1pik6lPuYncNhj38DB0LzQvsNZVQlU0alOBV0fe75elEowTg_ObpnvNFB0XRp
cn3k085dZsBYuMFSVGVQDD3C-YqLxy2pHp5IrqcWxq0ZSEgnRNNh0G9F7yLS7e5k5ZPICF_OBjwsJk3feuZqdoBuo1reo7Xi5z0d46SEtm7Gm-U1Jg0PXUUF
8YRNUGnq6TW_FhO_0ti_SnGZQvqCS0SwUHhmwsDxXAhMJ-mqZqSWTY1v6d3huNoBclbdO6ydY96tJW87CO2GWIJUWUvVWEDZtny-YYhl64YU16GQ1j2_0_jN
uf4GoZfXHq3oP23JUpF_0HZURloFnACI1PwN4h-4lBD0YxxzwzuCS5I7OI0QpzXExt_YhxHOG8X3aUZlbhd1qxnqGbOxI2K0iWTSjx6wxrf5Vced8JF0Z8-G
aeUjbL6C704MiRhulbNy44y0aHnmqknSKIUJFHy25c40lZkAt6bdQDO0HJyB0KuLHLsg8V5KHmtsWFbHrFruL9428W6S7ymPuAPS3K_J1A181pWzYliFNr4H
0G7vk3vLbaXQOkTf2jZuC0AiEZgA-Xul7ZeL8Y39p_5GtiOwJsU060EAsE0ePdRsUAN47HFVhIy2MpfFCq1aWANWjKI-nqDPemJOO3_4ax8p34_dWAjU2M0H
Ue-uO_a2aDHa1tC-b3ovfpcWhmNaW6ArG-IRmnTyZGi8m2_N5u5FFQsRnam1fG7IdqJLgPqYSczGIZVqisrWzt7vXgVLjZt804K4LgNeKubCyIXRRe1I2XhX
CVL593nD05jy3DZuu6kJze2ecPsGo0Qu3JtaEzkG1pNnj0561e1eVB3jBEBXA8xn23mInWu2_CusxFTqFo02K4JiVWVNqU4Zq15kEqZbWVL549v-1DX2tywY
-CCTlCTJYX1hdW7NdI-7dBu-34zpm3vEW0sm1VvmGIMqNtOX-WgLsywNW_4Y6fxk1QpL6820F_wzfhDJf07sX4Rb_0Sl6DF-bS33qvsAMgsw0I80RvwQUG1I
2XkFlX2Q8dRmsFfoJ-U0Kk1BzTl7nhldLBlVEuaLi2TKJ7QGKP-KhyR2qrs0stjD_8_yKm9GvFQvLFQ4tGuUK5zwUGjFtmEA-FPmd0DAMUrKzeJnWnUJcza1
4GrFEy3qBkgBCmCCEwbaJnW_U0-gBuzuUFeEK5P0OQsM0g81AkMLq03XRDgF2-hcgSy19IxRehNMCU1c9ueeUq8ZS7XzSq_v5Z3kel0b0UGsvZqW6Y1Fg2y2
Tw--_x8jOqLNEodI07j2IxU1KWxFUXbngsylsnuVcmGGiOClX6VO6O55QWx8xh8zdeaIW3qXysa_Eg9sZzS0V8cpksnFX_wPa2VKr-D5F0DSgWKWCDt1xdy-
n_N5azl1eRscxMBoQgDn5vtk89Lw9poXlfmlFFNi_RHMO0e8MG-MFX2UiGqHgeuH3PgLEBjin-kr10pFgYz29eJv-sabc02kTb9A09vPNqIo4cl-pky9O0lA
DlI1TyAqzy6mnEaxVxMiGNaSUZszlhn4htMPllFdEnYVqcGROjhFHQoBozfUxcd-WnS0zDpwyezDrCU6hSkIUZeV-XGlwZkjnAZlXksff_EXFtSRvXyRhrLB
YQIUJeV-V3lp4hqwIcJcQJxqUNsd1xJbeRwPfybC_Ddw8a29VEIfQP9aslzOn1DF4y2alhySvhkV0_8AzKN4ffxQXUkBI9ruQWbUr7UDQEwfvTjmfOWjYQSs
nWk-wmI9ftRz-kQUsgY-akIAdbeoxTVCXlRagINRSDNe4fvsW4osuVAUMbxVzJqDGERrNTzJ-wdw8k9BU6h9pUndFDLisd_ZOrFrLb_vmM0hCUhxnUW6oFAp
4LjCfVno-5_h-mS
}

