sprite $Laptop [150x132/16z] {
pTc9RkjA30FG6Ogoy_y_V5V1jU2eZDeq4xvzFp09nRblF3VJCTukljzsVpEJxRS_sT_AXErsUpVLzFtsTgemlPNAehoiMZ-eTrFDStdStqDbPzCSeNgVGMrp
Z7TGpPDfnnXleKg36YEfbWugudC8rO91OKIIQkqri364QicWX6hLeDQhK0mggTOFQhtgR8hoX6h1DLYloXylDiSxg2RJky6VrAf5ro2oM9K7DO-iL4rFWqgv
_BslKbq6bR94bGU5USq2LVfuiNa_BrRbRo-OLLweoeEAygfarOi6jHa02DOBL3XV0m9GhFdpgidzOfAkdrRnV0qCQB1QgbH-wneWHRJOKis9EG4Z2KMRbq5r
N5zhS89kU71GKLwBzULTWQnSoDUWp5DKbmyhSnE3scacM4AbI01WPfZ9XSkWKdd_qsNr6uGHyuImcQz1DYaMXAe5Er7Cv_r1CKJ2zSIrJ-FyOA4Ob695lggQ
SmA6UPuKxQD5L8Fgi_hF2ZYFwEDnmUTWLLxVrMyGXWCs3vPnR7LvVLP_LzFmmKBydcDBvVLTBLLiAXtGwF7yj8nRc6ZsDHOwgiZ4-KWTB33-JAWALFjnGQco
9NAq60zhMgZu7HQQgd3XS8Lmu3yFyr0zWuNj5gfgL7bInw9iv3_neU9tMuG_yF-yaWl83mlZekgpSkBoxOx7ts4mysylgc-wB4nEEXztMVo9KQk-ph8uUnj9
kZkdPgNEX8hy0ilZGJ5GVsBZ4imhQsfL_t7bGGKgWilhIZIRE4BLP-L1RGpK4Svi8cbeglgkFAX0fTWC0emHonojwhCi3IgZJlCAKyHQghxh65H6vM0QKsP3
rMTnIuDAfXIUWz5fiCjAWmfK5T6UK3LSdieBL1rfqYhDOiCK4UKfbNOnbHSedJcUfs8rg9ttKLOIRJvFHOf1PHC0b2uyKSNhe3RUHP6Xga8yJyLoKDa4m6Zc
xcQbQxPKqiKjVRnSsmC0MF1Gp-jnbMJn65Jve4Y0HutcPV2eIh74e1m7n8uQgMhKgazTUL1Nb1bFA01H8qnT2QtoqbINTq18dcjqKjHe3wWYUb2HkzV0pZM2
PdIdgUkbLLwPSdd5DQ1TQZG0_Nc5QlCZbq4rhe55ZSRua_5dNSnBgrmCYcbGnpLWgX4UK1Bqps9I5NbmKFaQu5mZ62W8KzGeL9671fLdX5oZ6unMJ2hzomYj
Yj35eE8QvADE9XvOco9EDbHYK9SP7JNodyb8XOfqL67w_1gmk0PHepH5xB5TYK6TPcJv6XXuN5KJfloaj4f_l92mpww1qVYWoUGLpIPzDOyP6U8QnCZ1EvAo
FAtQxfJddMk0L1vJ2fDKVMuAI5m3YsjWJ2k32L8Ub5PjujkBk0QvF8h4e8HAc696HdSQ63KoU7tJO--YUL1N4sD6bneDrq6nLLwjYkp9b0PbZATpgL4yA66I
gjsJILu30kMWt7LvMbN_u1W1MhoQtBa6l5TU_BuoQLLXog_YCIF6ErHn3PeVnBLgzqpAtwWipOZY6lWfbKchQXFJDwhqAYvDaQeyhTgh7nQxVAEghu4seM6A
PrKblug7H0yg8ieJglGYKzMOhm5xvOrs-FykbAey8yRlqP1D58Fg1jldhlXYNdsZuX4ng6wm_pyFHIxVg01Bg2DwKFqQRm_NoF9GYlAQcIvgF1rrEt6B25Dx
Nbx701Z3f54OJudTQbTQ-H5XUawcl1Bq557UqrpfIiWytwJdfVFaylIyjWPBc5umhnHTtWlcfKqOFngBUQqihpyl_NLumRp4e5vHuxQ-l1oxzuuZJ8jgN56U
ViTPOT9NOabv-ae8qweQLvIdFuJ4nykIUOdoripBXMdDl5mCQeLhlxbXl5tCni_dDm
}

