sprite $Large_Store [225x179/16z] {
tDa5RWGn44JHQJ3S_yB1akoDr65mVjtWgV_YNByuiuiyCtStBiyrmnxFFL949Y_xx1aYyjhCCKVpY4L4jTd6xCzzBYAgpT73NOi84HbjjgSsrswkY6bJernn
RxEfpPg8QRCcOjgiYP0sQwBPVsipNQCGLvjzp1wk0OXLcmXYtIQ4MBVvyKKkuh5jklPfeejuOfjTRPA8gysXDb54yNAiDab4iw9D0B5e4q2isaGHnOlL9ecu
jzdK9eYujvckSOYsjHck_HxnrzgSQXD1hDj44TUVB4Dj4eXrcmXYtIQ1MBS985O_P0zPX8ZVsMPNcm1YtIQ2MBTvB17JPlr8umjjDhK98kvjfciSOlqdo_b4
J9ir4TJcnnzfc7ZUzQ578qQXmX0Zmz74o4GGlI969feeO0QJA23WYCNVg09YYGAoYNOh11BDYoE2Y95meZKUCNmZMbvEUobgcG9UBubEMBIsWFVTsecouweE
1L2ahO7__-9NZYXYH8VEeVDoxQEQVSVL4XivoIyxYi4RWSI_YYWw0ec8eEaetfet0Eae5ir7yTwy3jJmiUYlE8e8MmPo06zFXEWCVF0waEvyAmuyvTXatD3i
zqwRp9E-geah650D7yE8RpYdqA62rr9KNGzWInlO_OvYvec4hgzgvg8zRUnuVg-ZA8cNWONWhk4BuAtIPkRDG2AjsfBMuW6nfZczoNJEG3fAJ5sP0R7s1CgI
Y7VWWT21QLKZSta0Mzfe8LoR29buN4e7JgjQWHl4ui41dFCKrpvyeF8du6cJ4RTuqe2bN7PEHISV4r466gTLpLnQ-ziJaaIywk4JuKEOWFNXmMbLimSndb0y
GI9UaSSiWeSm0MlrMDL2mx32PW3azEHYH_6FsH90de17MLhLYhX2UlxOuYXU9rku_S53Pc1rJQiQgMlQRN0D8bHd7r431Yy1eomqprNDZDCJISHBy001nrKk
0EGbi3h6LGtL9Jsn9CGLBlRui3w08Y-0KORJgiOuq19FA9xeT1GlSFW2o35WQs1rFJYXOGIwFsbNFnBngxpSlbXS04Ish851bEUgLgDqNDxAukB_RhRqnGL7
oHl085fe65F-G1Tfy_MBNLguG38l0tDPEz3dliOJVPKsNpzyNEYykCWQcAkz6Cxvqp-OqkaeVZjR0dZK1l1eMG1FfGVmb3QKYL-SJcf09DuAcCj4Cbfb_1Xy
EefVuGMG0WZ85Z28Sr_pn-3G7U7-nHuLH-y15Da0hchrCVZdYPaNrHUNL9l0NDfV5NTsctsUvWqHdmEwJVcZPJTjzW_V80JaWq3rlEteiDla9kBZlB6GU2jW
iVU0DXWzVLJrwIRAYYUPj-wWYRy3518V7d5A6y6IkC_J1UUj4NLLVmDO2gMZEAQDhB-IsfzEBly8hDN5tW6M0X-9fzr6PFsLr3wl_2imrXP_1rZ6EQtMWDo0
YoRkNUoWyXbWdzCrS6wYzTtc4pyeoZocJm7Jd2w0B8sOqqPQseWculx5_bZ8FWDCSxe45bAVqqPU_w08UuUFX4FuZq0_GzJ_1aHyvJs_Mydv1qMSclXZ7WuN
Xv0sV2YzI8R_LNq7c8zYjG1k_w3epzd2JQW_zt7tvNwO-0f8C4vvcjD6VvmsCard0D64-cCUf0o5nPmEmFWqc8O_b_H9Zlxq1qLubItzhM73bu3BEGsWXezW
uexMJPy_oO6-V9F2kzb23o49W4rU1ivpQXEm_pAXa5QZuAfFQQFfJMf9XAoo1VWv3u0qO2v9Svg1r83jXqFqg6bEHTFdDYjYvl6GBGBPR5y6hkUq0Qa3Zn9t
n8CKIkbDQcuY5jbIXcoHxVPrO2xsDASlWOMi6WT5fwEu_ldY8biQy55xxSl0zPoAlmGMDdE9Bn2HvdJwYZztSUQ1KxRiy21hOEjCcjC1oFm4Qe4x-55vJWtd
psriEefpjiHYjfajuPitcNVdj0CFoWbOIDs224r4VRv9mURFRQPtFahPycyyIgPLsAXu0CVe8DOOLDV304YUKnk-uazfCxOlW2bRFkdBnMbE0pXiOW6CF1Ky
Ikjy59z06Zu7dxA5UlZy_tavRAeTGEOda08O1NV3KQBZQcDc67w-oC-qITdo06AF1onEttjpwWb80v25pRMbYfw8Mk26yrVyrezYwrxA5dnXElESpi1yNq0U
NHI8ZjCTAQIdh_Yj7yKuVEteKSgMxVQ1ouzAV09Y0XAaH9vAFEcjxoba3ru3nfKnPalyoEMhxOiYIS3q7MX4XvGc2I0DG2AuWpY0_PLaaItRF2uRnNu60ldd
iW6CaXaOVuF7RGbOUy8LbBFb--sB8l40FdWDo0r80n0pi6KBYUivRRY28prP07oRbudcvjKO7SWDI7y1dhA5pEMKDXKSGfOzNlQLVohc8cxIW1m5fH586JYk
Qd0B80SmPSktsvSh0X-0PY0t84t0lAg9EnDp0uOG8X--slUBtVK9xBjq04yN1qylXlPCcvPL5P4jLsbVpnkJ1WIaDqXQshGjZeTjDArgwi80Qch3nw_s_Rpn
1n01v0Qa3ZmOquVUHgTLpGoG0tYDqvSB_kXA0Ba1gGEf0tjP0_Qq4JUfyX4UbyyNQJK4a4TWMrCpiBgbLOtKwpNR5zNU7JAGMMm2zgEOLhLwNLv_nnLDSJe3
SzgWfqsznDsmdbFLd3O1v03cid5LksBxygLedDCcpXfUVOkAqoPpqVRbEKrfO-t__aMTNWphLTkNvpG3EG5JzHV3Ue6h_VtbhQUDSGBErLuCwtNRbz_uNNlQ
w1l06YjxlT3LlYwssAcn1gRjJUgrsvV3He6tWK6iD-55QNLv0e7wHbtjRbWNQpLfG6m0Bzs-AF5uLSHHjWLSju_BVroarQszPfZydNYhzaMnrmPiFs7O1uBp
rNwD4hS0nayNbtMtzaMnkWBonaziwmMkzktbBO1fJjy60jThNxuKWx2UqtjDPxuKevPpUjMhVLtl_yIsthHzKK5Qp-d6rNwr8LtFwGtRbxysNS_fBUw6TPYk
vtIZVVUQqtlpecGrfnjN-wtcr6_VlYYs5tFg6rVxhURKxzk-N3JDQGVcxd6vPx7FS-hhzjr_JdtZQh_HfUYY6-sxrvpUdxU-57rzDzn_JlstjIyAFWDHVbLf
0lwQzkNbpTTlxVUVK_-TxOiY3I2NNrli7ktxlINVuVqF
}

