sprite $Layer_2_Switch [150x112/16z] {
pPO9ZW8n30IPT3Bm_m_l6QttCAMWjZRq0vXIkh1zAKjhbwTB6sFquxcO3esFF1MNnbVqJEMDI7kAyaOaQjmkL9A-NQWysYaKf6qgh_zwdXFqsYHKR-hdkRd6
zfVfBS2rGIXDgDx7zTnKuz7lC4skBNebGaKsrTZwJoPfGX5N-qUcA2-oGQz3nCJFrNS9PUXLAXHd67fPqo2oGQ-3ojjLOmCcYYGPNEuqY6YcpIZqCceqX59B
8cC9ETE0iGHwUKBnD60kM4BrGh5M0ILZIZZhXTzBdM-SUg6OIK45qwjwlQIEVPMdYMSl8Pu6-VULFvJKUqkeM2-_F2NUw8TCIO56ZGcJxikJblSPPLGy9TQd
WGJoH9HoBjyuN2C8jL3UxsTLJq9JObqevKp2GlrRWjUBMjEoKEktH0EzUBq4YDQ4UloMEBb6PKpnctU_hoZq8IonNZoXOXecGi44i6y9NY-QA22qKYQ-9Hej
eMozz4mRbiUz9Su_DMhypjtVaWmcmIqnVaVdTH1NY-WZAsLr6Br_gPBlwxpTY2lxzs0UlYMIRtzGtM9iH18PaYAzMo9dcbGvLqwLj6ZS4kbZ1DMz6ZL1CXRZ
bX0nJQgPh4Q8VKl0ru8Az4eZ6RS4C0LLpiLOnYsHbfTIWLvPrcy9hJ41rNgDCGtpx-knyfXglSRs4P17wqn4nLmv5ShpW51CnNePjmGpCHNhPTyIp0HKo9LJ
wJDL3yLKnYrXCJ4LBw6MH6vvJCLwmItXCZ4LSqqg6K8vLAoNCGqSAgxHc0O6bS65J3OLSndb6LIkNaRjwW1YrUZyHTgbNHskkeUAwBYyHS5br5Z8D0CrBYoX
KgPsYHp3rSiNAXug8aklwl8YkZbwrPPNLwCz3UxbE1skIg6gz7A5udH3hrAXVBsAX68kiqQ_F5-l_s1obf0lLBrUZmi53rKt9VpowhaC9gz6pbalLCKIgdYe
-XehcEgdH4LvzNeLhfV29LHHNhrU5KprUbK8LQyNGvNJH1hLM55UlLwxcBX656eRrww7uXfT9ZyzuUBoTjLOirwgRvnTvR5UkvXu2K5v6_MgM2_rImZAswLN
K0NJveoW0g7sw0NbRQmHcFQbihnN
}

