sprite $MAS_s3500 [150x129/16z] {
pPa9SkCm30H53Ydw_n_UIzu4jZGAM6uVK-VURKmlY4eMAgMfB9yMzJ_HPp7LVatz7ARI-dS-fSRMRwBo4KBjeeyGQf_wPg5CMlcKyW2zSAPMr_NjDTQxybJL
-dWlLpbW-fi-0BsmyjJ-vxv6lMaRD4aj1D0BAYzchrTv7rFCEe0j0GWL0kW529Nagcygp-Zrr2tH4kK1Ug520NhXGlbqgnV_v6MOj6LMBxuyNLE_ewCQookP
wa5ajmHVNXxBFKBrXKB9K9aRXoqlZwQJBT5Uk0saQgYCNdnvVb1NE94tJaamgKgsFBKxhRnUf517ev12RuRAF4A8K3hoHZS_fnsrrmiHIZfZKlW9GJUElrVy
l--7bxXn4bpACrNPuN4tZXTAofINPz8MS-CaXLAiAY5KyfQeHgzaUTeeaaBbRmcZLrAewoTp_txSuJDSibl2boUr6ogT2As4K9A_9GoN4If-J9qAxQ4ysa_R
I_qsaXc-4JgRirlY7g6iVPSMKaC8faCFzmINiUSwff8Pb_7ChDuzrT5OBfVBCEDo_tjSeeVstLJGoZ7zfJ9SXifm9T_jIEMPhbH7DVOzbRPOACiKVrAXOiEq
KHcky5RC2VtZy6G75QbyZJxpXs2CPzgeGjOPBYalL8x9K1czx6mqVGWsBvIXSboMojyIy-LPAg-NzyZFHDDCdYfVuqPoTakeAbcUevhdsb1E3z4iawUQrKl9
RPylprFbzHBEvAdoDKQe95g2oL2bkUek4Z0eGsMuShS4nEIfl5x-bW2O35MoHWKGKYXFDR-z8A4yLRv6dYbFvMySYibJqJLweJ0gpmKDocC1Ud5CgajPyroc
HdXEMfQbgez7QkoCKF4FjzAQr1xZOWOL_xIkN_zS0RqefgRQ-vKBgf5WglNhOMk4Ne-_JQfreuAueF8Y5Q0Nn1If0BqGfaZrU8s0KAgHQiUrJd2HWp9KW5u0
Kw02z8AO8XMW5o2KeuerJd21W_9Kytgj25EayboJDRRvvyMaRBzEw3KB9GkrVSyBgN40vMrCMsedk0R3L9Ql2D1h44BL9QO-hjSWoWjXQXmuawyn_mWDIgWy
LwB60GgrO7eDhZnGhq4neNeDI2XMhy4BvVLAdz03A8_NQpoll0SUeK4o-KnkYJ5_hyHWUXagG2XEhm6Kn-irx3R8C_5w3Lmed_m9FG2XIBr6e0A4GlKQW52y
NYDH7f_oWru3OEBr8eJYzMg0K7oDRQ8ydijGCOFYQoIO-2r1bCVhHJ3nMu8eZzUBOEBr8ihZzIAOUBs8ydYz22PUBw8yNY-2YTUBA8_NYs3YQmJB-mq
}

