sprite $MAS_s3500_controller [150x129/16z] {
pDY9cjiu30FWCG7GUVyNtYDq54vHRQ9Pfmbwttz9IFOtNsTb8xQlJmiawSDSeIFnGIRgdayP5wKUVe8Bik0Z2kM9JodKnwmHifZhpIP6fjNhtSj3WDhJwlLk
4qbgjpM-SNdWBPdcUijjG80jvegtBQ_d3VNQwClpfDNh3OMo-1gn_S52EMfUhpSLoklr-ZK-AjHQlIBEA3cMJFDwjJCJ9nTA0FXSb5wl3RxIrnUgWehNAoGH
p7AzVdau4lVWrpMI4e48A7--nWLJX0UzNcKIG4Q0BDS9omF85LQ_9Sf4aEJXhNgzk51m5OTBPGARYiow-5z-6w3Pm95cYa1z9bVNYEdZPM5Uw2RLIG3GVv5L
--tyvRa9-AxIxUHLRhy6WdZsbjYUC260wPnmVBURW00GWmM2GLoZIRqM2zL6uOK2oIXLBrG0LovGNpDu8ArUQuNocT2NT_yHHg5OwoeN018n1iThh5vhXGB-
ouJs4-WdZonFkSYnK5QiNailm6QQ3s-KdEokGr8cjA9MlNvMg0eU36yi3n5e8OcEl2V2NDCNu2TcCZS9XDtsFVxSb2G-AXJwl_QmK3rvFFiGWPu-AQBbZkAZ
Gc4e_D_tuVNavRBNp7_frVsl1i3UgpeS96UtmVSHJ__zTeUxwfza_NKD5OUhnjE61r87YjFtbQx2fD2sObDTQertL56Y_w26tqpaj51zGzta0JbNTTVT180D
5NTJfMw35c3-1W1ECrVTwaLKWgW1js6HtKIcB6onrv9rLQiNG13Z21LhdBoM6l3KrL6JSSrwfhr4VOte2q2Ltqra3NZ6GbZmmDJiQQv-WeRUJEAnU8kfPgxv
SrlKs6Ah5mamWZXGRYB6VyJYAbGU3AhFmDTu62Bu-q7LSUj_mbamo2n-zIipfSaQ8uR9K23wW2ryFh3zIghPvCLT4Ryr4GG9N5fonGLC2rLHIfbAaLulW9Cv
iMzmNgz91c7stERLbFLNUhqS1PP9RODJ5-SRmuCNqSmnBtFvya0Ai5cjrAielhokkfhAvckqsm3auMgpMbnZITpKDrYicutiu_AIbeTGQ_kggoZmGlMsbsdO
Qesc6Wz80I20DjQrUk6PspvJMJQLhRcwgJpYqVOK6sMbNZ3J_8FRtJRgDKpD8nB89AUgjNU9-RZsTXBxk5X1yn2WacogHLTOC74rKxybI59e7ggMvoftdV0k
eRsVn9fNxgI4vY68ChdANMUyI-JUJs8z7DKz5AfGfbfQ8nmoZwJSrMy9IIWF240WbAIfrbnSY2fxdSHXGtbkhXHDjRx65LCblzyIjDl0LAzogT9ScMKJ805i
jy54jLgl1LHp7TKY0PAsF5ETx9A5v3Y9hBRJJCOwSusptwkzRWUG0FOaFOYlBPztfImhfdwhSjm65cnVMr3xoMjqb3ySHw4i4ZSI-9-kXK4DLp8r7pFgfcQU
Lg_dbgoScmWStu0dhN7z_d1JgNJ26ZKPrA99m53zNRjzs5OGmq0GnO_RVyMEb-Wao7p72WRSWR88LvDfQLIX0deHfae5z79C2nM8qGXLgMgC3IxHg4grnDZG
2p1LgihLYl7U2AzIzVJgG5McIjNKYuLNgRfwFI5JfQer7QCGQgdhSZ4ez5ADkbr_VQG-Fmb5CLq-xr6l5UQVar0Oqr8NeLU4KDVwkAAlLrIZwhk1fbxHJ4kC
FRt2cHQkUqUlT8IwNISUWyrCGe6DSdg5CKczSWfJT_GA4Khh5TweiLxZDKu0auynW_2QJ4iDrpXZAY5KhUarJa1uNgy09gzNPjOhWt9wPM81F2YeLq1uKgyi
L829wnKmlNYzSbAZUckS02Qlbs3oUjs5K7wK48toCGec_r6zmKJgvnY5K5ulqIYlbs3oUedrYjTBDChh9PYyNeB9woL60x_64OtoUWachvTWyde9eRnUaEaL
}

