sprite $Network_cloud_open [150x78/16z] {
pPg9akiw24JLq0tw_n--zmwUUbcSSJdBqt1gpNuih3OfF3u8O6PUc04OlmtCkSSDQ6AqD_j59KL45X4XtOejTl9DIAHZgnRWJiNC35s9OQsJVlX5k79cNBmM
EhcD8pnAR5qT_UJnUyxGvyg8B-mBxBF7IDeuXsacD-pDZUMym_qgVVovymIQmSB_d_If-D7JH-sPUbchbAJOCaSHEMTcX7W7nhDencjQvXKzXjtJT_5JKckq
p7MqIvoN-C5u1JwlPMVUNV6ZbtUIffwwQCFF7hzh-dYLoBjzSuZvM89DdMueO1YBoE2Enxzk6CjGIj9URDpZMDtvA78NWdSMEwTrVjNfwCwh0yQhLiT68xx4
r6kv2l0_hz6AykgdDM96HosRsL8hMsgDMLhMheX1agCPFdMrM8RHWyZBOj7xr50aKLB4w4B6TmbRRKRbPkNgPEMp8WlHAY5iiv98Z3PWLWMJ_QpWsIjCBQk0
qS_AHaIl2ZBeevrLY2YhJic0B1bbgqRBmx-pj5C9mqSnez5Y6SU6ij5YuHAciMdrWbCalPjM93jgPKijP5OHhLqHnOPUCOCDlNocDYz7m-KgCUjZPkLrCJEW
ZPTsiyhLUh17qzZW7bieTJJOkiN7Aknei9LtPbZaPEC8kABKzEvYsUciWH7dtiRCzyuidGr1EEsPY-GxgU_dRYw2ESjyYPRpXWSX29WvASFpBSMBHJIIZtRq
1NuXsYXUqd8yBULZE6DcbDeUAMZZ9H0p-BoNaNOx3io8q3Vn1HtlJN_uf1Ty_rwuVxG3iCnunWjE-hfXsPduWQsx740NhuFuWJb9-IZMUXMtTwi2C7TogLC1
PePuY6XZEQQSFvfTqcSzy38BIToe_563VxgmIkROvDm-AVGN
}

