sprite $Network_wall_jack [61x150/16z] {
xTG5KaKn58FXwcdtlsBoD5Fq9ZWqsDWtdFzPIZMzOxqLs-RUVLw0mRE5Mx-i-jYy_KgjspEGpGkbdbu1B4vitbvRCpWnj7axiCM9d-VvCBRIYQcvcWzX8vtu
PLuEO2ETs4WdTcu7FiHREO2Lz1LhJnknaKvif1CxwS2Y9YSsqeaDJcoa4nlfn0ulm2wF3cpoc27XjbWHOxJ4AX_Jm-2mDcwmVmLllF766s_SUtTnBT3W9Ywr
ayluoasCDUWmS6rd7dCuU8xw3Znd-1ZhNuCt1di7BdNu66iMXhvm3uDRcDp3v17DnD2Vyj6xySORRxnnYtVWCaUtSSAlOUCu_p5nE_yTOU4oBnlTmEcAmGtS
hXOB6QSS_ESXOgm6ULSn-2INSSgTF4IifHDpPKaNCT87kOgnHXugNcyF5Q-ygtXDb_6QBkCrNSKhxo9URnygnZfvY7XzluokOl2nS0slpxgCruyv6Q_fps0b
NS1CvmJCT0CptS9Cjp3J3Smr4vFxEEKWDbQ2s5WZTbOV
}

