sprite $Printer [150x125/16z] {
pTi7YkHA48HXgPIcxd_YHKkfDGITGn8JRV9vkryh_h6m6t6x7VlsRMVkxkExJ8Ul-oBNC7_SjyouBvF09HuFN5zc4kIb7e-VKMzIklJZVKLUmnitlcKyYu_D
M0TbPYbmIOEo_vSPz8pweEowd8HB7HIYp7FEv6RK1tMVppcflFJZ8OkOKJqUNanqkOqFcP25URtvlK7Dci6u-A0GXPUBHUIb7WzPR5vw4xBGTNnYF6GHsMjD
UBvOH5xoyV2zgJOlSnA5B2el_NZuRakK5uw7A9urOKQfYMVnUON01EyVQbTRDJDaA6JnUQtNep4X2_xd_HdNwv6Wa8MclWlUNAGiDFNpWl-3mELG5FCD07ZQ
4bRreFepmfkBnELWQhjGfSqhdfi2ycgeb7dvqqjyrKT3LRXK9eydM-mDbIIlWdJzBWBYwghglFZnrWIHFrwqMKEboClBecP0MsODbI8lBo_oMl4s4IeYhyep
u_gJ-vKQeMBoyXAr_ZznFtypGiNavULbCHwdgbtzyR8OZrVLUVNVQovCudYygiwh_uQNrv-1gQdYPon1i2AO6YhULHL-BHyJngDL_Royl7ZC3YQ92lFg7uwd
L-6CUFMAO29KQbV0U8IApGilFExPm4Ie97b5cDdj-jKKqtKgd15DvpLGdfDG4Qwu3HsJGeKkrhJ6co8LNk1uVLDEGaNCk4pTyGWLvI9CGbMTLpSeKiK_haPG
f8ftDSVZLRpBobicKDakLA6h6HIgpZEf2XzNVpnyn4T3HRiOqxeXK-6LgcXynBBzlQee7nIuNgIYneCPzIh6X2wzYWeAyvAhkA3GfLQHu-6DrwdoBr_b3gsA
3mhpaghuyT3bALBfJ6ws3Oqh5ECjavrlYYDLgYHDYBBjl2FLAdwyItMUfrp5c-pOrer8bOeF2b6G5wkIF2ZuPCjIfk9DOyF3l7YLpeHvyQfqjd8uo8jKIOF2
l6YLD2WyvrMaoS1KvCMfqjNZOLw4IXWKdnUgD44fymhJ12NEAoJZoVFAOCOZppWNRzBdbOeFB_gyCWH1wVBA11SndZwlC7-uM9C-h_ZvTLSmGUdpmgy7CvYW
z7dXryuPn7YAl525BkB3YoOlLC6Cn7ZQlABu6LQ4YNNzfi8PYQ3Oi_RtHPq8IfSNgexTbueOJvPNWEdwDvmRZxyZAzN5E4uLOPBb5M1QPxPzu1nKWeQKUON0
fCyh1Ey0z7c5mAJFAmJZoM-uz47z0m
}

