sprite $RAP5 [150x126/16z] {
p9Q7RiGm34EZOSd__yFTxYA4-C8Sx8VPOZrGFCO7XvZhiHlQtd3PoydR9xQFatZxOPSpMlk3wnQ50amsEjukPnHh5Rf3eH2NbMjGOx93eH3TfL0BLyBQD2ux
50gnBGg5w892hJ-ZjekOx50en1OSRzLAMADnsUXu4Moz-3L00kgrl50vqe9whInKV4OL2VLQLgW_GIMi5rKekbCP8xLlT4sXXWganjPBsPn-1TLkgfSw_ylx
Uq30YECHGKL2QimRnnhzouEc4nyXA1GzdICeuet35sgeG6erHXIAcCu8yWbjxOwWu0_YZSCTByhfv9xGulHaudJEO_ST3tzcC9spkCc1PD119KpdDFwEebVl
3tlX2CIreFmBKx1w8wzQuNJEcVoLUiC4h1xtAfy5DNw22LhrZ4iFO4XjsWXHi9hqmWzSZ7ynIbYl_aDUVm17CafunlwRqxWoYkcadD2h3wRE6CLqSavunkop
Nf4udLnEjLS4U9rEv_a1dSAa9tXbb47XTD9EY9byX1DzmcjsEft4LAM_StB6Z78w4TvfMFKyyOAWoWFIJiEgyCeucSud1JMiHZZbIk1qFZ4eis5rUaRuzXLI
V4wj-x2glQBwu21tE7b66rP_lEepWjBTKfPfXxkAGZWnKo-4TzBeJOxZyo7VGAAkLmtlP1blDfzMOkvnxXNFidfjlanqNDM186gx5kV_V_WjWnkQ6pJ6CqYv
hItAUaHL-c2WZO5A2IgIf4uG4maz2pM8t1guKOcjKY9jBTNhVNwx3VfEfTT69PEaVrEltsw3vg2gtMrGYVUukf-ZGju6PQVwOgsnhA_hfPin_g9GdQLiL7Oh
jNvvqDweCjTwZEjCO-HQWkhrOXtFqhQFhtR_qPRu6HDQ4yfEvV4y3Ke-Oh78lY2Xc1-6jrEXjnYOhJ9xnDVryhnUFzABWwg-WWfMQxLmwCs3Zf7ZMhrMcTJT
oaubZwUt1wLiE2D6nxznKKAhsu1Vss2ZQgMKjXUgDKYiHtfsF5wK4DSl5AFYwXsrHg6-o2o1qIhdsfFstNejC8rnAmULuacrrhQM0vJKRSb7lLOajAmNjJPs
L7LhaQb6U18ng2pRFcg_8A6kLRtiLAttDeRcO1800s6SuofvHK9Tqi8sw6ex5Ji7wX4UiL4rMPOIbnSaD1R4xMrGImsggdXQKNBYQqoNWfvn9EksX89ATmhL
Unim5ckfvsqW6sEyBJ6-NQPx4iexVde3t5bAKALLpWWFWqe6DWsre-kMTLj2Lfg9XrqEAbqKQgEYYQ0ABbjsrqq9JMIOmsDGLGsYq0jooHanbXXsQw3TbP3-
d4iczEwTYY-Tz68T9SSUeye-TUT9DNEMqDADLhxPH53LpdEXSiazOfGPJBbUToLaNSoVfnVLib7LMafzqmiDf49vIp5JnPQuAw6kgydAwswbR5JzvLhVzJ8o
i-A22MzKfR9R4mdDi7G-3WTLvuLU8ZEajH1KUQfzNqAUK74_fBTJeQIzvOPC3wP8iRnFYwNbgOJwBIg-s4vwaItYo0m2m2D5bgj1xpSbv1jKjHjdlKWoa0eb
m7t7hELwwbq9zHjKZF1oeIApO7CyetQDj22X6PNLIgqNUe77DeX2nJCetyvSGkfJgjTBDUc5kUIqD5QLuXcMwTIvX6PK_LoeN7ADaaDxoHtXpRZIqhey2NrF
zNQ_OY5b1W4wKfo4jo0XSKwL2wMi5uYngkRXBKg8trATzG9blR37dz6gCuvb2Nr3bJOK49afwGK6v5RMfseY8LvJXLxoJPHCAka5ZaAjJ_Fa9CGBgj2BR057
eQYa5tRMyiEPdOJUgN9ufB9UA5W6rWkrBg44XhVx5MMzq1ubdnTgFdKc8GRLst7ub9c7SRXUg7K97LpSz99ABdey3ZZJhEMXmKn2717YLF8kW4nwGVS2qug4
SfxEjSS8Jyfw8I4RUA1GSmdvB26Rn2WKbVL2cnZFe3m_oFz6NqXe58hAUh6YzWk5Ub928peAifZq0Ys4zxI4W9GParxWXV0Ubj0vCyOsM0llUGablK2og9bU
dg_NkuIINc03q6mRF5-lTmc1TjOBjBuDdfUG1MMzm8k5Ubv28y5pYiyohP-4WegoTEZb0rDzNbfRPg12BnyQE9-4Hg6es50V6nmIaZoC4-5zRYf3Glau_Fb1
BAs9NZx05LGVO9f8w1FRO2uX6kLlcmV2-nS
}

