sprite $RAP_ABG_Hybrid [106x157/16z] {
xDG7WWGX24JH0QhG-rzu8vDTRJfjwdy0d_aqJc2dVJAux2In_4dfa0xfa0v9p9eZaaNNbPHiZIW4iBRaJQd0-KtI8HsIc-ma5L8tbyJyGo9aKqcC38aqsKvI
y2gzMnj90fA4mnsCT0t9w7Q_SU_XNY9bkGG0jsw4ZtZD5biEzxi3kbgypvPAF4i23j9L936EWooNmabQUKd1oUa2gO2fTBx4P905qkQMebob3RTGZ4nAUIkS
X3H_2vNl8NNtybOuUIc_XUQjFpiVJAKleHP62noQlYTzgLRdh63s2PXf90Ef5f-XQ3FfINaBmQGirAWapoHjcPSpvHadJw6MZ0NL-TAL6bisoP6lf7jh-O9w
KfsqXR29Jbko05fMNX89gHK261uNWA7JanJmsh1Q46m0TIKZo8PLF2c932KIG1bPw4iYOydf9C31SRtMQYPeakem3FviIU7-9tvBo1WwWwgX0C_Q6p-I4yMr
iDSvJl9OKsjIj_28DP5m0fHa6lSwgf4qxJBs6K4Wqf_khInqB4wQl7582jQzjkeIPTh5YMGvJ4WDOTphcFKFUT2kXLNu14Bd23mc3KLbuK6x5kr4UOwGaWZm
UFeB3ipGLh8srZ8jFjyW2G3id9dgg0xhr9-xgvPVaMo3YAu8vPxPlgqJrsvnMdk5-jWWW9GmaQo5NHUfTX2s90uusXi7bdkMvInisXLCWmW1P8UnDDbs5QPs
yYnAd3did4xGWB4qkM9JeTh8-6KInQC6zGu94Bg5SqRuTjLVQdrtBOO4RSPrMOsSEPwb_KvMwnOUavBO6STX71aNdkQRb-7atdu7YSCuShKmhptHLujYPP2S
IRM3Y860h76-WhE56ue_8wxZrYw9lC2m5XQBSyILgXCDyc6eLbjCMbcS8muIL0twgg2Azpfs9SqHr_yKvxiARDdKaIJ5AUACSL-tg-qjBECwh3YtMPgNOHT1
0LI7vMElY4wvYxKtXBgguZp2-c4X1eAytI1_TdKWERf4tUNucRf9geZ3Cmtoiwu0rTdmKWqBXtbHrYRPbgf6vcrJGshJJiqzP8_B1tRNjhAXkh98P89KaPLt
sqMCzLYt7vFqnC3TMviHgpXptqNZBM5LdTFmsuRlkkvmq3bvegttM2d3iIpbTw3blygBt-zy9dFElLf5khIaQf7ARL09jNOJb9GRA2_RO57vznFeGyR_hiSN
EwCjIpDt0UsgzcOiY-Ax75iM_yL4hupOtu7_Pf84NBeY7tbhwHolUEM4N0vBV1IJAX4Pex8aAX_Zh5TaXe_NvpXAh_SPLh3BYHlVa_b1Hcw2FdEAvRCu91fM
i289fqCscurNclTq12gIBeLiy7Fc4J6j9Mrt4DTFZN0JVoyWr_q1gZYzrEBYxEOJZvhgbNmfsFkOeeqwUL-jvvA4V4t-to4hnWkOLlDoh_eGyIY71_DovC3H
i-ByiDmhHvQxM_2prvdWJMcWGfyk5kWD2xF1fawQNHs_3um-7Ij2bPy5rNT4tR6la0qYz2k5ut2dEYP1LbROYzaixvoSLaRLnLLMBEBdkWLLdEUg4e_eHKdF
Sqh3Irdknr-994vH8ZAp9kiNZvXzlERpk4gUkMXPO5nBS4u3SnF7BA3sSNoLbDTMP-pqDCGKMLvNIi9faAHLKxWKZSwoA1fPFXrpMLhup4jp0HD3Ri3iXGz6
0DwKYMKu9sq-SPty_7N6NKvPU3X7HU3Xy0jKkaPLfUp3mrL2H_LEo0JuGfG7R6uc0AILadbmqC0hrxVF772RnzYMAZ--yhj61-iMLOZsXqY7Kbu5vGP2pSkx
fo9Wm-5Ynx6BYcXpzgLS6gQkdnhAhxihveKWuRtHYtasH6vb4dI2bNmapASCDHZnaSXpxwgEoYSydUKInnkJ0N8BsNVZjOI-D2kJUyWJb7y1
}

