sprite $Remote_AP [137x150/16z] {
xPhfylgu3aHjgxlD-p_n5FcfIAo0W3Z3dm-SUsVVJaKjkMSfnsZMQla26W3x1X4ZoAyG4QIVo4_a9_8oFv5QwrU8L03j6qIC0Bv2H11_8Z-HdyZh_4Hg_GgH
Qa1xAW91gl_xtoZWcKW5GTY_20H7Mm4Wla2a4-hyYVn4VY8_aK1wpxz0f88GsnsH-bcHHbpPYtIqpufqWfrtH4Yq3uleWGXfzH-ADAuYfFqhaGfgAqAqVo9Y
P10XKJykqiXHnB7wKP56P_bLuXRxd4W5_u2BW5lGFYHYT70J0PtperAXtJsFSm2WnIs8d1eLmwDxpi74eNF-VApZuJrVsMcShsB9FKyuFogMtFFNiPD5uZr_
7RHpHIh26VtSV2ovvszYzIIHHXuHaKw9YYNt_81AcnP1Si-VEqZJKR4xzxo7UvvOh0uAKPaMeTzGl28IV1mxHuHmdbayLa6R5N4IYrHbeakQWaX2EXHDNPKA
9YA79-EqDpHuH4IwepBn01aPH2Q-X0u_G8qy9aBjVFhn1wY2pbltlEV1k4zxIIFSyucLJQX9E1m0BulqEy7GH45eyN81qlCxUcGo-Vv8euapjx8v060x5Ltw
NcNkUEN0iHf5BgvoP6MTN0KtI6neDOXSLUYSlB98iHP4hamTqrGYLmaYoNoobPsnY55naQYIhoo3pr4BZqeGUHOLtPtCfCOw7ru6DBkoI4ZdG_N1f2kVpCHG
ylceArL9Wd6YXxMgowLBbr7bmFMOqh2sY5nLUenAlh8dVuxMNEIIpgThLyNErd2H-oh9PFPCQ0IHB2hFdvM9S0mYJZAVN6NcSqIHF2hvApkbuTJMBxaAdwhC
QJYrL4QLtIhdp8J3iTPgDS37aqGbO_vpwD9QnHMcyybLfZNOEwyY9AZdAgU9M4p7HTR-H2W0qB6eJ7uEB06vYXX9aOlAaVdCQP3DgTGYmgDHcLbP4XifYRhz
AVLsL2R2qLODas5pg20YlZVFFihHps5eAwHdn5Lq92e7DSmsGx5M2pRNMqUYyfw64pHQAuLQAuV8lKfU4Du91zLscD2QaQZmkOYIrZzvVoagxqm5_Ou8kIon
X6OU4P7gSXCAU3gVjpIignKN6QS2af0rU5YrVUZrIbJqXeQwbU8YSIga6Ls4LEShgHr4-FBbwAWbY1XTWx15n2Hgky93QhEh8f8lxWhBWa8uN6CHiL93FPVS
ALrb5o4pZI1YYk6Gx0_fEhegqHt6EH7YGvLE9zTOHTf5CHpu4u5WpLqzgqDgau8m7BN7uR2jYE2_m3KSYuXeTXLn5PBQH6L8xRvBSk3XvN0HePGwN0uFXyme
s4QaLCQFeQmWC71tPKaNkLnGD-4GISy612xJGRdHDAHM2uyA0dU4gQYZDBf8jp4SSWy8oyR4_tR6fF5ZI7J4KKKFJ5o3dRMi8fjmW2Jm9yBb9mGfSn6dMbZX
M13oCWtNQ50hPICImm6wnXK9nb74ep8yF9B2gKrCcWChBX8kXuS3D4ZhT5nanDOLJWk2deeqSNnM93-aa61QfsCaoXxpxSmBGdygmcvXAh8_I5zT-IzxLYEL
OOMrIUqjAaf5ri60FXNOcb5VNVbqIYIgQ9sJGa58HOXQDfV3F1oyXS9_giMhbWIJqeAGYrpwxbcnHGJYzhF8fv9YFIq8gGYtuRXbr2YQZQlh6YaLuyCJJcqY
4bTMxg7RPx4OZfoy882HHqrGjWc7v9TLBAzZyU6Ht0nN7eZ4SCWCuhgweA_i6rIBAopvZrmbYiJEuPaarkc0a9LtgRXJ42JUCHd38T7MvmGOLhSSeSKL7clj
IfmARGq7uC-BNuvZsF3mn880Ed4gdadNeJ7SymDKf0N1LM8Jf1cxBV3MWQnCaHS4DubDa9ldn7-PPPAy8BZANpWasFYSoCMy4SvZVPzQqbL4UXCamdCYdqxK
c8yArMD1400F1n2Qe6mY77b1qFs2u4qGeGdAx_cvD8dK_OBWzug2QREwcbdPl23eRa7ma2esGRd6wLICAxn04g49qauEHruGrZaXD44kGkN_fN5V401fkxfC
xlbvL8ihBD5NLsiJ_0GLOONXgykPntww8BW8vQ4LQ_aWRVlmm9iWl7Dy5gor5ju4CRUoymN1LuP2-JSqQhsiarEPl_ekGarhp1S49FVyir4HoZVGC36L_m
}

