sprite $Router [150x109/16z] {
nTk9agiu58DXMv89x__4mznDIHadLX7J_ypTK-JZ77e9NLqkLIkEIEfF975KoqzK0KhjVIJgVI2g1McvhSAWA5bsi-X-MMNxIiJD96eIzfM9GNFh0TWcGrrB
iebDWKjORce4v5yJrtfJwcfOP_BU_CVfiDZab8nBDK2fvSjpNEB2l0dyazeH_mPmtiLl3ag4-xr7k6nSwQ34DjCVbQOGZAzwzVDGe9hTUxJ5gku0w5ofQkwG
TNPxFWQ_f1ACccNXpINDM1KV31Ee_lHILJnuV4OvsXMfyhF31AftCL059bS3b0yAfgh-WafOpIKdAvsffE6e8vRQftniFLDFLGIpvJbDxczypiIhIbO134tz
U_dQtFGQ-Vna_dlpbItFE_J-KXTV7VhTwr3PBJtP8LeGyPAc7XC5Zog8cOejJFceSfLQ6jwDIkqi1HkyCAmwlAu7faGrTkcDThH04MSg8b8vdPwVnYlK-M75
NiK-DHSzJX3jwbOuUkbfrPA4Do-qIpqttQ4Qlz2k6BtmNQyQlz06Ho_62PxNidWUu3UixghZy8QAXaSBcZgx_l9wPauzes8LyxieqkWVTHvZ5NJU46LLFqjY
KAmQD5vW4rlhN7U-3SecHmrsV9FAonkh_APwWygcBepkTfwfnfTi_a31o-kgRpu_dxbmDNc1A_fYHjssuPlEpFEffO-oIYrMDN4mn5XrVY2rOQhResKfL54j
JRNjMyoAL2rFTTl3OJ7Te6AK3jKUcW9LxhBgaIzFJVXqdu7oROOCfThsVTy2av-4pohgw4Mbbx4nKstxvB3w9n27zw_y8ALhr1_LrB1uTdGDL6mkTCcgKrPm
PAicfZoZQhzKZ-3sVQvgcdR9ip9hubG3LRv6MMNMnF42LVx515bbLcuQg_AP6oMqtQo90mMg-8i9ichRpPem1Qfqz7ArxHzPQfTLZXCeLUtFh2tuZ35LsSNs
7gNAlMDDHhe_AjAf1UcrKlVN7XS--mFS5HHBCIWUbm2E_Zf9lMhBMOw01dyNcrmjXPtg4RX4KDynkL9AxLMP2-0tbkTOZbgdCclMfUicXtA4JfMulBRho_Ee
ZhPUzSSr3HE1woQFwWW3LUO2Bv8yAW-hK-MBl6xog8xgGEM1tKNog8vqgZBhQ2t9rUAsZwgZjIJlpptUgjmwaL4E7rLkaSWNbUE4AfOfYxLqh2cL2pmvoZ5J
9QGSvRXEbQCSrwbobAlRJwbOthNzZ0hbVLofohVdBTwjGfc9ArNve3ok-rGeys6xHyLQehYjLzcKktBLEfFtcAioKnxQ6XLgkLJLzcqLKRuGz4KLWp45i2kg
9Ty4Uar5b3M1IbNUsz8gs1ALGUi3g4ygmg1xU_u-UluEGBsg-Gy
}

