sprite $Scan_Gun [150x148/16z] {
xTU9SkGg38LXDe7V_udlT9o-_wX2qvOZ6wQgDVkIv2lf8Enmf5AEORMAHKJIOgOiNrLMSkscMX-kLSQOofUfRLiJ4SbnbK29jEshgX2lwO6g3zJNJwtEZrV2
r7A8PNVD7MCgcFQKHzcsPxnc3Oz0oNThOanrZzUaCVuTgFI4FYeJhpXnU3c0UbII--E5IGWKgDrLYTVDWTe350CeAZ76aYO4ge_wKmLNl7SRX1UelQHjN49t
NIyInwYKSkKIkYbGARn3wJ6cMwwN4OhAWklEG8rHVygm9Hm2XMc8ohaqudNXDZ2WzXBlU87QEoNXE8egbKl8JrNsK36_CGeJBiTueT9PjwDAyHiZAkNA9r3Q
5NrKkDYX5jHUTNEC5vzMM0zM5EtQuvMyL3fU9r2UyKAbNNc8mgHLKd6vgNIyxAX7CSRifDBjacH6uU8Iyb3fUAKJA8SnekgwQhQWgCPXz5An9N2PKFHAYgDA
nyk88kyqoqcbutKKXQcAmF9JwNWLSz2f4ZrLEbuZLDz4PLULZjS0rGiKLEuVayhcUcMgEb2qh-5oKkbBg7HGu-6rxTc_xAmgGhnAqTKtAIgFNQugFSOEYa3r
JBXASbADNRfHGzMkBj5NnPR0zSg4wmTBigUATX4lXjS9L6Ese5ZsNYeznihHx0KAQctaIevlYLGeYsku3NO8hbR_1xPZJnAHRjdYXQcV9LoO7dLmIoIJIytb
mC6ZWGfxqHXfL6-023fOukK-nlepK0s1GdLSzQ9uTGDLjM0Fr3UjW_MF5mL4JwnnClJ_0Ukz9JecvMgjli3ozyxnGbLA9yi3RAM1FEEukL0Lmy7hOLtZXOfs
zRy-zQijaQmgN8JvMwQmeoqH7SQeLBWmxOWVsFOShk-MwAku80apyUfXkSDPQGvR0bNtULcxC14liBOjOLJrZwF84Qpf6SUYueBixWFNBM5HqQu3Mw9riVPu
ZLMK4h0bZc8DyJAeS74_TxO4sDeqod096LHi2SAyAG5RWYQg3DP0MUA5wgKBXNOr1L5RuhbXKOrTHjMhItk0hVmJAjiOKGtASF0K5vNPXShGhdReJGYLELwe
3hMBarSxsnEhNHLYCgbmOMe_nzWm6LMCqQJ2zJJX0AjDg4nZjAgAJesYT6v9L3QNHJM-j0d_UHLZjAeElmcXEkNggOnRWa3zNaMyK5bT-dhnK54nii2iOsH3
UQfeMJxXQfYkKPrW2TlW8bLCsSWgGg3MKH6lnLH5C5saseDbt17RRIgH9LMrhgcgTKbLQxAa2jTAAboBgRQj_axLIhn2jJNvXQgc41nKcJFuLBLwLjKmNQ2g
SaRLIl2eZgfzgyIkaXWyLQMhojcW8b1NgrBikiGGA5TL-rQ5daiisy1VbUFZlnnG2OswLbMVAboex87oLp56L8P0EQlAhiA5IWLgaeenec9uCrHKHdMH2LKw
gcACOhXU_1uQ-YfSGg2cguYNCBpfAk8bR8FPAYeM0dM_Iaf-svAFQdkl-gZgGghyBwZQKFLHbVEgZwgXce0Qg_8irFXrOXPgh8htgz8xLPcWYbRLHvK-gWFr
KLb6E5R9ggeKvh0MV71_guepL74j5QpnwqHSyYKdJAeuUfs8OHhhzOCxhPh2wgjAc5gfkqP1pQhyGrLJMA1I-LirlL4wO28UQ-e_
}

