sprite $Service_Amigopod [114x150/16z] {
lD67TKGn24JH5K5I_mqxs-FCZk130_SmxqQTkjmwJypThSySwg-deyl3QSUW_lMa8-3NCsaO57TnJdW_p8w0PCvyG2vdFk3bEU45PikWzJa7uT4v-O3rEU5H
PZeWVz8mA9apx-LpYkTFwO3vavv1-Ppm2aJj2GWm5eULUg4ujDIBHQqTD1QhlLZSQzPwiRZtAlPYiU9DeyIyQKQ9C1CUBo8dxz4YRYP0LiIqUMyI8apUmoaX
8cTYK2LMHSw4f-QSY6bvprMLNnKc7r3qP5MO9m7zP5NSv0CAiMemRHGGWwgUYJ1Z3rHcLPX4m3VQ3aMOSK0pKT29LJ5jE2ZetAemV_TysaT0ALaLzxU8WA0l
5HK14VHCdEik4TG7pOfe1_Ehw5z4KA0FnRr0XglYoyIgStyo7rcn4_N6GHW8mE6GPgJtV-1TWuXDIAzWxT6x_pSgo52Pe8kuZZYHpyJWLB6AttVrumaG4Q7w
dHZKRbVdY51ybt5DAH-AbuXGI1TMSHvnMrsT8ketNItBslbCd2DIWbZ4YThhQkCGxjSPvsMwqzMW4AzyAQuZJXNeCqjo-eiuHOHSjlqtNOtTYwDubDRqUv6N
YDztDTQEj6XIygDNAXKq0o3vD-AyUYIoBM84x1vU4XKVXT-ApmqoSU-wgYIMzQB-BFcrs2CsKTvcbD83eZwMoWQ5TJB_MfpsuoBsPQgWlbsMzIW5tRtkdQpc
hWgu1EmbjPUvMxdhP2MbWkKzc4JaARBS9EO9d2kBT5FD3IotY5F2LTGmrLd8T4l6_ZFCCBTbFrPLxIQTgL3l4BLzcsJUY_agAhIRvcxf8QmtYC0HItmKhw8O
qD2-8HEOjqLb7H6j_OUhc9sDP4oTGjqLGOpvIH5L4RcAoOrGq4PwPTuMwvYVAhtI9Be1e8qvbocR8j40NCHo5OqZOymvC6s9Idc4QDrJlOfAsW6IPkvwx1VM
BH6n6TGqQX8BIKjPsAhr8n5x8c8N-2dcKyGXFZ8OLLhij24APUm2I818Bu_UH-OeQMqjMs8TQKmE4e0-NiLJGEjqtH3rd6aAKHmb5r6RA9EOAFU8ef0cvekO
cmW-gmNN3H5CO-EfAZGYdfM4J9n5S4kCRrnnYEHwsacr80n8kaiK6g4AqAvYAbNQypAb_BzIV6XVp3Ht4eT8ip8yzF4zXzuNKmVTGgHxaF1UieZONAjARoAb
g2dDBGOVpTWV_LCbwfPO2Yr4vke4nnMZ7QZ48lDPcR8tS_GKzH0jplj9Mj6zJk3cpAbKqbkHP65_-CeXQXDXBhCep3iYqCH82UD5ZB8wY-3cyz7ePqWpqYTH
rFFhmjaIbPn49pqMgwA9v1onico9SehMHHjtg0e0gaXBK_T46CtFb7xEkTn5cS52sHLXvfUKDRmpP4rpnBn_9jUg88tKcgUpwhZHNynAUUoASPnRgnmW57H3
Vavtf7rHYBUW6SX-E3P6IhtbRbMLieB9d339JNJJqTExxiXr4SMTyAfiOWzPY7lkoFAEf1jXXLrqrXFS5ykxbEP6sdFgKazmMomzfRncT9gFY4v8WFjY_68U
HBwAsPncZ8n6Qs2KRdSrPlfyLzKcUeXJ3rB5XjZ1kA3NoHJGXpWTFVfdVoG65wKaPVhMgVGqhyS0gQNg1-8CjeCKI6WjEHrSBbKnZkApsCqFnDahfNJZKXYX
Px6RWi_5xaNLVfDKgULVw-Pnn30G0p6bxRzbVnmL3YiFs026m9USHpU1a3D3NjRTB7Y5Y6e3GkyIcHaG-YSnssNEjBoU23dJ1Uo9g3Pbm9wuPp9nn9kddlZA
kUtKXeJk5sGYv8mYT4_SgxsyUG2X9H5ofWtOFmD0pjG1A-PWpLVEL07xMP6PCc0_6-JClO12pZW1-voh5R3FIKBzHx9Btcv1BwSjb7FQFCvf1-ISkA2UatX-
JXBgvoIUhvQ4-cg9vwibeJwJU7vE4khd99wlTXM5FW
}

