sprite $Server_PBX [94x150/16z] {
xTM9QiDC34LXPoID-lul_2_2rEHqaJEvBdGHOFRFSDoRRe-VZUso6nxX5_atZpg_NM1Rl9wf_H5tDyJ1SJw4mN72_0OM-ON1wQk3CxywE7rrS7vURN2UYOFp
XZeuywk3CxysEC_KKUYBRTvG1sT-kTtd6HwgivisE6-eep0_RArkM8_ITZS4b-Abt-mQk_IBxDA7NsIN7lCwt6s-vBp8BlsbV9bDlNoTJRry7Kwz-AcngSCN
sD3XAspgvUlmIRryZUrcq9bdtGuRnZBqruF_RmTq-kjHZ5-L_fEseJjlFX6yREhCinZSwedkZNywIjdrBBtn5uANtUdbBmIlvoozvUTZmNr_6lNUxuENZQss
FcpY-AJOQkz_Q4VmavgLNVfP_YDyncjgV5YHRiRWPasPpDEw7y7FRZNdpBFwdeDle4x_d5vKlrMMoPcdz8Mj5bsFjamuFccxrV_KERFojpg3zrlDMNGz6frR
jNwhfHvvFjFvIKzijTJZqMwLR-ZBr6FFhzrgHJyUxLRnXaRFWwutARUAwCtV33yfjjhxZstLFVh_gtCUcuhFjchDLfilAzugyxHRvHjGfl7Zr5Rzt5QPNxnL
vfTkbVxdQufcgotVRFNjhu56xxVQNxzLl64Az6Qh4hrila6WDrjLwE_-mBjCPt3t8It3JsggDN6hBj_g-8Aj-ZLRBVlIhPRz_RQAJ_hDjchNRfM_1j8ryPFg
jngEDrorLVlUMntYhV8DqF-sMhP-gtRnLltRRdLymLPTlrN_rbkDjs-GRfMVzBAjxXT-pLRhPWYtIdlAoZ1u_RMhjuelxHOIdS7TwymZ1MKOV3-R6JEVrXby
ns__TS-Op-WHZk3xtRQju1cvhFjmH_2wiMsx_fBbB-bss7THjbslG_vUvmNiExtyDPt1hQBKsKus-HkTzd5s21cH2pg2tz-jzjhbp_F1wT_bcOtU1-UDDdzs
mVtEnbaYVwDtmNcUo0-z2TvUvCVvSo7u-Vov59p-H_bp8NYR7teJ_BJF_8dWZVrW_dmgE7tcpxV1j_KpvCyc-B9V-PD_uKySVpnpncHmgQy9pdLHPt19_aHm
sVcXmvRbJmIN-fa8hhsbuFy2
}

