sprite $Service_CSS [150x96/16z] {
pTdjTkig38HXf9aHv_wl-AJ4Aoh5IMr8T_pkpr_jip0LRYblpMwLIsMWMh3hcAYC5t51VNQHXReSopN6Aw4oN0xr-MTeUX8-ZxhOpgAUTgLDbTb5dX_TbFcd
L1ZsDp-liW5r1HK7r0LKDWo2AwWWPNOLbPHvCNV0lwlCFlm0QMnrAf1m--03TEohI0BsgQz0KzoI1bKB_f5j1Rirx7QAZ_m3swg9HbNKq89hLLLsLQNOTnZi
xqtm0wfRpbhrjkKoluMMk_-SFU1t5P-fMeQ72qiUS2V0_MupadvCrJ8-dgDDaZQHjaQQcKWh1rIPgSOioz0u8L7SQF7LWBEohp9bFG2JB0EbdJF235AjZPQe
FPMHoaZOAij1qkt5asso_BYZ2YH3ZmAabynFimm7nebjSz7Bdif585Ab_mYeNosn1NS_GFF3eyGPLdPKHkAMQgTYfoggP8RND9ivFNiLxYYmXhPgK4J_YQhO
XwSmz-Ll1KbiCUwkg281b2u5n_PWvbQMLK16nIrHmA1YZTWRWZwWIhQkIXhHsZis9DN6OzOphBnVbIRWrHcYzhHtNUzNaG9IzIf7a_6U_Q6A8h8Z7oTgi8M_
KAKfEpR27ovRHuqgakWhnq9KhRESf39kA25zHrNv2hR8CX2iYOhu-V0e1mX7EPn5rHAB1FYVKbM73KN_2YZ7Cwsn6g16diCYXGuLR2YKCqLZOLOb4QnLhQXY
SsOHVWjdLHQrMomxgn89HVqgVfeKSEAqAbyCoptCV2_F7zCW0kJsy13kEAygpCKo-NaLsLoaSe5kWMf_mp6ZiYgItb2q6HMPAyQWPm239C-hYcBRxoBAb2ed
UMZRtDZ-fN8od0hrlh54-hmg7nwwn3cLLv4i7gGjgOAZAJOKojdkglRNaae_JGovqnspAbWig-3eYiZ9CAToQbcLvIOZ7PCgaXRlLENvHqrE1giaIdshAjHF
1Z-jyY3jhhBtg28d18YvoK0HvQxoLLLEWroqkSaGRQH7aCIwYis1tF6OcWmMp4DwMTMRw3uv6KZB2UyhgZnoSj6egSbWslvJWoHNLFo-eHZR_-TK_G_WiA2A
D06rFnEzJ1QLoLezSOATQHALxygOLsKAzs6X5bdhgfgejLlKPD5NLHK-cDPPi2MLbFTHAwXaLQLhKfMRQjKqtlx0RKh5eFjWMYqlyGWtEwVA8sUS1klBfVx6
xP0gZvotRIZhTjVcokwVvzPBLRx3f6cbVhNpzdh8NwX22wQ3rnAkFHWEVEULyZLKoKPOBolVOwV2EnSAzkkFvv_T71WwrMkJ7GSR_D35k9xy9DpOgQmy3KU7
e3bevM18rexhrx7fUlZDNf0C-JnMMCL9lZAb_VKGD7CmJMTPFguvuEKNL8Gu3i4j02IfqNIS1IkdSf0EvjVDNX8nUqRENE8vIVl-9TtVe-fM25PciyXB_-EZ
XyJF1qugMYBNvwwnHhvH73JHob_dKSKjc1qmmShVPwpfUhLY1kGM_AUk_V5ZzwtpvwO3Rpfun2t1opyEgWaRa-Zb8pdZIwO154dwJ0wsYxY8hM7_h_G_
}

