sprite $Service_AirWave [116x150/16z] {
vTi7SkGw30HG8P7otF_0NzzSJD6B6KfGOtDNSiLNxCO6foqLCTv-RbZDJ7-cIc8ZGZzLTFNdr6fVmpzdoAzH_YcrUdx2h2x6oCyP4fWL61AO5HWIc1KO4fWL
ghL-LWeYE2i-PFsiBYRLmY71MV5QyLbn4P-L3Oz0GyApuhNMpofM5vNia3XvnIGj5I-O9CNYkIbMJ9wRzUAvkVTMBPwR-zvhn9HPyLHDchYgcZHXLJLlkWg8
UTFJ839lUi6us19cNjMNaOJfAbYhfBhrD4GKjRpf1UT54v5Cjr7D3ycIwpQgTuQqNBSnBJya8zt6WjT3JhKAPBgw5YSCxTRLwqCwhfZfwdh8-MGDw3OKlAvr
mk5kNNqjMjFda0ns6_FUz24d_4URJz6yM-2ThLyo9ypn-sPlGuscpUQCENxVFDH-kLkPSA3RjWyrcZQPyIy-izlc08-2exdkLkJ-EuTwp7hQhM7TncUE3nRl
32y5klLdVdvWFcGmmnKXtSxFR8jk9LnHmbmyqxkrOCuOtEqds5rUx3cVBDXj7-2t3rRTXYi2kfsUUPZsXDvrwtW3xdPwvghRU4M0ET-H-Vk2wSwC2sBw7vV5
djyDUOHfes-vPuvdVfhsodJCHJuydaAKDhtWztlo_5BQY4DKYlyF9jFd3Jo9K_R7BhN_1tkUh8nIG_Hnf1DkncvvuzVfZ__peNMcdopJ6r8-7YEjpDJnKYTZ
xE7fPQQ8haZU7n75_qzjGkz9VKnfPTrAE9zmGHwjwbR2AyC5UJwegDiuPhmWprxKhJUxl22FLfZnWE85pUsMTBlnwe9253ULpoueB8gRnCiBYc6ysyG5ZHXi
SkA2l5pK93LJMLnGEDm2qzgHbwvyHA-trWWrj-O9hdt7zJR2e2daP7Jt-NbJfCgChWQkokGs4js-krTlfeDt-u-OMzvaqDJDqYQX9ccMBFWxdhEcmcR-Y0Gt
quCIRARBrQt0J3wKSLEK97UrkAcMUoXNc2p4gJKhkbNTz7ApLFKrZEljSjtdsKJNK2dy6WPld22BleOX6zjrSci5tUg1afrlwI7jY3b8LI7IqulrgAhrU-O0
FRpgLxOvPYhQacOanu-ZocjHoJKtNKsRNqGLOJfK2wsAYvCvLEltpKzHPAWaQXF83WNJJcQrfMZo31_iuLBu6dKmJmksarhdH2oQGSsOGHpiPTFqxQos405p
EQijXWJCPS6s618mWxesLo9j6TDdrHxCK6lsaT5SpsfuhMlJ2-wlJGDg3UPYLWE6Z66DN9pLi26ZkdYgpshWa35ogXeyP8oUp6hf8V5PBJiaFglaXyHdpTUA
__BSMt7nI7JMVAtuh7aHdpK_93vh_f7uh7aHdpLVApvhNiGBpjUA5vmNyOBpjU9gNiHdpTUApveMyOYKrleV
}

