sprite $SM_11n [166x146/16z] {
xCx50GCn34HHYyFflrf32uk6-OBpIpiYPagzHy8itJCvp680PMr09PHGGWabb5JhNyarwbvf8YRTAwFMiH9AAA64KkFa_0ZbytzotqEKlzVh_QhtRhzLQB4N
RJjH60p0OvAVS2wxy_vlsw878rcmmTJ-CxqedhM-WX1a__EZoS-TlATfQUvao_c3hrU_PAyhQLSMW-K0PTLqHbLprfHm9BdO3VXspRcdP2Ac1UN6IJNnhiGX
iGuuZ1uqGledtDLtHwafAQyeXPX9jg9CMecNlipQTcM13vHueqnzfUgIaZG1INVbqOLlHxme7Q8Rtwmv_vsof2g7xwKvtLkt6drCURwHC-MS2T-k-fpIcEwz
j2mhcyi7bKbLrMPFdUG0rfJjXF4DZogRrJgFb9xfPGu9FATKzIMbpcZ7ML-9pAnFAK_VP-ozR5pj1HvJlW01KcfUpQpFA85LvROqufUjnJdYw2ZJkd9rn4qa
s_iHxw_gCQL5rrTrPe2PUafGwSlQaK5bUcJsA8H5kQTCuCzVjWuvvVgYtkn7WigIaH9VhewlAtjWlwfhVafvNTJZ8zv_GFKlb0nJlW0Hb46hoAYosnvMKa7r
-d8qubfYYlLek2z9W4O907K6vEuNXUhQrgtN75Cou9Is3gtC7jnQYM9zMOnUQNteTnk8A16hFQOamH4HtIFoHscz6DrjZ1_G_Bgft0GLIVnpawICk8z7gge6
bYAha9sDXVILZ3DiIlxwPL-pA_lBw_LAPtUK3DN4Mq-PO14Y76NyHwbEMH-FrF7vNZqnCmdFb60YPYw_ZofazklbxRqwXhjWrPHKvqe8xr2vKyVdtps-sUhu
j6HlfkoaA6q_5AkGQDDyKEYQaZ1HBlVbxIcErRxS16ccTCYUKbLdiyTQtCdWN2d0N6dxZDc8puVSAnVwae55PKdilVHCNtfcIXAiAQ-hvRn2fWbplbwQybeE
TG-6IdUqCQez3h6oJitcEAE6MVS8oq3f3gmhSmZftkytwnkbqBKOLYNnG6d0sAfkSOtlrylKri9KDnQJlYpEo1m_xxdcusf92I8IG9X8fhDdhfnlCDk-N5KM
NmdBk496loYyqY6NHjoW9UZ6VO-7AYJ6n-ezvIQcdCUKRkxSN2_h5wYkdRa945IMN9tdDdXXo57Y7XWh2GWgRQLyRg_Uh-CaY2ex9uEr-3Z1N3aUSIk7qRuq
dbEkxuBTFwCtnnbuG1dVkG6z1u3hBfXG8wnxmBUK5Udwylvx2MEwKuDDhcN6bUpbsUFhk3-1KNMJOnHqpjmQ8yIKT4_vyUIvElmS9w1LSj63RlQb0QDxekO9
_ztZvWaJ4U-_uPwo9AJi7sUvlhJvxCu20dCyhfpjB-yjEt6b7absecJvQUWuOSfrPrnPOLP8wtFrGVIGfemw_NhvzIV7Rv_bLv5aIqTep1BD5lTJhrEfASML
___ZlDGIPdw-Hlb-9f-gCsSymdGx_tMZ-g-SJA5iFMKACAF6k1FGW3DcZ0-x_gxTJd0YYc4O34zh9zp_nEmxMD6ZFpx19zbgM6QwcdPw7sRzt2Njj8wHFvLF
gUBc2HY3ygwfULg0CIY1sgb59YNe56FCogUSrYx6c9N0F25aLYAr2p0cfJvvZbub0yQWVCfJoUUr6p5cvMqNKBj8v0hVlpnr6Z069JXFWSQilAsZUHem1YKu
Jm78gBm-psvCkTQWZF6RvkBH56hSVlEmjOj4kdMRiliFJdD6TUtG-5HxJqnHPLVliClHERzAWWRP2aPWdXPKjdSmvcCqEr7ZxWfb4_E4Z3MKVNGq_U-395ub
2n_azMYgtRQEonu6EMSDHzE12PSzEsFjRqfR1-VGmGZEi-t1EPx3OEJcsUNtICmWqNa-lKhbBn4nIBvsVu-0rmTtbhDpFeV1oDMUbPReStXyDFrR10mIhRtz
Qu11eg-IVus0ruUSPmSbKZPtDEkIKXVE8JdF3ahW79Bp3Cg3tmxfUKObC4Yozg04NXyo2hi4pY6Q7PJ08D4eA851abb1YGwIhrtyEUHhj_YoUQS5dqE-zZUb
cYsRTufyVVWilIZD3v9_bSeRD_ArQ_58tYdS-
}

