sprite $Smartphone [62x163/16z] {
nDPRpkiW30JW-XxO_u8FVU0_CHsKW5BLxvyouznuhGsngl1hRvfzZz2ktVGagYVEctRzygnW-9wbXDOu2O1HgwjSOsIzr5eFbPt2zhPlhUk5xNZJQqrYiF0j
pMO62WEDhHaAVQr9BUaK-aAJc7teA1Lg73fh6sr4ry1cRSTW3rEaITq_T0osk2hG9DvcmFuHMXLfDayQ5cu8QMwmwsvrB5nCaIRrh2U51McDI7fIM0HeySWQ
tgLcWIQBI1g6DkauQV8uQnYwk0ZK577M1XzBaOdsivuKvfdME6bSc7cguxysU9U4vrgEFsqeTBD9QzBsfrtL1rkKEyOwZYakpdoXZwvDBUDWkgrTjUJ2HFUr
fTp5gEDREht9pZJHEjFbL9YobclT2olH7Mr05wFNQrTxinslwaEQxHelRQwrIQZbXYwqekqhcdwlyShNjJokxIkQ7j7yjDODBOzh-ugc9pHUshgMnxLzHTFl
DLxvkfR7jNr1hosjJ3LVQI-rhcWzwwFMYRuE7etkQYzrJtUBDLteV8uDgETBYtB2HLVqUFYs5JqUlaDd6k3uE7oFcgRQouXDxQR-nuYzgCOEmq00fRipacR-
_uClYft7pRhDJjyL1umYP0ZBzmHGQttYr_BGys4zwd7egYhvcWB2NsXAcP6PjuxHpnfbHP2Cq0KJqAD-XwtWI9uwWF1QdvYolMF41G-TVsZKwEsfJnmCk_2h
Vi-3OjVlNIT0CIp-gZbxL2_E_DG5c-50BdKVUWRlYV6Z7KCsev2rqk_qaTUkNt0d1ZO9Ug5V8P_vmQvrl1zoQq0BZQkrNhZqRFPfwFA7VfV_ptjeS8uMjUbS
J8lJzt16BHgxTQwcnP-f24Q4ngb3RbqWmnQUjBjISgAntRe0jOvdRKcpNT2c0oWpN8XdFPyJM5CtDaDWFMibEcbjke1qQqAFUbhAGzSvBUK7NO4HU-WyfoLy
qqoTKWUDt7K2kUa2VTCTHXolZAQLQse2vTPQRAPLA7lgGkFMuj3yKqS5XpksGciHoVYu1N4UcUF6FBHuJ4iIOOQ5csuWfAGkNtGNOseWt6MYFhN7zwlk4YNe
k4NC2DGtMdDzRre4vsOAF-jgswvrura6zQIrKGGyT06SpO5yrtdLgc5JDNK2eQtCvRGmif2gIW3Jshj6czQns4oV2PxJ8WBfJGTYiPaGlDAIuz2NjYIerhpf
igeGcQN_fqK4EAU5nps6hwQbHWE6Fk-nxtGHO7deRDnbVALhBlAXuznCNsZmkfaK0EexFSU5LLCNWPhts48pIqEB98QzJWj7kR3ICyIHSrhsvO8wyLAVunA7
5ezxJ5ZhKWK1Cl9VfVQLn308nL0qTCZ-zvigb-To0VsVeOwLOdlUpsfwJ1czBMdNOoQXf_LmsPvCCxeLxRnwpCQpBgR7ZZWwq3MTUimcF7Owjvsk-QB73d6R
LWt6l5MAwR7BVx_7U-myRwDBsIQNQjltMBx0RjFOOpLUZcmqzDZLm4EwPNfRW3NOleumQT3giOl8AhR7whV7cdgC9strG8AHe7d1yzfOrhnWrZnfrcnPywHP
isNDasRDbZLC6bAauLf2eZHC6kAoD4oQ4gJ1KboKfadpzC7sunDEkkzZ37vsu3S
}

