sprite $Surveillance_Camera [150x150/16z] {
xTaBOkEg3e1Xz8RiVy4tutPAeihaWHnyppd_2hv12hN7vK68nDU84Cf9GfQRcE1CfXx1UbCKhZG1oqwCoqmallLZ97aGBLWeUI9SlUHn32kNVFrw0SbBqPeb
Npz6a7TYM71GYzUBvVrmmKcj6oF8P7G42aNEvy90jNoz84Sb3BaeP4c9CkSNi5QF4P15LLohnuXQj-nKBgdVcOgSPRsmzj9SZ9CgxgWJZL7gVNeAbrQNfRam
JxL-lRmgVxq8abJhRuckMZz6hphS1GcgzUlbLUjl2QzQlrvZrVe_Gbwr_fRmglNhvLNBrskiMdzBTDNwCNhLnrsSeSeV8sMeyXzLCK6LFqQ6ULM-Yn6cLJvB
KE6qAl-u214cLVaknckJgdmN_WccLFct1F4rmWbL_d7nTmGJgcGNzp1RrREtKKmJgipZuljWNZNlOfvLvRkOPrNvwyKyhSe_BbwY6hkOLwZ6OsHUe-ffO5gl
gieiFIO-XQeQ8j9NYCYhLPtLuzEegkBVw4IgAYEKYAnH6UtDJ-lbJyqMgAh6HsMNdvfyNbKfG6dRF9qrKd4zwB0SQfkTO-shg1uHEPMqow_gG0M7g0J9eO8Q
bjti29MXGuLP-Um8ZHmgZlT7Q4Um-AQEyhNosL-X-5zV77tsiCJVdN7wqSFgAlbDgMRsFTLQzjC3LSsRx0khrI-M3-qmbVbpOYBU4h5sQV1HbiJpKxhMNLgX
V98buUzFyDgTI_2JB8cEIW0tLdSz-h03OjaglrKArz0TrwCFOQZfgZjKXRAn8fVWuAd6SbLwfy9IIdUvCGu_Lx1bgbfqZSTZtCAZrqlyhZS4wApOfSfmwAzH
_Auhmb_MpdffRN_qVE1wYRki6Y5sLx1UsXu-eigqIznQLI8SkEx_1N3KUebRAw5hZjLTxc-u77NPYxiNc9bsZqiwoXrMydh9_R8ttbYnYuUFg3uKor9LaHiN
tBce1O-eer2JL2ORAneZji4hMV8OlKhbMZX6kyIgSMmfAjrnoUKjLK6TLrNzPhdrAjZUL1LWcxqPggc6nsKllf3r04bixXPjPg6BBnCg9DR9lpYTTUkgiOgU
L16BpJmpj6h-k9X8Bd7uj8fPRUAfRsCv5zKOLSiBAX6RU49kzRVh4gTFguXPHDJUVCVfhiuIVME0lQuIDNj1nTf6npKnGATIjHTKpEPOjwuMg_WjbTaBAiUo
UZF66DNWJPKzgVAiAgprnsKJHnMgx0KLIsrVvoHyJUoRPJK-gl8HbV_InLQlxQhmHHNVgSOquVr8wkOAbrtAim5Yf5ArTrJuzyqkKZMOLudQgog4dpUeDeFo
AhrH2QkzeYAuVR7xZQAIeoBIaSgRUb9hW9fNsQR2GZPGULEFhGMeD9L_uuXLM7nO_OUvN5K1TgfeoSSimvAaqaqLlGcH7rwSzbV-Kj9L_eLMSMZgaRLhras9
Al-6PeJqOy8o3ZfwKhMnlbNmwx-zZ16Hd2axm4Ug7h08urT4pfIB6gg2hO6loe41lghg7Q-YKwdmJYLUnV_VglzKjzVeVoeuhyezkAzNbJEguijzlQh0UbNC
6ZyYBsgeWhAgaQgiQr-5PM4OgbIeB0qeKb5P7VnMOJb1GBSFeqhbB04IYnnz8_mF
}

