sprite $VIA [165x167/16z] {
pDS7akiu40DGTW2RU_y3R_2eLb_6q6vMjMoYyezl19YKsmUY7TBsZlGnHjZMHiJuBzYOQ376vaZjOsoE58onEz9Zx8wqFYx1dcFS72c8iJlIhiGEGkxMTDTc
ko455s9uQxiXnQzDGzfsI8tdfXiXznfZM6kx8GL1O_mJwHiOUOnFI6nux3H2RZX6Hkvqx0IaROSqFdRAaVLDRuRaEr3Q7BdJ7JX7YgYgo2vZP6G4_e_9ryOe
htwSZajSld87oijPWEBowJkmlroQuTV8Hr_8mkIH_6EyNobFOtGHcIiLyyZ7xa0LEPEf-en_wjYHQrQCW7tcsE4i606v_mvK-IqBHjWjO-IcENaZSE_tG6gQ
c8f4zBunSjEi56HYjuqHJEGuKhbhZAO9f26NU-v0LzNtIaKoSalJHzum9mlatz3wR_ocPp9byzjPET9uZ9fJpczghqKA7JkKbGSPFqWZPF4Oiqe59mRAaTpq
9Ca7sKSvqeARNb3-PYn6SjEcBvDua56AP28rpNbx8VgeHF8OtMnHgMoqIYJVWVR84fFRbaeaZz5iMSbjMoMItdRC5fGwRLlga3PfEi-S8BqCAJ5fUbN9azGY
91yxb3JJgUqQ91yxbBoIsYv1MfytlSwaILe9CaKyiuhKSYGtpVaoCjnIMK9AAJBWbipNaE5k-Nm9sRr0UVScknSe9qWlH9Om6QaO1vADWAqXIvICz1YFU6iA
nrCShal82YOzgZY_pG5k_2GTBdbaWNAEx0wuMU-u9jpCeUj8juMaaE4ETpCRXEncvf0bv3hpFJBWE6wA4RXc_20rYonHCZAEfX_f0zVy1JjNcK4MC1bv48_u
qwCSOGwOfP4LIaO-ndZ6uvmb-l5vMa4MC1b9hos84T5xZ-FpPBQ2B54Q6pcEtZlyf-arP84oXJofS2j0hZ8DaKKUJHSW5vKU8uiyYIN8FBEFaKEUOwn1vfKO
OuxaCTOXyqh4I21fZ8L8Pl8O3sCdvBJfUgI_7kEHxY0a4-kGUURvNWi7nMcC4sKDqXD4TqRo63aEAqBwR8pdgxS7dXAJfccfq0eaCxsF8_yqSnywakCm48RH
9akwUVy7lcGJLsZf7_3GHiD4shpVgCgIl67gwfq_UfkVN986fFAu1vcGT4K9I4-QaLA-Ra5chiIH-HzolByzh6SW8wMu1vcMjFt4Aqxzo6Vy2Ce8oAec8ANi
ZfTHMSYJgJ-chwDAtqDQDG7PLihBQ4WfppMUuxnw3ouZ8wLW92cPw1NHEPbrywwhTqDOI6GMSaezffTnHNgutQGDQPa3igCSdlIAp2ncbpY78NtonKYfNyPT
sYSp5o9UJG1PcGDIJBIa8UlwkjgNK4PA0KXK-Xa8H0bEUIG2qZDVaSmSd3GW6_TaHo8JaS8oGjA0nB7Je90qWKYfMSOUCWMNq253qXo8L1R4Fcem0jBNROhU
Y38AYPE8bBfbPAIlsrok9XTnGRx_1laRKlsa4v7sAoWYx6C-YGjo-MtoTsINg0X2Jl-BQicJbZK0Y3MCL3FfF8w4kCreOsKq91CPsIV-Cx2IOsiqeY7P62z0
zfDcPEIEE6L96nA91-sJU0OkmimeeoChx3btIQ_xA1DVi9bZqjebdPdQ8lLlicD26MsIauQpUz0Pg6tIHz8-EK-Jdu5Ez67Y3ibbN8MfIZftI8qo3KowXigu
HU8PA4Zw-afia4KifNrz6IZZ5ZbcZoXF6fxkj6KRTT-XeQHNv82a1KbdWRT8DvrNy3xIYOwqCixMuv8LUsRia2RIjGg10sLyHqBIMfAkEfv4ovglQlDiP38I
bj6GDGtYiIHjUn0XTOQjuDaG6JaM8YOTddGIiWwUZj6JPkHaeIUjzwHpwQJFgAS6Pzbs63cr42dfzAHhI-TBx-yBkIJDo3aM8Xw1SO8lOYeGcRFsjsmdpSZ1
GawwlfAv8lrzPl12Ef77aaRYlwIuY659-mAlo34N8n4hQHWdQZk7GN99seroP4v_j-wKaQUCmaapUj9n9HtI3ZdX1ib9yzGl91vFses6pnKvciHm3IEToPE7
9PrnWPFtISq9H2WZZwRV9ta2auuZuSH9IH-KqUOO9tDqLZAMHyaQko1RsqwNENkPH-ILRUmV9KPoqlt95jEILcGb7MK4v0T9G-PJF9HqmdtoWwIPsSoyRhoL
z241iasyF_Etf5ECv39-C6fNConfHlRBU7yr_Pb692Vz-SJiLpD5o0_Em7khcH8YkOntpQjxKZAIotZ_9-SO7oEvZD-g9YiRPVngDHd9PRp_yq3D_vzsVf3q
lISb4pDDc8d4xrSpOI3fMpFFPkP4FBxw-VBc4ubySUyd_GLSTplwTXdvfEJCxq_w_fFoEKJUZlI0f9VjQ64-YSWdvGEIffEIa0ln8TLyGDADazA8pvbusuwW
Z4_A7ChugCoVapIVb8Aa7rLDMTBFdFm76S-qUURwIXd_0W
}

