sprite $VoFi_Handset [122x150/16z] {
xPg9SkjCgqNLm0QQzt_WQwHMK5JM_IRY_DCwyv6hLZP3ItPbUq7CjFq2nFA2Vq4ioI-eXonuVDZCSiA_PnwVRlDlXHvIq7zBw8r_F_JdXun_RyZ-AqDVr9yE
_L-zMHNwVvj5BB0NaF6vq2JgCmgbZuGcEQJJJI4Yi1cJVppq44khgp0L6g6zeU-RHJeZfe7ky0pxmSqYoxIWjtWuzTQxIAy95J-fhj3mdAdJEyRuSJLNth3o
7cP-GSKCRzyiJx6UucqRWs1cAip2_MDMeUTDl0tDskSlY4YtkZRBhwMc_3yF5sQ6pV2hMbhtcZKIlaH6wEgp-7Sr8hZDJ1O9NSm-QPbJhO9IQqpgCej68cKU
qsksPKu1lkrMLv-1iy-L-Mgs0C2bRfio0lRGyp9X6l9ivgvMCm1BDIeqpSbVPh-P2J6founSNR-4bfYop1ek05snyAPg0tgVCPdXAYBgCL6ptThgWSIlPybu
GJfZnwNskRdLs4aFVrEJgAbAmdG3CKV3FYEn2ftKLfNtYdNKc-wX2qxe1lFHQdILMolq8mnpKpKJaexL4fn3DfcUONLNo0iM4zBmhd9dlPKU47E3x71YJDvG
RtpLU_wHLdXXn0sF_uolUkkpjhm9ijwpuJ1v2CrwqGeNH4RaeKqp1liU6cugxxr4h5blQfgn73AkAYkUl8bontnZeLyxhOvdRpAEUgDfnk3hbiNs1zuN8Wtr
7gXw-sx67tWJfOPw2nQs7ax-o9kG4isGhj1-R1R_eJUVrvWavcW9NKF6V-1DijuMshHOi3LaV-HDZ1g6JEv3ziVURR_cOLsXTPraV-0TWtOaWZfEapLak_31
MzgcD_ICUxtfOQvsRQ4HqX2wblgjjxG5HypH5TeZ-8rtMUzuX7M5rWY_USU3blTo1pM4hZjrcP-q0dE7H8HtXSQCa38_FWCdnZCYq1LQwnduMRjWZnVK5Tgp
rK-8-GNMD5jNwAotFIOkhQcGHC9TeItUg1dgBaHwMfcIIBpbz5wXG--Jd1WHGRz_QfDeqoqBU_T02zRgxRkp9A6kq5PgbDODTCUYeTw2Ofvgy-BqNj_K8mxG
5LfZgSkilBIx6a8x4Wlg2ksHAB5zysROCOW5MFbZOIsFeSbSQjBoaa1ux9zFVyrtd73NSM8h2X4Bqm8uCyjbhJg63FTwtmxIpBoQVJFt3zdjzY4Yp7nRwFOX
irCjz4YP-uSiKNh68lg7JEF4cPxGABg7B9du0xERUUEGLRsVxzZOBwgQvSj7rv1fn1_5vlIQcwag-eQiwltSRLLBBI0Y4THSx-SXPomjCmbgo5hhNRjTsinx
Q6dmNY7kh_SzDelkQHMf7KjSeHlhNTrUQVVUCcjwISuNehdUnLI1wj9cMfPj22mlUTf7Mxsjf6vhabLnQ1CLs8nv_BUtFVXNgmtcxgl8WaEx3HOXpQNUhwdC
uBPwOnxYBssc5NbfDsBXwrABmCEtjdfhclTHJYtlQGdrQCAwj4oC6I6zzHQKzWK3V2vrVKa4hStgghSBi7k9MMvQg1oNrYQWjzvJCpPUgC-mRsaPuqKs-M3q
rTiYcSdNUgdfUN8Eq61eNjjVO8trzbYudKiD1Q-btXY26STImoAugTvrYivSwg_R4tZNRhHlsfnhgM7XMz_vlMR7V6dNKjTEawWT2mz4I6EzBIDBzJO1dpjD
h5_dZ6XjLbkzvN9WKxsRPMJSytZRNudEUkS8xQbUY42LQgdpUch7Bav6Sxt3JL-OxxckIqqYOwpTIgoptXx5MkfJcsanI2wleUvM9zDCRIsrdZiz1CnhgQ6p
XgpZADFOKLrBBMkfQxbashxnG1qdZQt6jSYCzNpmxOu9gT1zhJxJhY93lhPBz3ndH6PjLijg8HifAdpVwRNKkvO67GVFwAfttJ0X2Q26Rqkzxk4CYmIjzRPZ
fLuSTyoLTfsgu77ThT7RwhTBlGvp4XBHdaym4dwtrVFOwUl9cKCXH3nlnqbVgvEfxbz55baFtqo9n8bl_VMkks8M6MDSnfogtjohdcck0plDiXu_YNUzjuNU
-DqDaoXLA-pOnX1LCFErrTIiZXV70gkvrxTEciy94IBf2xqzh5Q28x8h4R5EJRLMfzjRNSpTJFCelaw0YRmlDDrRNUZLp5CXby-1iRMt-XxQZD8ioopdnQrP
xMz2kp2BJm7NLbVeldUOzz23TBweRpctdjCx6O-jrbqzI4Iuph8PoHpjwYWcqnjuLrkPkmRSRg5lCAyt7xGLxLDs3ys2WhT-zNmVkhHbRbPhcUSzRY7R3wZj
7hekFfdxrREy3-PcTKsPCDx3sy-gf-81sdv8RJF53lnHv7urpFqXi505RbS_msNzf9h7zcCG7X7QVfI1zz3OVXnv4tTi7u4_rzqxGr3Gzb6el1-7MFZ_BVF_
0G
}

