sprite $Wired_IP_Phone [150x118/16z] {
pPYBSlCi34GB4f3tV-7_-YLdAe_eKiV4EzTSd1vs5y7qwuoAMVcwcshxHrxlnUJjZ-msJCLRGtOZffjn6JIet8a9-GUvQijbDobKLFq8rEWGt2R6ydZyo6MV
eFgPo-jcgFPuI5nxczuV3xXkOPUr1jK_N7UmgxO6bHHZtH4UL2gNbSl32rHQZFNgyA1QikkwQO2WahdgXdCFAZb6kwHG2PLkbzVBBosWVCWkmkiTiyRZDtQL
zpEDRqwCpAuDfQzGZFulMJjhrpkP-kYu9TXrNUcBmJHmgojsNLPw2-7XLZ_OTS0RrwHOQJaMWHViwjWcsLLFxpmi6bWMseLjQBmRAoqKhx_RXMsgNNvk6aGS
B4CZsPJJ5CkfGeqKho5ikoB5ua9ul3wgdqnHdmOzVTtEsUNBeppPVYsyFcbNEL-e0swYFlJIrpFJ89yEabs_FNzQJy9ByQRgOvAYNgwEpslRpzsTLqXFqSk4
2f_pxGSUK63DxLhfF5Ju34vwECEKOpKznJAXOa5zDXqYaspNEbOF2nBckIFLhjK9qUE2b489N5rDiKwfOkd7l53lIx7Eg5ZGV1heN3BMb0gxkXOUKaRgMAXy
bZ_RRvq9gLXpAepkoqn9wQNEvrIi2BTqAA-r-eyfTk7iWIfPaMwKrNzbMOfpBAiv5HhhJ4-jOV5mcLDXbmxL_4KbbAiX7frHeRvIA8i9HgL9i9oYKF6i59ut
Vp6vfrGHooeoXOeK9qoirPwJmUs5X-9FmuJSYq35cYQ5ibWeuzMXxwYp8DHQJQWakq3ovszRh8a5geZb1WxhiY9GKVgiKDQQmUHW-Png08CuUw0IInyBvSq9
pu1Tes8b1fMIebeeh_RilUTObfdLMe5Ai4ihrBU4BGnIv4Sc5WYLO5Se5B_ZU1SnFRcQjfgRrRn0DH5Ok89vLb_UMHPmJB7NYLbGgQMF2mF7Y00iIux3aLDv
hGKiCKLB2uLrJ-zW8iMyxlPw_9_2r_4Bkpnw1oRUlJ3zcA8dJ1pLRIpQzVfpt1OyALGOO3sfkpt3W-ghj8TQUkJFu41mi6B27bBinqAvnMjDxIifnjj2B1GG
ONEGuaZ22vSj6tgAyqAn5ork3bAaxiRZKBrKciGL3vr3eU36Ep_kHG_J85B1rLVjeb0UhUEbEK2as61gLZCgFSQENSUhkoVJDgYF7Wjrf48-baeFW3SdJhp3
gA11eL8glLwa60fbOEATjxdSwfGArIMxyjk20ve9fWaLzLgV4R5GCoIULAXG6tBfXQkxoWHLejA7dgAl5OhmT2hgjNn9fL1lPq8cstM-K301bQYs8Tl5ylqg
9hYwNdglLnOgngYdQ3-dv-UOa0-zz5U7fyU8NLl2qsCSVIUJ7cFVLAYe9gIueL2BzHfzPtXwlSPE9hrUesyD3vM-LdetdUcwUetDuI4ROeg-WGaL5-oI2xKX
HkmI2xKnnhwpKFgKyDrCgBISIWrlQxrSC6f_ZBwNIVo_X6zaqWyXtmYbJmaNcFRNoyMTjtTA-8UDWci4Ae5fSxtyyqoeGIKKQdkzN31gVun-8oQcXD-8YHWT
g1jnsRdd_mO
}

