sprite $Workstation [150x188/16z] {
p9I7ZGH13CFMGRFJVyCVBkSa6oTMG5Y4bmuiR5730e2QLs13kf2J9m0nBqkS4gOHr2Nn_V5mWtI1e6wG9X3K3S8aWfB8o_6KT86WYBnQWbB8om9la2uH5E_5
1wMGboK-8mI28cOanjFnyWHBci1uxTyhK4HwytZyZBoJcjSOg2OAhEOgw3Ncd2kgIUEjEiwLHberUOMnLYqp8cYhfhn8gxQyAAl6l0YhnhoCi3hGCIDX9JJZ
kEKqwhsyeAjHdTSlBVQ1speGn63uUOTSvVuNVcaY30dCmE9QGKt_CZ_JZ8fLCW7ppVD2hDAW062-Trx8LJ99zJONaAiKJogzS1sLgsGwgTRd1SGgnJEgnOp8
LJ8PrPeBI5MAPrLoXQPOnTEXIAEApeLSLMUJKKKk85ODd4n65MK4CfLCF9YCAd4XLZsE9j2eieo0KsM3Cgh81NXL7AzNoPMO04RnlCgx0jD4QkfLVSOUDIUH
3QfNzQxUn8tiLGCDgbVr6T4TIgeaNgzg_qD3UwXMzL2yNEKpeZrKhnhw0AdAku3-KArgsAygLoaZ-aCPbHsKP-MgteGTXcf-6jocyl40V90agwenETOjghal
RloQWEhZtQzIFA16aHW5gRofoh3UhU8cqm0nHk6eUjJ9L0qhKncJuWsGzMqwgen9hDjKSyfKCabbuidaZvMhsa4zKOIFTxyAqmnAdmADgM4jgsJIe9ueyaSr
QE8vrhhAZBnsq-73mmogLs599PCV5FHHEMNwRNo1bQdcRjAW38gO7nkUfc5OCAnODJSU1kLCKidKijPLc_xqSuC2ZKgebng6gjr4OXJuBJiS2jZsLN5N2INM
lQeoWm9sLP7LgdfMhZBnz2rPDG6f9Bem-5JbJVgMv8HNzQnr5Om9lwQQn88AiGfbJB_n1YTmK3qkiNALJAT1WQL3eLVrh4Y5Ai0FIeSwgYwmOfKnOOpwDk77
H1hLfOQ12dvGptZ4MVK81f-go6UyEiJ3MHKC7f6Anq5X4f7Aip8LZuDIFAyAM85AQzIWnfn0gme6VrN5_SaEogk2mIFyFMW6vLK1ArUHPKoXgjPLEbPfKBtA
iMvIGQP0rR1YLM-YKObriwh-Ce565R02LU5lquAgLbIWJ1RbLJrhNRLjR4nBgcfGyMF8ZIfYSVjOLP7NL9xbJBcAx5J1iHHlHSLUzJhBc58L-IPL4aygO-fL
_nfMPyfLv9fgk7YvofkygcCrfan51Yh3Cl5o5LzNzSSI2eafLtMi8DxzAfc-loTILgxoh18A-2pcFdHaXq4e30C7x7t_5xvbF9wIiqGfZiFjTJ-PNrEaJLH4
KEUhcDLDNINYTQAAMSr4Aj6Ofs9MCx5AHEja5QDOHNbTh18sUP3gCN63wkCHgf2AyhfQ9Ly7XQW_gKh4wYoLV2mF6Z-PoZoWWZfBzJQ9f2gD_mFL6AToKh79
H5YrP8M9bZ4gVuyjL8PF4wlu6cCtGJsZOXIagsXvcOelneQArvEgnQDYLx5fNMNnCH2DOof6GULJPLz1hQdumcVq9w6wGyMc1lbG6Rv-UrMbpjUUjoUXub6t
gzW4bQwYtrvNAR9hsFJn0KlThEeesb9JaIbNMNQzdrh_U6MxYa-agvYQguoNz_MO4ctg5XMRMCK7nQgbAPOFlj67riWgljY5LMnYrTA4n4GkKf59XLIql4qg
VvcCKCsLgfOcumzRKnEhyg0OnNcLxLT9M9ZATXK7nM9Q8wjuUJnxLSXDx28LBM-0Ye8YLBh6CiJ4AWwAKVbnbG7B8nK5nIPWpLN6c0JrzPzHK8noCxCa-wOQ
OJAF_Xw7d_BOP8u7ohEyoW2J-lFqImzgzQ3Ch9coyogr33ArsR0ymCtmH9abtPyqoR9Q5pRv8gZ-cPRs7mScUPmovQ-XnCZKWy9Brt-aOmetbM7BeqSe2kgn
EnWS_t5uA9rMPmDlRuNLvG4zxnuKp0njdVX0GGUOE2XR2yhDl0NbIsMSFISn7n5KMwV3q9TtoAIwFIXV3-gj-p3f4LEBPrnGRd0pFnTKqr1Gcfloe30WAAff
Qr2u8YXs7Ng4YXQKZmsArvW75JE2ub7V7nHQK0zL-oCodNSjWiBseF0yCOCFM1wjSJqev471EfCEQjJi3ugNDtwCJ1GKA2XqarrZ0f5s13N7n46rZfgAWfAB
Wc8J1-NVGM5EK16xWfgnl8ZreF0Lb5qRb898toztlGbUkWb12VwJQEO6nHF9hJ1-3If0GLsaIcxHGK5v1E2We2uPv7Sq-Iqe12tlgjFAZkixA7SAwignahk-
WWeAwbfNpLqS56JMU4tpug3cZQwiSIMeE_FAWfgOLsBYeERcHSV5oxjlZVSlZnybRZRbZnBt1yLFGZyb2-hkl9BbtPjNSGUPRi-hyFBk7_FPfhy
}

